#!/bin/bash

. config

# kill long running wiki queries on new master
mysql -h $newmaster -e "show processlist"  | awk '{ if (($6 > 9) && ($2 ~ "^wiki")) { print "kill " $1 ";" } }' | mysql -h $newmaster
# Turn off slave on new master, to avoid replication loop
echo "slave stop; change master to master_host=''" | mysql -h $newmaster

# Change slaves to use new master
sql="
	slave stop;
	change master to MASTER_HOST='$newmaster',
	  MASTER_USER='$repluser', MASTER_PASSWORD='$replpass',
	  MASTER_LOG_FILE='$newmasterlog', MASTER_LOG_POS=$newmasterpos;
	slave start;
"
echo "$sql"

for slave in $slaves $master
do
    echo $slave
    mysql -h $slave -e "show processlist"  | awk '{ if (($6 > 9) && ($2 ~ "^wiki")) { print "kill " $1 ";" } }' | mysql -h $slave
    echo "$sql" | mysql -f -h $slave
done

