#!/bin/sh

if [ "0" = "$(id -u)" ]; then
	# root install, global paths
	export npm_config_globalconfig=/etc/npm/rootrc
else
	# user install
	export npm_config_globalconfig=/etc/npm/userrc
fi

# run it
exec node /usr/share/npm/cli.js "$@"
