#!/bin/sh

scp rnelson@ersch.wikimedia.org:/var/www/extensions/SwiftMedia/{SwiftMedia.body.php,SwiftMedia.i18n.php,SwiftMedia.php,TODO} .
scp rnelson@alsted.wikimedia.org:/etc/swift/proxy-server.conf proxy-server.sample
scp rnelson@alsted.wikimedia.org:/usr/local/lib/python2.6/dist-packages/wmf/{client.py,__init__.py,rewrite.py} wmf/

# strip out passwords to prevent funny stuff.
perl -pi -e "s/^super_admin_key = .*/super_admin_key = notreal/;s/^key = .*/key = alsonotreal/;" proxy-server.sample
