#!/bin/sh

if [ ! -d /usr/local/apache/common-local ];then
	if ! install -d -o mwdeploy -g mwdeploy /usr/local/apache/common-local; then
		echo "Unable to create common-local, please re-run this script as root."
		exit 1
	fi
fi

if [ ! -d /usr/local/apache/uncommon ];then
	if ! install -d -o mwdeploy -g mwdeploy /usr/local/apache/uncommon; then
		echo "Unable to create /usr/local/apache/uncommon, please re-run this script as root."
		exit 1
	fi
fi

sudo -u mwdeploy /usr/bin/scap-2

echo Done

