#!/usr/bin/python
# :vim:ft=python

import os
import sys

import numpy as np
import matplotlib.pyplot as pp

from argparse import ArgumentParser
from collections import defaultdict
from datetime import datetime
from matplotlib.font_manager import FontProperties
from dateutil.parser import parser as DateParser

__prog__ = os.path.basename(__file__)

parser = ArgumentParser(description=__doc__)
parser.add_argument('data_paths', metavar='data', nargs='+')
parser.add_argument('-o', '--output', dest='output_path', metavar='FILE')
parser.add_argument('-T', '--title')

date_parser = DateParser()
default_date = datetime(2001,1,1)

markers = 'ov^<>sp*+xD'
colors = 'bgrcmykw'
conv = defaultdict(lambda k : float)
conv[0] = lambda k : date_parser.parse(k, default=default_date)

if __name__ == '__main__':
    ns = parser.parse_args()

    # create figure
    fig = pp.figure(figsize=(10,4))
    ax1 = fig.add_axes(pp.axes([.1,.15,.65,.75], axisbg='ghostwhite'))
    ax2 = ax1.twinx()

    M = len(markers)
    C = len(colors)

    lines = []

    for i, path in enumerate(ns.data_paths):

        # load cohort data and filter out estimates based on samples with size
        # smaller than minimum requested
        arr = np.loadtxt(path, delimiter='\t', dtype=object, converters=conv, 
                skiprows=1)

        if len(arr) == 0:
            print >> sys.stderr, '%s: warning: skipping empty dataset: %s' % \
                    (__prog__, path)
            continue
 
        date = arr[:, 0]
        idx = np.argsort(date)
        arr = arr[idx]
        date = arr[:, 0]
        act, peak_date, peak_date_err, peak, peak_err = map(np.asfarray, 
                arr[:,1:].T)

        label = os.path.splitext(path)[0].replace('_',' ')

#        color = colors[i % C]
        marker = markers[i % M]
        l, (wu, wd), mc = ax1.errorbar(date, peak_date, peak_date_err / 2.0, 
                marker=marker, mec='red', label=label, ecolor='lightgrey', 
                ls='none', lw=2, mfc='none')
        lines.append(l)

        l, (wu, wd), mc = ax2.errorbar(date, peak, peak_err / 2.0, 
                marker=marker, mec='blue', label=label, ecolor='lightgrey', 
                ls='none', lw=2, mfc='none')

        lines.append(l)

    # decorate figure
    ax1.set_xlabel('cohorts')
    ax1.set_ylabel('peak day', color='red')
    ax2.set_ylabel('peak edits/day', color='blue')
    pp.figlegend(lines, [ l.get_label() for l in lines ], 
            loc='center right', prop=FontProperties(size='small'))
    pp.minorticks_on()
    pp.grid("on")
    pp.axis('tight')

    pp.draw()
    if ns.title is not None:
        pp.title(ns.title)
    pp.draw()

    # save to file, is output path specified
    if ns.output_path is not None:
        _, ext = os.path.splitext(ns.output_path)
        fmt = ext.strip('.') or 'pdf'
        pp.savefig(ns.output_path, fmt=ext)
        print '%s: output saved to %s' % (__prog__, ns.output_path)

    pp.show()

