<?php

$lang_register_form = array(
'registration_title' => '위키매니아 2008 등록',
'select' => '선택해 주세요',
'query' => '당신의 등록 현황을 조회합니다',
'query_title' => '당신은 이곳에서 위키매니아 2008의 등록 현황을 조회할 수 있습니다.',
'correction' => '당신의 정보는 약간의 양식 오류로 인하여 제출되지 못했습니다.',

'legend1' => '개인 정보',
'title1' =>
'        <p><strong>개인 식별 데이터</strong></p>
         <p>이 양식에 당신의 개인 데이터를 정확하게 기재해 주세요.</p>
',
'egy' => '이집트가 당신의 국적입니까?',
'egy1' => '그렇습니다. (다음 양식에 당신의 이름과 국가인증번호를 기재해 주세요.)',
'egy0' => '그렇지않습니다. (다음 양식에 여권에 나와 있는 당신의 이름과 여권 번호를 기재해 주세요.)',
'surname' => '성',
'given_name' => '이름',
'sex' => '성별',
'sex1' => '남성',
'sex2' => '여성',
'sex3' => '응답 거부',
'id' => 'ID / 여권 번호',
'country' => '국가 / 지역',
'city' => '주 / 도시',
'birthday' => '생년월일(dd/mmm/yyyy)',
'organization' => '기관',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, '1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월' ),
'day' => '',

'title2' =>
'        <p><strong>언어 구사 능력</strong></p>',
'langn' => '모국어',
'lang' => '언어 능력 수준',
'select_lang' => '언어를 선택해 주세요',
'select_level' => '언어 구사 능력을 선택해 주세요',

'lang_level1' => '1 (아주 조금)',
'lang_level2' => '2 (어느 정도 수준)',
'lang_level3' => '3 (유창한 수준)',
'lang_level4' => '4 (모국어에 준하는 수준)',

'lang1' => '언어 1',
'lang2' => '언어 2',
'lang3' => '언어 3',

'lang1_level' => '언어 1의 구사 능력',
'lang2_level' => '언어 2의 구사 능력',
'lang3_level' => '온어 3의 구사 능력',

'title3' =>
'        <p><strong>위키미디어 프로젝트와 이메일 계정</strong></p>
         <ul class="form_notice">
           <li>당신의 이메일 정보는 위키매니아 2008의 등록과 긴급 확인 용도로만 사용될 것입니다.</li>
         </ul>
',
'wiki_id' => '선호하는 위키미디어 프로젝트 계정 이름',
'email' => '당신의  이메일',


'legend2' => '참가',
'title4' =>
'        <p><strong>참가, 배지 정보 및 기타</strong></p>
         <p>숙박과 트랙 세션 및 관련 서비스에서 더 나은 배치를 위해 필요하오니 당신의 원하는 사항을 아래의 항목에서 선택해 주세요.</p>
',
'join_date' => '참가 일자',
'join1' => '7월 17일',
'join2' => '7월 18일',
'join3' => '7월 19일',
'topic' => '선호하는 세션 분야',
'topic1' => '위키미디어 커뮤니티',
'topic2' => '자유 콘텐츠',
'topic3' => '기술 기반',
'topic4' => '과학 분야',
'showname' => '배지 정보',
'custom_showname' => '배지에 표시되길 원하는 닉네임',
'showname1' => '이름',
'showname2' => '위키미디어 계정',
'showname3' => '기관',
'showname4' => '기타',
'size' => 'T-셔츠 사이즈',
'food' => '규정식',
'food0' => '-',
'food1' => '소고기 불가',
'food2' => '채식 (아시아 스타일)',
'food3' => '채식 (서구 스타일, 달걀과 우유는 괜찮음)',
'food4' => '코샤르',
'food5' => '기타',
'food_other' => '특별한 규정식',
'allegric' => '엘러지 있음',
'transportation_assistance' => '항공권 지원 요청',
'need_transportation_assistance' => '예, 제 항공권 예약에 지원이 필요합니다.',
'visa_assistance' => '비자 요청',
'need_visa_assistance' => '예, 비자 발급이 필요합니다',
'visa_assistance_description' => ' 비자 발급을 위해 어떤 기관이 어떻게 도와주어야 하는 기재해 주세요. (<strong>아랍어</strong> 또는 <strong>영어</strong>로)',

'title5' =>
'         <p><strong>숙박</strong></p>
         <p>숙박과 관련하여 2개의 옵션이 있습니다. 당신은 더블 룸의 2개의 시내 호텔 중 하나를 선택하거나 성마르크 대학의 기숙사를 선택하여 숙박할 수 있습니다.
    등록하시기 전에, 정확한 위치와 선택가능한 사양을 <a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>위키매니아 공식 사이트</a>에서 상세 내용을 확인하세요.></p>
',
'accommodation_hotel' => '선호하는 호텔',
'hotels_metropol' => '메트로폴 호텔(1박에 $60)',
'hotels_delta' => '델타 호텔(1박에 $30)',
'hotels_dorms' => '성 마르크 기숙사(1박에 $10)',

'accommodation' => '체류 일자',
'night1' => '7월 16일',
'night2' => '7월 17일',
'night3' => '7월 18일',
'night4' => '7월 19일',
'night5' => '7월 20일',
'room' => '공동 숙박 가능 여부',
'room2' => '2인실',
'room4' => '4인실',
'room6' => '상관 없음',

'title6' =>
'         <p><strong>지불</strong></p>
         <p>당신은 당신의 Paypal 계좌에서 출금하거나 <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">103개 국가/지역</a>(이집트는 포함되지 않음)에서 PayPal을 통해 당신의 신용카드를 사용하거나 또는 알렉산드리아에 있는 조직위 소유의 은행 계좌에 송금과 직접 지불을 통해 지불할 수도 있습니다. 주의: 당신이 이집트인이면 PayPal 옵션은 사용 불가합니다.</p>
',

'pay_method' => '지불 수단',
'atm' => '은행 계좌 지불',
'receipt' => '영수증',
'need_receipt' => '예, 종이로 된 영수증이 필요합니다.',
'receipt_title' => '제목',
'receipt_address' => '메일 주소',

'submit_notice' =>
'<li><strong>양식을 제출하고서, 당신은 아직 당신의 등록을 확인할 기회가 한 번 있습니다.</strong></li>',
'submit' => '제출',
'reset' => '다시 작성',

'confirm' => '확인',
'confirm_description' => '양식을 제출하기 전에, 당신의 정보를 정확하게 채웠는 지 확인하세요:',

'paypal' => 'PayPal을 통한 지불',
'paypal_description' =>
'<p>PayPal을 통해 지불하시려면 아래의 "바로 구매" 버튼을 사용하세요</p> ',
'paypal_failed' => 'PayPal 지불의 취소',
'paypal_failed_description' => '<p>당신은 다시 아래의 양식을 채우거나 아래에 설명된 다른 방법으로 지불할 수 있습니다.</p>',
'paypal_successful' => 'PayPal을 통한 지불, 성공',
'paypal_successful_description' => '<p>감사합니다! 당신의 납부를 받고, 등록 정보을 검토한 후에 그 결과를 통지하겠습니다.</p>',
'atm' => '은행 계좌를 통한 지불',
'atm_description' => '
<p>당신의 등록비와 숙박비를 이체하기 위하여 아래의 이집트 은행을 이용하세요:</p>
<ul class="atm-account">
<li>계좌명: Bibliotheca Alexandrina</li>
<li>은행: Commercial International Bank</li>
<li>지점 코드: Bibliotheca Alexandrina Branch</li>
<li>SWIFT BIC 코드: CIBEEGCX041</li>
<li>위키매니아 계좌 번호 (USD): 41-8930006-6</li>
</ul>
<p>이집트에서 paypal은 제한되기 때문에, 당신은 은행에 직접 납부할 수 있습니다. 다음 EGP 계좌 번호와 함께 은행을 이용하세요:</p>
<ul class="atm-account">
<li>위키매니아 계좌 번호 (EGP): 41-8900019-5</li>
</ul>
<p>그리고 wikimedia.org의 regwikimania2008에 전자 양식으로 위에 보여지는 등록 번호와 당신의 이름을 채워서 납부 영수증을 보내세요. 그러면 3 근무일 이내에 회신하겠습니다. 당신은 또한 <a href="index.php?action=query" title="query the registration status">온라인 상으로 등록 현황을 조회</a>할 수 있습니다.</p>
'
);

$lang_messages = array(
'successful' => '등록 완료',
'successful_description' =>
'<p>위키매니아 2008에 함께 하여 주셔서 감사합니다! 당신의 등록 양식은 제출되었습니다. 등록을 확인하려면 납부 과정을 완료할 필요가 있음을 유의하세요.
당신의 <strong>등록 번호</strong>는 아래 표시됩니다. 나중에 당신의 신원을 확인하거나 등록 현황을 조회하기 위하여 필요하오니 등록 번호를 적어 두세요',
'cost' => '등록비',
'wikimania_cost' => '회의: ',
'accommodation_cost' => '숙박: ',
'other_cost' => '기타 지불: ',
'total_cost' => '합계: ',
'usd' => ' USD',
'egp' => ' EGP',
);

$lang_errors = array(
'repeat' => '누군가 같은 이름과 증명서/여권 번호로 등록하였습니다. 당신이 두 번 등록하였거나 등록 페이지를 새로 고침했을 가능성이 있습니다.',
'not_input' => '$1이 채워지지 않았습니다.',
'not_input_completely' => '$1이 완료되지 않았습니다.',
'not_select' => '$1이 체크되지 않았습니다.',
'not_select_whether' => '$1이 기재되지 않았습니다.',
'too_long' => '$1이 너무 깁니다. $2 길이로 제한되어 있습니다.',
'incorect' => '$1이 정확하지 않습니다.',
'wrong' => '$1이 잘못되었습니다.',
'visa_assistance_incomplete' => '비자 요청 정보가 채워지지 않았습니다.',
'wrong_query' => '이름 또는 등록 번호가 잘못되었습니다.',
'paypal_unavailable' => '당신의 선택한 국가/지역은 PayPay에서 지원하지 않습니다.'
);

$lang_query = array(
'unique_code' => '등록 번호',
'submit' => '조회',
'your_status' => '안녕하세요 $1, 이것은 당신의 등록 현황입니다:',
'received_money' => '등록비 무료 (접수 / 예정):',
'lack' => '아직 미접수',
'enough' => '이미 납부했습니다',
'too_much' => '너무 많이 납부했습니다',
'accepted' => '당신의 등록이 <strong>확인</strong>되었습니다.',
'rejected' => '당신의 등록이 <strong>거부</strong>되었습니다.',
'not_yet' => '당신의 등록은 <strong>확인되지 않았습니다</strong>.'

);


$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

?>
