<?php

$lang_register_form = array(
'registration_title' => 'Wikimania 2008: Rejestracja',
'select' => 'Wybierz',
'query' => 'Sprawdź stan swojej rejestracji',
'query_title' => 'Tu możesz sprawdzić stan swojej rejestracji uczestnictwa w Wikimanii 2008.',
'correction' => 'Twoje informacje nie zostały wysłane ze względu na błąd w formularzu.',

'legend1' => 'Dane osobowe',
'title1' =>
'        <p><strong>Dane identyfikacyjne</strong></p>
         <p>Proszę poprawnie wprowadzić swoje dane w formularzu.</p>
',
'egy' => 'Czy jesteś obywatelem Arabskiej Republiki Egiptu?',
'egy1' => 'Tak. (W poniższych polach podaj swój narodowy numer identyfikacyjny oraz nazwisko)',
'egy0' => 'Nie. (W poniższych polach podaj numer paszportu i nazwisko)',
'surname' => 'Nazwisko',
'given_name' => 'Imię',
'sex' => 'Płeć',
'sex1' => 'Mężczyzna',
'sex2' => 'Kobieta',
'sex3' => 'Odmawiam podania',
'id' => 'Numer paszportu',
'country' => 'Kraj / Region',
'city' => 'Stan / miasto',
'birthday' => 'Data urodzenie (dd/mmm/rrrr)',
'organization' => 'Organizacja',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień' ),
'day' => '',

'title2' =>
'        <p><strong>Znajomość języków</strong></p>',
'langn' => 'Język ojczysty',
'lang' => 'Poziom znajomości języka',
'select_lang' => 'Wybierz język',
'select_level' => 'Wybierz poziom znajomości języka',

'lang_level1' => '1 (Początkujący)',
'lang_level2' => '2 (Średnio zaawansowany)',
'lang_level3' => '3 (Zaawansowany)',
'lang_level4' => '4 (Zbliżony do ojczystego)',

'lang1' => 'Język 1',
'lang2' => 'Język 2',
'lang3' => 'Język 3',

'lang1_level' => 'Poziom znajomości języka 1',
'lang2_level' => 'Poziom znajomości języka 2',
'lang3_level' => 'Poziom znajomości języka 3',

'title3' =>
'        <p><strong>Projekty Wikimedia i konto/konta e-mail</strong></p>
         <ul class="form_notice">
           <li>Informacja o twoim koncie będzie wykorzystana wyłącznie do celów rejestracji i pilnych powiadomień o Wikimanii 2008.</li>
         </ul>
',
'wiki_id' => 'Nazwa głównego projektu Wikimedia',
'email' => 'Twój e-mail',


'legend2' => 'Uczestnictwo',
'title4' =>
'        <p><strong>Uczestnictwo, identyfikator i pozostałe</strong></p>
         <p>W celu zapewnienia lepszego zakwaterowania, sesji i innych usług prosimy o podanie preferencji w poniższych polach.</p>
',
'join_date' => 'Uczestnictwo w dniach',
'join1' => '17 lipca',
'join2' => '18 lipca',
'join3' => '19 lipca',
'topic' => 'Preferowany zestaw sesji',
'topic1' => 'Społeczności Wikimedia',
'topic2' => 'Wolne treści',
'topic3' => 'Infrastruktura techniczna',
'topic4' => 'Ścieżka naukowa',
'showname' => 'Identyfikator',
'custom_showname' => 'Preferowana nazwa na identyfikatorze',
'showname1' => 'Nazwisko',
'showname2' => 'Konto Wikimedia',
'showname3' => 'Organizacja',
'showname4' => 'Inne',
'size' => 'Rozmiar T-shirtu',
'food' => 'Ograniczenia diety',
'food0' => '-',
'food1' => 'Bez wołowiny',
'food2' => 'Wegetariańska (styl azjatycki)',
'food3' => 'Wegetariańska (styl zachodni: może zawierać mleko i jajka)',
'food4' => 'Koszerna',
'food5' => 'Inna',
'food_other' => 'Określone ograniczenia dietetyczne',
'allegric' => 'Alergie',
'transportation_assistance' => 'Pomoc w zorganizowaniu biletów lotniczych',
'need_transportation_assistance' => 'Tak, potrzebuję pomocy w dziedzinie rezerwacji lotniczej',
'visa_assistance' => 'Pomoc w uzyskaniu wizy',
'need_visa_assistance' => 'Tak, potrzebuję pomocy',
'visa_assistance_description' => 'Proszę podać jak organizatorzy mogą pomóc w uzyskaniu wizy. (po <strong>arabsku</strong> lub <strong>angielsku</strong>)',

'title5' =>
'         <p><strong>Zakwaterowanie</strong></p>
         <p>Udostępniliśmy 2 opcje zakwaterowania. Możesz wybrać pomiędzy 2 hotelami w centrum z pokojami dwuosobowymi lub zamieszkać w akademikach Saint-Marc College.
    Sprawdź szczegóły lokalizacji na <a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>oficjalnej stronie Wikimanii</a> przed zarejestrowniem.</p>
',
'accommodation_hotel' => 'Preferowany hotel.',
'hotels_metropol' => 'Hotel Metropol ($60 za noc)',
'hotels_delta' => 'Hotel Delta ($30 za noc)',
'hotels_dorms' => 'Akademiki Saint Marc($10 za noc)',

'accommodation' => 'Noclegi',
'night1' => '16 lipca',
'night2' => '17 lipca',
'night3' => '18 lipca',
'night4' => '19 lipca',
'night5' => '20 lipca',
'room' => 'Preferowany pokój',
'room2' => '2-osobowy',
'room4' => '4-osobowy',
'room6' => 'Bez znaczenia',

'title6' =>
'         <p><strong>Płatność</strong></p>
         <p>Możesz skorzystać ze swojego konta PayPal lub zapłacić kartą kredytową poprzez PayPal w <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">103 krajach / regionach</a> (Egipt jest z tej usługi wyłączony) lub przelewem na konto bankowe organizatorów w Aleksandrii. Uwaga: płatność przez PayPal jest niedostępna jeśli jesteś Egipcjaninem.</p>
',

'pay_method' => 'Rodzaj płatności',
'atm' => 'Przelew z konta bankowego',
'receipt' => 'Rachunek',
'need_receipt' => 'Tak, poproszę o rachunek',
'receipt_title' => 'Tytuł',
'receipt_address' => 'Adres do korespondencji',

'submit_notice' =>
'<li><strong>Po wysłaniu formularza nadal dostępna jest możliwość weryfikacji zgłoszenia.</strong></li>',
'submit' => 'Wyślij',
'reset' => 'Wyczyść',

'confirm' => 'Weryfikacja',
'confirm_description' => 'Przed wysłaniem formularza prosimy o sprawdzenie, czy wszystkie dane są poprawne:',

'paypal' => 'Płatność przez PayPal',
'paypal_description' =>
'<p>Użyj przycisku "Kup teraz" by zapłacić przez PayPal</p> ',
'paypal_failed' => 'Anuluj płatność przez PayPal',
'paypal_failed_description' => '<p>Możesz spróbować ponownie, wypełniając poniższy formularz lub wybrać inną formę płatności opisaną poniżej.</p>',
'paypal_successful' => 'Płatność przez PayPal powiodła się',
'paypal_successful_description' => '<p>Dziękujemy! Powiadomimy Cię o wyniku po otrzymaniu płatności i przejrzeniu danych podanych w trakcie rejestracji.</p>',
'atm' => 'Płatność z konta bankowego',
'atm_description' => '
<p>Konto w banku w Egipcie, na które możesz przelać opłatę za rejestrację i/lub zakwaterowanie:</p>
<ul class="atm-account">
<li>Właściciel: Bibliotheca Alexandrina</li>
<li>Bank: Commercial International Bank</li>
<li>Kod oddziału: Bibliotheca Alexandrina Branch</li>
<li>Kod SWIFT BIC: CIBEEGCX041</li>
<li>Numer konta Wikimanii (USD): 41-8930006-6</li>
</ul>
<p>W związku z ograniczeniami płatności przez PayPal w <b>Egipcie</b> możesz dokonać płatności bezpośrednio w banku, korzystając z podanych powyżej danych, na poniższe konto w EGP:</p>
<ul class="atm-account">
<li>Numer konta Wikimanii (EGP): 41-8900019-5</li>
</ul>
<p>Prosimy o przesłanie kopii przelewu w formie elektronicznej z podaniem nazwiska i numeru rejestracji (podanego powyżej pod adres regwikimania2008 AT wikimedia.org; odpowiemy w ciągu 3 dni roboczych. Możesz również <a href="index.php?action=query" title="query the registration status">sprawdzić stan rejestracji online</a>.</p>
'
);

$lang_messages = array(
'successful' => 'Rejestracja zakończona',
'successful_description' =>
'<p>Dziękujemy za zgłoszenie udziału w konferencji Wikimania 2008! Twój formularz rejestracyjny został wysłany. Aby rejestracja została potwierdzona musisz dokonać płatności.

Poniżej znajduje się Twój <strong>numer rejestracji</strong>. Zanotuj go, gdyż jest on używany do sprawdzania stanu rejestracji i potwierdzenia Twojej tożsamości.
',
'cost' => 'Opłata rejestracyjna',
'wikimania_cost' => 'Konferencja: ',
'accommodation_cost' => 'Zakwaterowanie: ',
'other_cost' => 'Inne opłaty: ',
'total_cost' => 'Razem: ',
'usd' => ' USD',
'egp' => ' EGP',
);

$lang_errors = array(
'repeat' => 'Ktoś zarejestrował się pod takim samym nazwiskiem i numerem identyfikacyjnym/paszportu. Możliwe, że wysłałeś formularz dwukrotnie lub odświeżyłeś stronę rejestracji.',
'not_input' => 'Pole $1 jest puste.',
'not_input_completely' => 'Pole $1 jest niekompletne.',
'not_select' => 'Pole $1 jest niezaznaczone',
'not_select_whether' => 'Dane w polu $1 nie zostały określone.',
'too_long' => '$1 jest zbyt długie, maksymalna długość danych to $2 znaków.',
'incorect' => '$1 jest niepoprawne.',
'wrong' => '$1 jest błędne.',
'visa_assistance_incomplete' => 'Informacja o pomocy w uzyskaniu wizy nie została podana.',
'wrong_query' => 'Zła nazwa lub zły numer rejestracji.',
'paypal_unavailable' => 'Twój kraj / region nie jest obsługiwany przez PayPal.'
);

$lang_query = array(
'unique_code' => 'Numer rejestracji',
'submit' => 'Szukaj',
'your_status' => 'Witaj, $1, oto stan Twojej rejestracji:',
'received_money' => 'Opłata rejestracyjna (otrzymano / oczekiwanie):',
'lack' => 'Nie otrzymano',
'enough' => 'Zapłacono',
'too_much' => 'Zapłaciłeś zbyt dużo',
'accepted' => 'Twoja rejestracja została <strong>potwierdzona</strong>.',
'rejected' => 'Twoja rejestracja została <strong>odrzucona</strong>.',
'not_yet' => 'Twoja rejestracja <strong>nie została potwierdzona</strong>.'

);

$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

?>
