<?php

$lang_register_form = array(
'registration_title' => '2008国际维基媒体年会报名',
'select' => '请选择',
'query' => '查询注册申请情况',
'query_title' => '你可以在此查询注册申请情况。',
'correction' => '你的报名表格里可能出现错误，你的资料未被传送',

'legend1' => '个人资料',
'title1' =>
'        <p><strong>个人身份资料</strong></p>
         <p>请确保填上正确的个人资料</p>
',
'egy' => '你是否埃及阿拉伯共和国的公民？',
'egy1' => '是(请在以下栏位填上你的国民身分号码和姓名。)',
'egy0' => '否(请在以下栏位填上你的护照号码和姓名。)',
'surname' => '姓氏',
'given_name' => '名',
'sex' => '性别', 
'sex1' => '男',
'sex2' => '女',
'sex3' => '不愿申明',
'id' => '身份证明文件 / 护照号码', 
'country' => '国家 / 地区', 
'city' => '州/ 省 / 城市', 
'birthday' => '出生日期(dd/mm/yyyy)',
'organization' => '所属组织',
'year1' => '', 
'year' => '', 
'month' => '', 
'months' => array(NULL, '一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'),
'day' => '', 

'title2' =>
'        <p><strong>语言</strong></p>',
'langn' => '母语', 
'lang' => '熟练程度', 
'select_lang' => '选择语言',
'select_level' => '选择熟练程度',

'lang_level1' => '1 (基本)',
'lang_level2' => '2 (中等)',
'lang_level3' => '3 (高阶)',
'lang_level4' => '4 (接近母语)',

'lang1' => '第一语言',
'lang2' => '第二语言',
'lang3' => '第三语言',

'lang1_level' => '第一语言的熟练程度',
'lang2_level' => '第二语言的熟练程度',
'lang3_level' => '第三语言的熟练程度',

'title3' => 
'        <p><strong>参与的维基计划和电邮帐戶</strong></p>
         <ul class="form_notice">
           <li>年会筹备小组将只会在注册相关程序和紧急通知时使用你的电邮地址资讯。</li>
         </ul>
', 
'wiki_id' => '意欲使用的维基计划帐戶名称。', 
'email' => '电邮地址', 


'legend2' => '参与情况',
'title4' =>
'        <p><strong>参与情况丶名牌资料和其他</strong></p>
         <p>为了更好安排住宿丶议程跟进和相关方面的服务，我们希望你告诉我们下列的资料。</p>
',
'join_date' => '报名参与的日子',
'join1' => '7月17日',
'join2' => '7月18日',
'join3' => '7月19日',
'topic' => '感兴趣的议程类型', 
'topic1' => '维基媒体社群',
'topic2' => '自由资讯',
'topic3' => '技术架构',
'topic4' => '科学相关主题',
'showname' => '名牌资料',
'custom_showname' => '想用在名牌上的名字',
'showname1' => '姓名',
'showname2' => '维基媒体计划中的帐戶名',
'showname3' => '所属组织',
'showname4' => '其他',
'size' => 'T恤的尺寸', 
'food' => '饮食习惯',
'food0' => '-',
'food1' => '不吃牛肉',
'food2' => '亚洲式素食者',
'food3' => '西式素食者(可吃蛋和牛奶)',
'food4' => '犹太饮食',
'food5' => '其他',
'food_other' => '请注明特别的饮食习惯',
'allegric' => '任何食物敏感', 
'transportation_assistance' => '机票协助',
'need_transportation_assistance' => '我需要筹备小组为我预定机票。',
'visa_assistance' => '签证协助', 
'need_visa_assistance' => '我需要签证协助',
'visa_assistance_description' => '请说明筹备小组可以提供什么协助(请使用<strong>阿拉伯语</strong>或<strong>英语</strong>填写)',

'title5' =>
'         <p><strong>住宿</strong></p>
         <p>我们提供两种选择。你可以选择入住酒店，或入住圣马可书院(Collège Saint Marc)的宿舍。
    请查阅<a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>该页面上的资讯</a>，取得住宿地点的实际位置和其附属设施的资料，以便报名时申明你的决定。</p>
',
'accommodation_hotel' => '希望入住酒店',
'hotels_metropol'=> '大都会酒店(Metropole Hotel，每晚60美元)',
'hotels_delta'=> '三角洲酒店 (Delta Hotel，每晚30美元)',
'hotels_dorms' => '圣马可书院宿舍 (每晚10美元)',

'accommodation' => '入住日期', 
'night1' => '7月16日',
'night2' => '7月17日',
'night3' => '7月18日',
'night4' => '7月19日',
'night5' => '7月20日',
'room' => '偏好的房间类别',  
'room2' => '二人房',
'room4' => '四人房',
'room6' => '没有所谓',

'title6' =>
'         <p><strong>付款</strong></p>
         <p>若你居住在<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">这里所列出的103个国家/地区</a> (埃及除外)，你可以通过PayPal，以借帐或信用卡付款。你也可以选择汇款或将款项直接存入亚力山卓筹备小组的银行户口。请注意：来自埃及的申请人将不能使用PayPal付款。</p>
',

'pay_method' => '付款方法', 
'atm' => '银行户口付款',
'receipt' => '收据',
'need_receipt' => '我需要收据。',  
'receipt_title' => '称谓', 
'receipt_address' => '邮寄地址', 

'submit_notice' =>
'<li><strong>递交了这份表格後，你需要再一次确认你的申请。</strong></li>',
'submit' => '递交',
'reset' => '重置',

'confirm' => '确认',
'confirm_description' => '递交这份表格前，请确认你已经正确填写各项资料。',

'paypal' => '以PayPal付款',
'paypal_description' =>
'<p>请按"Buy Now"按钮使用PayPal付款</p> ',
'paypal_failed' => '取消PayPal付款',
'paypal_failed_description' => '<p>你可以重新填写以下表格，或以下面所属的其他途径付款。</p>',
'paypal_successful' => 'PayPal付费成功！',
'paypal_successful_description' => '<p>多谢！我们收到付款和审阅登记资料後将会通知你。</p>',
'atm' => '通过银行帐号付款',
'atm_description' => '
<p>收取住宿及参加费的银行帐号资料如下：</p>
<ul class="atm-account">
<li>户口名称: Bibliotheca Alexandrina</li>
<li>银行名称: Commercial International Bank</li>
<li>分行: Bibliotheca Alexandrina Branch</li>
<li>SWIFT BIC编码: CIBEEGCX041</li>
<li>帐号(美元): 41-8930006-6</li>
</ul>
<p>由于PayPal在埃及的限制，你只可以通过银行直接付款，资料和上面一样，但请使用以下的埃及镑帐号：</p>
<ul class="atm-account">
<li>帐号(埃及镑): 41-8900019-5</li>
</ul>
<p>请随後把付费证明，连同你的姓名及上述的注册编号以电子邮件寄到regwikimania2008 AT wikimedia.org，
我们会在3个工作天内回覆。你也可在<a href="index.php?action=query" title="query the registration status">这里</a>查询登记状况。</p>
'
);

$lang_messages = array(
'successful' => '完成报名',
'successful_description' => 
'<p>多谢阁下报名参加2008国际维基媒体年会！你的报名表格己经成功递交。请注意你必须完成缴费步骤，才能确认参与资格。 

你的<strong>注册编号</strong>已显示在下面。请记下有关编号，以便日後查询报名受理状况及确认身份。 
',
'cost' => '报名费用',
'wikimania_cost' => '会议：',
'accommodation_cost' => '住宿：',
'other_cost' => '其他支出：',
'total_cost' => '总支出',
'usd' => '美元(USD)',
'egp' => '埃及镑(EGP)',
);

$lang_errors = array(
'repeat' => '有人使用了一样的姓名及身份证 / 护照编号。也有可能是因为你重复提交了申请，或者你重刷了报名表格页面',
'not_input' => '你留空了$1。',
'not_input_completely' => '你未完成$1。',
'not_select' => '你未选择$1。',
'not_select_whether' => '你未选择$1。',
'too_long' => '$1中的内容过长了，最长只能容纳$2个位元组',
'incorect' => '你未能正确填写$1。',
'wrong' => '你错误填写了$1',
'visa_assistance_incomplete' => '你留空了签证协助的资料。',
'wrong_query' => '错误的名称或申请编号',
'paypal_unavailable' => '你所在的国家并不支援PayPal。'
);

$lang_query = array(
'unique_code' => '注册编号',
'submit' => '查询',
'your_status' => '你好，$1！以下是你的注册资料：',
'received_money' => '注册费用 (收到费用 / 应付费用):',
'lack' => '未支付费用',
'enough' => '己经支付费用',
'too_much' => '你支付了过多费用',
'accepted' => '你的申请已被<strong>确认</strong>。',
'rejected' => '你的申请已被<strong>拒绝</strong>。',
'not_yet' => '你的申请<strong>仍在处理中</strong>。'

);

$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

?>
