<?php

$lang_register_form = array(
'registration_title' => 'Inscrição para a Wikimania 2008',
'select' => 'Escolha uma opção',
'query' => 'Confira o estado de sua inscrição',
'query_title' => 'Pode conferir o estado de sua inscrição para o Wikimania 2008 aqui.',
'correction' => 'A informação não foi enviada devido a um erro no formulário.',

'legend1' => 'Informação pessoal',
'title1' =>
'        <p><strong>Dados de identificação pessoal</strong></p>
         <p>Por favor complete corretamente suas informações pessoais.</p>
',
'egy' => 'Você é cidadão da República Árabe do Egito?',
'egy1' => 'Sim. (Por favor escreva seu número de identificação nacional e seu nome nos seguintes campos)',
'egy0' => 'Não. (Por favor escreva seu número de passaporte e seu nome tal como figura no passaporte nos seguintes campos)',
'surname' => 'Sobrenome',
'given_name' => 'Nome',
'sex' => 'Gênero',
'sex1' => 'Masculino',
'sex2' => 'Feminino',
'sex3' => 'Não declara',
'id' => 'Número de identificação / Número de Passaporte',
'country' => 'País / Região',
'city' => 'Estado / Cidade',
'birthday' => 'Data de Nascimento (dd/mm/aaaa)',
'organization' => 'Organização',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro' ),
'day' => '',

'title2' =>
'        <p><strong>Habilidades lingüísticas</strong></p>',
'langn' => 'Língua nativa',
'lang' => 'Nível',
'select_lang' => 'Escolhe uma língua',
'select_level' => 'Escolhe o nível',

'lang_level1' => '1 (Básico)',
'lang_level2' => '2 (Intermédio)',
'lang_level3' => '3 (Avançado)',
'lang_level4' => '4 (Quase nativo)',

'lang1' => 'Língua 1',
'lang2' => 'Língua 2',
'lang3' => 'Língua 3',

'lang1_level' => 'Nível da língua 1',
'lang2_level' => 'Nível da língua 2',
'lang3_level' => 'Nível da língua 3',

'title3' =>
'        <p><strong>Projeto da Wikimedia e direções de correio eletrônico</strong></p>
         <ul class="form_notice">
           <li>Teu correio eletrônico só será utilizado para a inscrição e para notificações urgentes sobre a Wikimania 2008.</li>
         </ul>
',
'wiki_id' => 'Nome da conta de seu projeto da Wikimedia preferido',
'email' => 'Teu correio eletrônico',


'legend2' => 'Participação',
'title4' =>
'        <p><strong>Participação, informação para sua credencial e outros dados</strong></p>
         <p>Para facilitar arranjos no alojamento, as sessões das diferentes áreas e serviços relacionados, por favor indica-nos tuas opções nos seguintes campos.</p>
',
'join_date' => 'Data de participação',
'join1' => '17 de julho',
'join2' => '18 de julho',
'join3' => '19 de julho',
'topic' => 'Área preferida',
'topic1' => 'Comunidades Wikimedia',
'topic2' => 'Conteúdo livre',
'topic3' => 'Infra-estrutura técnica',
'topic4' => 'Área científica',
'showname' => 'Informação para a credencial',
'custom_showname' => 'Apelido para a credencial',
'showname1' => 'Nome',
'showname2' => 'Conta de Wikimedia',
'showname3' => 'Organização',
'showname4' => 'Outro',
'size' => 'Número da camiseta',
'food' => 'Restrições na dieta',
'food0' => '-',
'food1' => 'Não como carne',
'food2' => 'Vegetariano (estilo asiático)',
'food3' => 'Vegeteriano (estilo ocidental, ovos e leite estão permitidos)',
'food4' => 'Kosher',
'food5' => 'Outras',
'food_other' => 'Restrições especificadas na dieta',
'allegric' => 'Alguma alergia',
'transportation_assistance' => 'Auxílio com passagens de vôos',
'need_transportation_assistance' => 'Sim, eu necessito de seu auxílio com minha reserva de vôo',
'visa_assistance' => 'Ajuda para obter a visa',
'need_visa_assistance' => 'Sim, preciso ajuda para obter a visa',
'visa_assistance_description' => 'Por favor indica-nos como pode ajudar-te a equipe de organizadores a obter a visa. (em <strong>Árabe</strong> ou <strong>Inglês</strong>)',

'title5' =>
'         <p><strong>Alojamento</strong></p>
         <p>Temos 2 opções disponíveis para o alojamento. Podes eleger entre 1 de 2 hotéis no centro da cidade, em habitação dupla, ou podes ficar-te nos dormitórios do Saint-Marc College.
    Por favor confira os detalhes no <a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>site oficial de Wikimania</a> para conhecer a localização e especificações exatas de cada opção antes de registrar-se.</p>
',
'accommodation_hotel' => 'Hotel preferido.',
'hotels_metropol' => 'Hotel Metropol ($60 por noite)',
'hotels_delta' => 'Hotel Delta ($30 por noite)',
'hotels_dorms' => 'Dormitórios en Saint Marc ($10 por noite)',

'accommodation' => 'Datas de permanência',
'night1' => '16 de julho',
'night2' => '17 de julho',
'night3' => '18 de julho',
'night4' => '19 de julho',
'night5' => '20 de julho',
'room' => 'Preferência de habitação',
'room2' => 'Duplo',
'room4' => 'Quádruplo',
'room6' => 'Qualquer',

'title6' =>
'         <p><strong>Pagamento</strong></p>
         <p>Podes utilizar tua conta Paypal ou pagar utilizando teu cartão de crédito através de PayPal em <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">103 países / regiões</a> (Não inclui Egito) ou por transferência e pagamento direto à conta bancária do equipe organizador em Alexandria. Nota: a opção de PayPal será descartada se você é egípcio</p>
',

'pay_method' => 'Tipo de Pagamento',
'atm' => 'Pago através de conta bancária',
'receipt' => 'Recibo',
'need_receipt' => 'Sim, preciso recibo impresso.',
'receipt_title' => 'Título',
'receipt_address' => 'Direção postal',

'submit_notice' =>
'<li><strong>Depois de enviar o formulário, terás a possibilidade de verificar sua inscrição.</strong></li>',
'submit' => 'Enviar',
'reset' => 'Limpar',

'confirm' => 'Verificação',
'confirm_description' => 'Antes de aceitar o formulário, por favor, assegura-te de ter completado corretamente a informação:',

'paypal' => 'Pagamento através de PayPal',
'paypal_description' =>
'<p>Por favor, utiliza o botão "Buy now" que aparece embaixo para pagar através de PayPal</p> ',
'paypal_failed' => 'Cancelar o pagamento através de PayPal',
'paypal_failed_description' => '<p>Podes tentar novamente enchendo o formalrio que se encontra embaixo ou podes pagar mediante as outras formas explicadas mais abaixo.</p>',
'paypal_successful' => 'Pagamento através de PayPal bem-sucedido',
'paypal_successful_description' => '<p>¡Obrigado! Notificaremos o resultado depois de receber o pagamento e de revisar a informação de tua inscrição.</p>',
'atm' => 'Pagamento através de conta bancária',
'atm_description' => '
<p>Por favor utilize a seguinte informação bancária em Egito para transferir seu pagamento de inscrição e/ou estadía:</p>
<ul class="atm-account">
<li>Nome da conta bancária: Bibliotheca Alexandrina</li>
<li>Banco: Commercial International Bank</li>
<li>Código de sucursal: Bibliotheca Alexandrina Branch</li>
<li>Código SWIFT BIC: CIBEEGCX041</li>
<li>Número de conta de Wikimania (USD): 41-8930006-6</li>
</ul>
<p>Devido à restrição de Paypal em <b>Egito</b>, podes pagar diretamente no banco, por favor utiliza os dados acima mencionados com o seguinte número de conta em EGP:</p>
<ul class="atm-account">
<li>Número de conta de Wikimania (EGP): 41-8900019-5</li>
</ul>
<p>Por favor envia o recibo de tua transferência em formato eletrônico com teu nome e o número de inscrição a regwikimania2008 AT wikimedia.org, te responderemos dentro dos três dias hábeis. Também podes <a href="index.php?action=query" title="Conferir o estado de tua inscrição">conferir o estado de tua inscrição online</a>.</p>
'
);

$lang_messages = array(
'successful' => 'Inscrição completa',
'successful_description' =>
'<p>Obrigado por unir-se ao Wikimania 2008! Seu formulário de inscrição foi aceito. Por favor, tem em conta que precisas completar o processo de pagamento para que a inscrição possa ser confirmada.

Teu <strong>número de inscrição</strong> será mostrado abaixo. Por favor, anote esse número já que será utilizado para conferir o estado de sua inscrição e para confirmar sua identidade no futuro.
',
'cost' => 'Quota de inscrição',
'wikimania_cost' => 'Conferência: ',
'accommodation_cost' => 'Alojamento: ',
'other_cost' => 'Outros custos: ',
'total_cost' => 'Total: ',
'usd' => ' USD',
'egp' => ' EGP',
);

$lang_errors = array(
'repeat' => 'Já existe alguém registrado com este nome e número de identificação / passaporte. É possível que te tenhas registrado duas vezes ou que tenhas recarregado a página de inscrição.',
'not_input' => '$1 está vazio.',
'not_input_completely' => '$1 está incompleto.',
'not_select' => '$1 não foi escolhido.',
'not_select_whether' => '$1 não foi especificado.',
'too_long' => '$1 é muito longo, a longitude máxima é $2.',
'incorect' => '$1 é incorreto.',
'wrong' => '$1 é errôneo.',
'visa_assistance_incomplete' => 'A informação de assistência para a visa está vazia.',
'wrong_query' => 'Nome ou número de inscrição incorreto.',
'paypal_unavailable' => 'PaypPal não funciona no país / região selecionada.'
);

$lang_query = array(
'unique_code' => 'Número de inscrição',
'submit' => 'Conferir',
'your_status' => 'Olá, $1, aqui tem o estado de sua inscrição:',
'received_money' => 'Quota de inscrição (recebida / esperada):',
'lack' => 'Não recebida',
'enough' => 'Paga',
'too_much' => 'Pagaste por demais',
'accepted' => 'Sua inscrição está <strong>confirmada</strong>.',
'rejected' => 'Sua inscrição foi <strong>rejeitada</strong>.',
'not_yet' => 'Sua inscrição <strong>não foi confirmada</strong>.'

);


$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

?>
