<?php

$lang_register_form = array(
'registration_title' => '2008國際維基媒體年會報名',
'select' => '請選擇',
'query' => '查詢註冊申請狀況',
'query_title' => '你可以在此查詢註冊申請狀況。',
'correction' => '你的報名表格裡可能出現錯誤，你的資料未被傳送',

'legend1' => '個人資料',
'title1' =>
'        <p><strong>個人身份資料</strong></p>
         <p>請確保填上正確的個人資料</p>
',
'egy' => '你是否埃及阿拉伯共和國的公民？',
'egy1' => '是(請在以下欄位填上你的國民身份號碼和姓名。)',
'egy0' => '否(請在以下欄位填上你的護照號碼和姓名。)',
'surname' => '姓氏',
'given_name' => '名',
'sex' => '性別',
'sex1' => '男',
'sex2' => '女',
'sex3' => '不願申明',
'id' => '身份證明文件 / 護照號碼',
'country' => '國家 / 地區',
'city' => '州/ 省 / 城市',
'birthday' => '出生日期(dd/mm/yyyy)',
'organization' => '所屬組織',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, '一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月' ),
'day' => '',

'title2' =>
'        <p><strong>語言</strong></p>',
'langn' => '母語',
'lang' => '熟練程度',
'select_lang' => '選擇語言',
'select_level' => '選擇熟練程度',

'lang_level1' => '1 (基本)',
'lang_level2' => '2 (中等)',
'lang_level3' => '3 (進階)',
'lang_level4' => '4 (接近母語)',

'lang1' => '第一語言',
'lang2' => '第二語言',
'lang3' => '第三語言',

'lang1_level' => '第一語言的熟練程度',
'lang2_level' => '第二語言的熟練程度',
'lang3_level' => '第三語言的熟練程度',

'title3' =>
'        <p><strong>參與的維基計劃和電郵戶口</strong></p>
         <ul class="form_notice">
           <li>年會籌備小組將只會在註冊相關程序和緊急通知時使用你的電郵地址資訊。</li>
         </ul>
',
'wiki_id' => '意欲使用的維基計劃戶口名稱。',
'email' => '電郵地址',


'legend2' => '參與狀況',
'title4' =>
'        <p><strong>參與狀況、名牌資訊和其他</strong></p>
         <p>為了更好安排住宿、議程跟進和相關方面的服務，我們希望你告訴我們下列的資料。</p>
',
'join_date' => '報名參與的日子',
'join1' => '7月17日',
'join2' => '7月18日',
'join3' => '7月19日',
'topic' => '感興趣的議程類型',
'topic1' => '維基媒體社群',
'topic2' => '自由資訊',
'topic3' => '技術架構',
'topic4' => '科學相關主題',
'showname' => '名牌資訊',
'custom_showname' => '想用在名牌上的名字',
'showname1' => '姓名',
'showname2' => '維基媒體計劃中的戶口名',
'showname3' => '所屬組織',
'showname4' => '其他',
'size' => 'T恤的大小',
'food' => '飲食習慣',
'food0' => '-',
'food1' => '不吃牛肉',
'food2' => '亞洲式素食者',
'food3' => '西式素食者(可吃蛋和牛奶)',
'food4' => '猶太飲食',
'food5' => '其他',
'food_other' => '請註明特別的飲食習慣',
'allegric' => '任何食物敏感',
'transportation_assistance' => '機票協助',
'need_transportation_assistance' => '我需要籌備小組為我預訂機票。',
'visa_assistance' => '簽證協助',
'need_visa_assistance' => '我需要簽證協助',
'visa_assistance_description' => '請說明籌備小組可以如何協助(請使用<strong>阿拉伯語</strong>或<strong>英語</strong>填寫)',

'title5' =>
'         <p><strong>住宿</strong></p>
         <p>我們提供兩種選擇。你可以選擇入住酒店，或入住聖馬可書院(Collège Saint Marc)的宿舍。
    請查閱<a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>該頁面上的資訊</a>，取得住宿地點的實際位置和其附屬設施的資料，以便報名時申明你的決定。</p>
',
'accommodation_hotel' => '希望入住酒店',
'hotels_metropol' => '大都會酒店(Metropole Hotel，每晚60美元)',
'hotels_delta' => '三角洲酒店 (Delta Hotel，每晚30美元)',
'hotels_dorms' => '聖馬可書院宿舍 (每晚10美元)',

'accommodation' => '入住日期',
'night1' => '7月16日',
'night2' => '7月17日',
'night3' => '7月18日',
'night4' => '7月19日',
'night5' => '7月20日',
'room' => '偏好的房間類別',
'room2' => '二人房',
'room4' => '四人房',
'room6' => '沒有所謂',

'title6' =>
'         <p><strong>付款</strong></p>
         <p>若你居住在<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">這裡所列出的103個國家/地區</a> (埃及除外)，你可以通過PayPal，以借帳或信用卡付款。你也可以選擇匯款或將款項直接存入亞力山卓籌備小組的銀行戶口。請注意：來自埃及的申請人將不能使用PayPal付款。</p>
',

'pay_method' => '付款方法',
'atm' => '銀行戶口付款',
'receipt' => '收據',
'need_receipt' => '我需要收據。',
'receipt_title' => '抬頭',
'receipt_address' => '郵寄地址',

'submit_notice' =>
'<li><strong>遞交了這份表格後，你需要再一次確認你的申請。</strong></li>',
'submit' => '遞交',
'reset' => '重置',

'confirm' => '確認',
'confirm_description' => '遞交這份表格前，請確認你已經正確填寫各項資料。',

'paypal' => '以PayPal付款',
'paypal_description' =>
'<p>請按"Buy Now"按鈕去使用PayPal付款</p> ',
'paypal_failed' => '取消PayPal付款',
'paypal_failed_description' => '<p>你可以重新填寫以下表格，或以下面所屬的其他途徑付款。</p>',
'paypal_successful' => 'PayPal付費成功！',
'paypal_successful_description' => '<p>多謝！我們收到付款和審閱登記資料後將會通知你。</p>',
'atm' => '通過銀行戶口付款',
'atm_description' => '
<p>收取住宿及參加費的銀行戶口資料如下：</p>
<ul class="atm-account">
<li>戶口名稱: Bibliotheca Alexandrina</li>
<li>銀行名稱: Commercial International Bank</li>
<li>分行: Bibliotheca Alexandrina Branch</li>
<li>SWIFT BIC編碼: CIBEEGCX041</li>
<li>戶口號碼(美元): 41-8930006-6</li>
</ul>
<p>由於PayPal在埃及的限制，你只可以通過銀行直接付款，資料和上面一樣，但請使用以下的埃及鎊戶口：</p>
<ul class="atm-account">
<li>戶口號碼(埃及鎊): 41-8900019-5</li>
</ul>
<p>請隨後把付費證明，連同你的姓名及上述的註冊編號以電子郵件寄到regwikimania2008 AT wikimedia.org，
我們會在3個工作天內回覆。你也可在<a href="index.php?action=query" title="query the registration status">這裡</a>查詢登記狀況。</p>
'
);

$lang_messages = array(
'successful' => '完成報名',
'successful_description' =>
'<p>多謝閣下報名參加2008國際維基媒體年會！你的報名表格己經成功遞交。請注意你必須完成繳費步驟，才能確認參與資格。

你的<strong>註冊編號</strong>已顯示在下面。請記下有關編號，以便日後查詢報名受理狀況及確認身份。
',
'cost' => '報名費用',
'wikimania_cost' => '會議：',
'accommodation_cost' => '住宿：',
'other_cost' => '其他支出：',
'total_cost' => '總支出',
'usd' => '美元(USD)',
'egp' => '埃及鎊(EGP)',
);

$lang_errors = array(
'repeat' => '有人使用了一樣的姓名及身份證 / 護照編號。也有可能是因為你重複提交了申請，或者你重新整理了報名表格頁面。',
'not_input' => '你留空了$1。',
'not_input_completely' => '你未完成$1。',
'not_select' => '你未選擇$1。',
'not_select_whether' => '你未選擇$1。',
'too_long' => '$1中的內容過長了，最長只能容納$2個位元組',
'incorect' => '你未能正確填寫$1。',
'wrong' => '你錯誤填寫了$1',
'visa_assistance_incomplete' => '你留空了簽證協助的資料。',
'wrong_query' => '錯誤的名稱或申請編號',
'paypal_unavailable' => '你所在的國家並不支援PayPal。'
);

$lang_query = array(
'unique_code' => '註冊編號',
'submit' => '查詢',
'your_status' => '你好，$1！以下是你的註冊資料：',
'received_money' => '註冊費用 (收到費用 / 應付費用):',
'lack' => '未支付費用',
'enough' => '己經支付費用',
'too_much' => '你支付了過多費用',
'accepted' => '你的申請已被<strong>確定</strong>。',
'rejected' => '你的申請已被<strong>拒絕</strong>。',
'not_yet' => '你的申請<strong>仍在處理中</strong>。'

);

$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

?>
