<?php

$lang_register_form = array(
'registration_title' => 'Registrierung für die Wikimania 2008',
'select' => 'Bitte wählen',
'query' => 'Frage den Status deiner Registrierung ab',
'query_title' => 'Du kannst hier den Status deiner Registrierung für die Wikimania 2008 abfragen.',
'correction' => 'Deine Informationen wurden aufgrund eines Fehlers im Formular nicht übermittelt.',

'legend1' => 'Informationen zur Person',
'title1' =>
'        <p><strong>Daten zur persönlichen Identifizierung</strong></p>
         <p>Bitte fülle das Formular mit deinen persönlichen Daten korrekt aus.</p>
',
'egy' => 'Bist du ein Staatsbürger von Ägypten?',
'egy1' => 'Ja, bin ich. (Bitte schreibe deine nationale ID-Nummer und deinen Namen in die folgenden Felder)',
'egy0' => 'Nein, bin ich nicht. (Bitte schreibe deine Reisepassnummer und deinen Namen in die folgenden Felder)',
'surname' => 'Familienname',
'given_name' => 'Vorname',
'sex' => 'Geschlecht', 
'sex1' => 'männlich',
'sex2' => 'weiblich',
'sex3' => 'anonym',
'id' => 'ID- / Reisepassnummer', 
'country' => 'Staat / Region', 
'city' => 'Bundesland/Provinz/Kanton / Stadt', 
'birthday' => 'Geburtsdatum (TT/MMM/JJJJ)',
'organization' => 'Organisation',
'year1' => '', 
'year' => '', 
'month' => '', 
'months' => array(NULL, 'Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'),
'day' => '', 

'title2' =>
'        <p><strong>Sprachkenntnisse</strong></p>',
'langn' => 'Muttersprache', 
'lang' => 'Kenntnisstand', 
'select_lang' => 'Wähle die Sprache aus',
'select_level' => 'Wähle den Kenntnisstand aus',

'lang_level1' => '1 (einfach)',
'lang_level2' => '2 (mittel)',
'lang_level3' => '3 (fortgeschritten)',
'lang_level4' => '4 (fast muttersprachlich)',

'lang1' => 'Sprache 1',
'lang2' => 'Sprache 2',
'lang3' => 'Sprache 3',

'lang1_level' => 'Kenntnisstand in Sprache 1',
'lang2_level' => 'Kenntnisstand in Sprache 2',
'lang3_level' => 'Kenntnisstand in Sprache 3',

'title3' => 
'        <p><strong>Wikimedia-Projekt und Account(s) mit E-Mail-Funktion</strong></p>
         <ul class="form_notice">
           <li>Deine Email-Daten werden nur für die Registrierung sowie für dringende Nachrichten über die Wikimania 2008 benutzt.</li>
         </ul>
', 
'wiki_id' => 'Bevorzugter Benutzername auf Wikimedia-Projekten', 
'email' => 'Deine Emailadresse', 


'legend2' => 'Teilnahme',
'title4' =>
'        <p><strong>Teilnahme, Namensschild und Verschiedenes</strong></p>
         <p>Für eine bessere Vorbereitung der Unterbringung, Veranstaltungspläne und anderer Dinge, informiere uns bitte über deine Wünsche in den folgenden Feldern.</p>
',
'join_date' => 'Datum der Teilnahme',
'join1' => '17. Juli',
'join2' => '18. Juli',
'join3' => '19. Juli',
'topic' => 'Bevorzugter Veranstaltungsbereich', 
'topic1' => 'Wikimedia-Communitys',
'topic2' => 'Freie Inhalte',
'topic3' => 'Technische Infrastruktur',
'topic4' => 'Wissenschaftsbereich',
'showname' => 'Namensschild',
'custom_showname' => 'Bevorzugter Nickname auf dem Namensschild',
'showname1' => 'Name',
'showname2' => 'Wikimedia-Account',
'showname3' => 'Organisation',
'showname4' => 'andere',
'size' => 'T-Shirt-Größe', 
'food' => 'Ernährungseinschränkungen',
'food0' => '-',
'food1' => 'Kein Rindfleisch',
'food2' => 'Vegetarier (asiatischer Stil)',
'food3' => 'Vegetarier (westlicher Stil, Eier und Milch sind gestattet)',
'food4' => 'Koscher',
'food5' => 'andere',
'food_other' => 'spezifische Ernährungseinschränkungen',
'allegric' => 'Allergien', 
'transportation_assistance' => 'Flugticketunterstützung',
'need_transportation_assistance' => 'Ja, ich brauche Hilfe bei meiner Flugreservierung',
'visa_assistance' => 'Hilfe mit dem Visum', 
'need_visa_assistance' => 'Ja, ich benötige Hilfe mit dem Visum',
'visa_assistance_description' => ' Bitte erläutere, wie das Organisationsteam dir mit Visumproblemen helfen kann. (auf <strong>Arabisch</strong> oder <strong>Englisch</strong>)',

'title5' =>
'         <p><strong>Unterbringung</strong></p>
         <p>Wir haben für dich zwei verfügbare Auswahlmöglichkeiten bezüglich der Unterbringung, du kannst zwischen zwei Hotels im Doppelzimmer wählen. Oder du kannst in den Schlafräumen des Saint-Marc-Colleges übernachten.
    Bitte lies vor der Registrierung die genauen Details zu Örtlichkeiten und Eigenschaften der Optionen auf <a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>der offiziellen Webseite der Wikimania</a>.</p>
',
'accommodation_hotel' => 'Bevorzugtes Hotel.',
'hotels_metropol'=> 'Metropol Hotel (etwa $60 pro Nacht)',
'hotels_delta'=> 'Delta Hotel (etwa $30 pro Nacht)',
'hotels_dorms' => 'Saint-Marc-College (etwa $10 pro Nacht)',

'accommodation' => 'Wann willst du übernachten?', 
'night1' => '16. Juli',
'night2' => '17. Juli',
'night3' => '18. Juli',
'night4' => '19. Juli',
'night5' => '20. Juli',
'room' => 'Bevorzugtes Zimmer',  
'room2' => 'Doppelzimmer',
'room4' => '4-Mann-Zimmer',
'room6' => 'Mir egal',

'title6' =>
'         <p><strong>Bezahlung</strong></p>
         <p>Du kannst deinen PayPal-Account belasten oder mit deiner Kreditkarte über PayPal bezahlen: <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">103 Länder / Regionen</a> (Ägypten nicht eingeschlossen) oder über eine Überweisung oder direkte Einzahlung auf das Bankkonto des Organisationsteams in Alexandria. Achtung: Die Möglichkeit der PayPal-Zahlung wird deaktiviert, wenn du Ägypter bist.</p>
',

'pay_method' => 'Art der Bezahlung', 
'atm' => 'Bezahlung auf das Bankkonto',
'receipt' => 'Quittung',
'need_receipt' => 'Ja, ich benötige eine Quittung auf Papier.',  
'receipt_title' => 'Titel', 
'receipt_address' => 'Postanschrift', 

'submit_notice' =>
'<li><strong>Nachdem du das Formular abgeschickt hast, hast du immer noch die Möglichkeit, deine Angaben zur Registrierung zu überprüfen.</strong></li>',
'submit' => 'Abschicken',
'reset' => 'Abbruch',

'confirm' => 'Überprüfung der Angaben',
'confirm_description' => 'Bevor du das Formular abschickst, stelle bitte sicher, dass du die folgenden Daten korrekt eingetragen hast:',

'paypal' => 'Bezahlung mit PayPal',
'paypal_description' =>
'<p>Bitte benutze die Schaltfläche "Jetzt bezahlen" unten, um mit PayPal zu bezahlen.</p> ',
'paypal_failed' => 'Abbruch der Bezahlung mit PayPal',
'paypal_failed_description' => '<p>Du kannst erneut unten das Formular ausfüllen oder kannst auf eine andere, unten beschriebene Weise bezahlen.</p>',
'paypal_successful' => 'Bezahlung mit PayPal erfolgreich',
'paypal_successful_description' => '<p>Danke! Wir benachrichtigen dich über das Ergebnis, nachdem wir die Bezahlung erhalten haben und deine Registrierungsdaten geprüft haben.</p>',
'atm' => 'Bezahlung über ein Bankkonto',
'atm_description' => '
<p>Bitte benutze die folgenden Bankdaten in Ägypten, um deine Registrierungs- und Übernachtungsgebühren zu bezahlen:</p>
<ul class="atm-account">
<li>Kontoinhaber: Bibliotheca Alexandrina</li>
<li>Bank: Commercial International Bank</li>
<li>Branch-Code: Bibliotheca Alexandrina Branch</li>
<li>SWIFT BIC code: CIBEEGCX041</li>
<li>Kontonummer Wikimania (USD): 41-8930006-6</li>
</ul>
<p>Aufgrund der PayPal-Registrierung in <b>Ägypten</b> kannst du direkt bei der Bank bezahlen, bitte benutze hierzu die obenstehenden Bankdaten mit der folgenden EGP-Kontonummer:</p>
<ul class="atm-account">
<li>Kontonummer Wikimania (EGP): 41-8900019-5</li>
</ul>
<p>Und bitte schicke deine Überweisungsquittung in elektronischer Form mit deinem Namen und deiner (obengenannten) Registrierungsnummer an regwikimania2008 AT wikimedia.org, wir werden innerhalb von drei Arbeitstagen antworten. Du kannst den <a href="index.php?action=query" title="query the registration status">Status deiner Registrierung auch online abfragen</a>.</p>
'
);

$lang_messages = array(
'successful' => 'Registrierung vollständig',
'successful_description' => 
'<p>Vielen Dank, dass du an der Wikimania 2008 teilnimmst! Dein Registrierungsformular wurde abgeschickt. Bitte beachte, dass du den Bezahlvorgang abschließen musst, um die Registrierung zu bestätigen.

Deine <strong>Registrierungsnummer</strong> steht unten. Bitte schreibe dir die Nummer auf, da sie benutzt wird, um den Status der Registrierung abzufragen und deine Identität zu bestätigen.
',
'cost' => 'Registrierungsgebühr',
'wikimania_cost' => 'Konferenz: ',
'accommodation_cost' => 'Unterbringung: ',
'other_cost' => 'Andere Kosten: ',
'total_cost' => 'Gesamt: ',
'usd' => ' USD',
'egp' => ' EGP',
);

$lang_errors = array(
'repeat' => 'Jemand hat sich mit dem gleichen Namen und der gleichen ID- bzw. Passnummer registriert. Es könnte sein, dass du das Formular zweimal abgeschickt oder die Registrierungsseite neu geladen hast.',
'not_input' => '$1 ist leer.',
'not_input_completely' => '$1 ist unvollständig.',
'not_select' => '$1 wurde nicht geprüft.',
'not_select_whether' => '$1 ist nicht spezifiziert.',
'too_long' => '$1 ist zu lang. Die Grenze dafür ist $2.',
'incorect' => '$1 ist nicht korrekt.',
'wrong' => '$1 ist falsch.',
'visa_assistance_incomplete' => 'Keine Informationen zur Visumhilfe eingegeben.',
'wrong_query' => 'Falscher Name oder Registrierungsnummer.',
'paypal_unavailable' => 'Das Land / die Region, die du ausgewählt hast, wird nicht von PayPal unterstützt.'
);

$lang_query = array(
'unique_code' => 'Registrierungsnummer',
'submit' => 'Abfrage',
'your_status' => 'Hallo, $1, hier ist der Status deiner Registrierung:',
'received_money' => 'Registrierungsgebühr (erhalten / erwartet):',
'lack' => 'Nicht erhalten',
'enough' => 'Schon bezahlt',
'too_much' => 'Du hast zuviel bezahlt',
'accepted' => 'Deine Registrierung wurde <strong>bestätigt</strong>.',
'rejected' => 'Deine Registrierung wurde <strong>abgelehnt</strong>.',
'not_yet' => 'Deine Registrierung wurde noch <strong>nicht bestätigt</strong>.'

);

$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

?>
