<?php

$lang_register_form = array(
'registration_title' => 'Registrazione Wikimania 2008',
'select' => 'Seleziona',
'query' => 'Controlla lo stato della tua registrazione',
'query_title' => 'Puoi controllare lo stato della tua registrazione a Wikimania 2008 qui.',
'correction' => 'Le tue informazioni non sono state inviate a causa di un errore nel modulo.',

'legend1' => 'Informazioni personali',
'title1' =>
'        <p><strong>Dati anagrafici</strong></p>
         <p>Per favore, inserisci correttamente i tuoi dati anagrafici nel modulo.</p>
',
'egy' => 'Sei cittadino della Repubblica Araba d\'Egitto?',
'egy1' => 'Sì, lo sono. (Per favore, immetti il tuo numero di identificazione nazionale e il tuo nome nei campi seguenti.',
'egy0' => 'No, non lo sono. (Per favore, immetti il tuo numero di passaporto e il tuo nome nei campi seguenti.)',
'surname' => 'Cognome',
'given_name' => 'Nome',
'sex' => 'Sesso',
'sex1' => 'Maschio',
'sex2' => 'Femmina',
'sex3' => 'Non dichiarato',
'id' => 'ID / Numero di passaporto',
'country' => 'Paese / Regione',
'city' => 'Stato / Città',
'birthday' => 'Data di nascita (gg/mm/aaaa)',
'organization' => 'Organizzazione',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre' ),
'day' => '',

'title2' =>
'        <p><strong>Lingue conosciute</strong></p>',
'langn' => 'Lingua madre',
'lang' => 'Livello di conoscenza',
'select_lang' => 'Seleziona la lingua',
'select_level' => 'Seleziona il livello di conoscenza',

'lang_level1' => '1 (Elementare)',
'lang_level2' => '2 (Intermedio)',
'lang_level3' => '3 (Avanzato)',
'lang_level4' => '4 (Quasi nativo)',

'lang1' => 'Lingua 1',
'lang2' => 'Lingua 2',
'lang3' => 'Lingua 3',

'lang1_level' => 'Livello di conoscenza della Lingua 1',
'lang2_level' => 'Livello di conoscenza della Lingua 2',
'lang3_level' => 'Livello di conoscenza della Lingua 3',

'title3' =>
'        <p><strong>Progetto Wikimedia e account e-mail</strong></p>
         <ul class="form_notice">
           <li>Le informazioni relative alla tua e-mail saranno usate unicamente per la registrazione e per comunicazioni urgenti relative a Wikimania 2008.</li>
         </ul>
',
'wiki_id' => 'Account del progetto Wikimedia principale',
'email' => 'La tua e-mail',


'legend2' => 'Partecipazione',
'title4' =>
'        <p><strong>Partecipazione, badge e varie</strong></p>
         <p>Per una migliore organizzazione relativa ad alloggio, conferenze e altri servizi, indicaci le tue preferenze compilando i campi seguenti.</p>
',
'join_date' => 'Date di partecipazione',
'join1' => '17 luglio',
'join2' => '18 luglio',
'join3' => '19 luglio',
'topic' => 'Tema preferito',
'topic1' => 'Comunità Wikimedia',
'topic2' => 'Conoscenza libera',
'topic3' => 'Infrastrutture tecniche',
'topic4' => 'Tema scientifico',
'showname' => 'Badge',
'custom_showname' => 'Nome o nickname scelto per il badge',
'showname1' => 'Nome',
'showname2' => 'Account Wikimedia',
'showname3' => 'Organizazione',
'showname4' => 'Altro',
'size' => 'Taglia della maglietta',
'food' => 'Preferenze o problemi alimentari',
'food0' => '-',
'food1' => 'Non mangi carne',
'food2' => 'Vegetariano (stile asiatico)',
'food3' => 'Vegetariano (stile occidentale, vanno bene uova e latte)',
'food4' => 'Kosher',
'food5' => 'Altro',
'food_other' => 'Specifica preferenze o problemi alimentari',
'allegric' => 'Allergie',
'transportation_assistance' => 'Assistenza relativa ai biglietti per l\'aereo',
'need_transportation_assistance' => 'Sì, necessito di assistenza per la prenotazione del volo',
'visa_assistance' => 'Assistenza per il visto',
'need_visa_assistance' => 'Sì, necessito di assistenza per il visto',
'visa_assistance_description' => ' Per favore, illustra come lo staff può aiutarti con questioni relative al visto. (in <strong>arabo</strong> o <strong>inglese</strong>)',

'title5' =>
'         <p><strong>Alloggio</strong></p>
         <p>Abbiamo reso possibile la scelta tra due soluzioni per il tuo alloggio, puoi scegliere uno tra i due hotel in centro città, camera doppia. O puoi alloggiare nei dormitori del College Saint-Marc.
    Per favore, prima di registrarti, controlla i dettagli sul <a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>sito ufficiale di Wikimania</a> per informazioni precise sulla posizione e le caratteristiche degli alloggi.</p>
',
'accommodation_hotel' => 'Alloggio scelto',
'hotels_metropol' => 'Hotel Metropol (60$ a notte)',
'hotels_delta' => 'Hotel Delta (30$ a notte)',
'hotels_dorms' => 'Dormitori del College Saint Marc (10$ a notte)',

'accommodation' => 'Giorni di alloggio',
'night1' => '16 luglio',
'night2' => '17 luglio',
'night3' => '18 luglio',
'night4' => '19 luglio',
'night5' => '20 luglio',
'room' => 'Tipologia di stanza scelta',
'room2' => 'Doppia',
'room4' => 'Quattro persone',
'room6' => 'Indifferente',

'title6' =>
'         <p><strong>Pagamento</strong></p>
         <p>Puoi addebitare sul tuo conto PayPal o pagare tramite la tua carta di credito via PayPal da <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">103 paesi / regioni</a> (Egitto escluso) o con rimessa e pagamento diretto sul conto bancario intestato al team di organizzazione ad Alexandria. Nota: se sei egiziano, l\'opzione PayPal verrà scartata.</p>
',

'pay_method' => 'Tipo di pagamento',
'atm' => 'Conto bancario',
'receipt' => 'Ricevuta',
'need_receipt' => 'Sì, necessito di ricevuta cartacea.',
'receipt_title' => 'Titolo',
'receipt_address' => 'Indirizzo di spedizione',

'submit_notice' =>
'<li><strong>Dopo l\'invio del modulo, hai ancora una possibilità di verificare i dati della tua registrazione.</strong></li>',
'submit' => 'Invia',
'reset' => 'Reset',

'confirm' => 'Verifica',
'confirm_description' => 'Prima di inviare il modulo, assicurati di aver inserito correttamente tutti i dati:',

'paypal' => 'Paga con PayPal',
'paypal_description' =>
'<p>Per favore, usa il pulsante "Buy Now" sotto per pagare con PayPal</p> ',
'paypal_failed' => 'Annulla il pagamento con PayPal',
'paypal_failed_description' => '<p>Puoi riprovare a compilare il modulo sotto, o puoi pagare con un altro modo, come illustrato sotto.</p>',
'paypal_successful' => 'Pagamento con PayPal eseguito con successo.',
'paypal_successful_description' => '<p>Grazie! Ti faremo avere altre informazioni dopo che avremo ricevuto il pagamento e revisionato le tue informazioni di registrazione.</p>',
'atm' => 'Paga tramite conto bancario',
'atm_description' => '
<p>Per favore, usa le seguenti coordinate bancarie relative all\'Egitto per trasferire l\'importo relativo alla registrazione e/o all\'alloggio:</p>
<ul class="atm-account">
<li>Nome del conto: Bibliotheca Alexandrina</li>
<li>Banca: Commercial International Bank</li>
<li>Branch Code: Bibliotheca Alexandrina Branch</li>
<li>Codice SWIFT BIC: CIBEEGCX041</li>
<li>Numero di conto Wikimania (USD): 41-8930006-6</li>
</ul>
<p>A causa di restrizioni relative a PayPal in <b>Egitto</b>, puoi pagare direttamente alla banca con le coordinate riportate sopra e con il seguente numero di conto EGP:</p>
<ul class="atm-account">
<li>Numero di conto Wikimania (EGP): 41-8900019-5</li>
</ul>
<p>E per favore invia la tua ricevuta elettronica con il tuo nome e il numero di registrazione (mostrato sopra) a regwikimania2008 AT wikimedia.org, risponderemo in tre giorni lavorativi. Puoi anche <a href="index.php?action=query" title="controlla lo stato della registrazione">controllare lo stato della registrazione online</a>.</p>
'
);

$lang_messages = array(
'successful' => 'Registrazione completata',
'successful_description' =>
'<p>Grazie per la tua partecipazione a Wikimania 2008! La tua registrazione è stata inviata. Per favore, nota che hai bisogno di completare il processo di pagamento affinché la registrazione possa essere confermata.

Il tuo <strong>numero di registrazione</strong> sarà mostrato in basso. Prendi nota del numero dato che sarà usato per controllare lo stato della tua registrazione e per confermare la tua identità in futuro.
',
'cost' => 'Contributo di registrazione',
'wikimania_cost' => 'Conferenza: ',
'accommodation_cost' => 'Alloggio: ',
'other_cost' => 'Altre spese: ',
'total_cost' => 'Totale: ',
'usd' => ' USD',
'egp' => ' EGP',
);

$lang_errors = array(
'repeat' => 'Qualcuno si è registrato con lo stesso nome e numero identificativo o di passaporto. È possibile che tu abbia inviato due volte il modulo o aggiornato la pagina di registrazione.',
'not_input' => '$1 è vuoto.',
'not_input_completely' => '$1 è incompleto.',
'not_select' => '$1 non è selezionato.',
'not_select_whether' => '$1 non è specificato.',
'too_long' => '$1 è troppo lungo, lunghezza limitata a $2.',
'incorect' => '$1 non è corretto.',
'wrong' => '$1 è errato.',
'visa_assistance_incomplete' => 'Non ci sono informazioni per l\'assistenza relativa al visto',
'wrong_query' => 'Nome o numero di registrazione non validi',
'paypal_unavailable' => 'Il paese o la regione selezionati non permettono il pagamento con PayPal'
);

$lang_query = array(
'unique_code' => 'Numero di registrazione',
'submit' => 'Controlla',
'your_status' => 'Ciao, $1, questo è lo stato della tua registrazione:',
'received_money' => 'Contributo di registrazione (ricevuto / atteso):',
'lack' => 'Non ricevuto',
'enough' => 'Già pagato',
'too_much' => 'Hai pagato un importo superiore al necessario',
'accepted' => 'La tua registrazione è stata <strong>confermata</strong>.',
'rejected' => 'La tua registrazione è stata <strong>rifiutata</strong>.',
'not_yet' => 'La tua registrazione <strong>non è stata confermata</strong>.'

);


$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

