<?php

$lang_register_form = array(
'registration_title' => 'Wikimania 2008 Registrace',
'select' => 'Vyberte',
'query' => 'Zjistit stav registrace',
'query_title' => 'Zde můžete zjistit aktuální stav Vaší registrace.',
'correction' => 'Informace nebyly odeslány z důvodu chyby ve formuláři.',

'legend1' => 'Osobní ínformace',
'title1' =>
'	  <p><strong>Osobní identifikační údaje</strong></p>
		 <p>Prosíme vyplnit údaje ve formuláři pravdivě.</p>
',
'egy' => 'Jste občanem Egyptské arabské republiky?',
'egy1' => 'Ano, jsem. (Do následujících polí uveďte své národní identifikační číslo a jméno)',
'egy0' => 'Ne, nejsem. (Do následujících polí uveďte číslo cestovního pasu a jméno)',
'surname' => 'Příjmení',
'given_name' => 'Jméno',
'sex' => 'Pohlaví',
'sex1' => 'Muž',
'sex2' => 'Žena',
'sex3' => 'Nechci uvést',
'id' => 'ID / Číslo pasu',
'country' => 'Země / Region',
'city' => 'Stát / Město',
'birthday' => 'Datum narození (dd/mmm/yyyy)',
'organization' => 'Organizace',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'ledna', 'února', 'března', 'dubna', 'května', 'června', 'července', 'srpna', 'září', 'října', 'listopadu', 'prosince' ),
'day' => '',

'title2' =>
'	  <p><strong>Jazykové schopnosti</strong></p>',
'langn' => 'Mateřský jazyk',
'lang' => 'Úroveň znalosti',
'select_lang' => 'Vyberte jazyk',
'select_level' => 'Vyberte úroveň znalosti',

'lang_level1' => '1 (Základní)',
'lang_level2' => '2 (Střední)',
'lang_level3' => '3 (Pokročilá)',
'lang_level4' => '4 (Jako rodilý mluvčí)',

'lang1' => 'Jazyk 1',
'lang2' => 'Jazyk 2',
'lang3' => 'Jazyk 3',

'lang1_level' => 'Úroveň znalosti jazyka 1',
'lang2_level' => 'Úroveň znalosti jazyka 2',
'lang3_level' => 'Úroveň znalosti jazyka 3',

'title3' =>
'	  <p><strong>Projekt Wikimedia a e-mail účtu</strong></p>
		 <ul class="form_notice">
		   <li>Informace o elektronické adrese budou použity pouze pro účely registrace a v případě neodkladných oznámení o Wikimanii 2008.</li>
		 </ul>
',
'wiki_id' => 'Přihlašovací jméno zvoleného účtu na projektu Wikimedia',
'email' => 'Váš e-mail',


'legend2' => 'Účast',
'title4' =>
'	  <p><strong>Informace o účasti, identifikační visačka a ostatní</strong></p>
		 <p>Pro zajištění ubytování, vstupu na akce a služeb, prosíme o vyznačení preferencí v následujících polích.</p>
',
'join_date' => 'Datum účasti',
'join1' => '17. červenec',
'join2' => '18. červenec',
'join3' => '19. červenec',
'topic' => 'Zájmová témata',
'topic1' => 'Komunity Wikimedia',
'topic2' => 'Svobodná tvorba',
'topic3' => 'Technická infrastruktura',
'topic4' => 'Vědecká cesta',
'showname' => 'Informace na visačce',
'custom_showname' => 'Požadovaná přezdívka',
'showname1' => 'Jméno',
'showname2' => 'Účet Wikimedia',
'showname3' => 'Organizace',
'showname4' => 'Ostatní',
'size' => 'Velikost trička',
'food' => 'Stravovací požadavky',
'food0' => '-',
'food1' => 'Žádné hovězí',
'food2' => 'Vegetarián (asijský)',
'food3' => 'Vegetarián (západní, vajíčka a mléko mohu)',
'food4' => 'Košer',
'food5' => 'Jiné',
'food_other' => 'Jiné stravovací požadavky',
'allegric' => 'Žádné alergie',
'transportation_assistance' => 'Pomoc s rezervací letu',
'need_transportation_assistance' => 'Ano, potřebuji pomoci s rezervací letu',
'visa_assistance' => 'Pomoc při získání víza',
'need_visa_assistance' => 'Ano, potřebuji pomoc s vízem',
'visa_assistance_description' => 'Uveďte, jak Vám může organizační tým pomoci se získáním víza. (v <strong>arabštině</strong> nebo <strong>angličtině</strong>)',

'title5' =>
'	   <p><strong>Ubytování</strong></p>
		 <p>Nabízíme 2 možnosti ubytování. Je možno bydlet v dvojlůžkovém pokoji v jednom ze dvou hotelů v centru města, nebo na kolejích Saint-Marc College.
	Před vyplněním formuláře si prostudujte detaily jednotlivých variant na <a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>oficiální stránce Wikimanie</a>.</p>
',
'accommodation_hotel' => 'Preferovaný hotel',
'hotels_metropol' => 'Hotel Metropol ($60 za noc)',
'hotels_delta' => 'Hotel Delta ($30 za noc)',
'hotels_dorms' => 'Koleje Saint-Marc ($10 za noc)',

'accommodation' => 'Dny ubytování',
'night1' => '16. červenec',
'night2' => '17. červenec',
'night3' => '18. červenec',
'night4' => '19. červenec',
'night5' => '20. červenec',
'room' => 'Preferovaný pokoj',
'room2' => '2-lůžkový',
'room4' => '4-lůžkový',
'room6' => 'Libovolný',

'title6' =>
'	   <p><strong>Platba</strong></p>
		 <p>Můžete využít svůj PayPal účet nebo kreditní kartu prostřednictvím PayPal účtu <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">ve 103 státech / regionech</a> (Egypt není obsažen) nebo bankovním převodem na účet organizačního týmu v Alexandrii. Pozor: Platbu prostřednictvím Paypal účtu nemohou využít egyptští občané.</p>
',

'pay_method' => 'Způsob platby',
'atm' => 'Bankovní převod',
'receipt' => 'Potvrzení',
'need_receipt' => 'Ano, potřebuji písemné potvrzení.',
'receipt_title' => 'Platební titul',
'receipt_address' => 'Poštovní adresa',

'submit_notice' =>
'<li><strong>Po odeslání formuláře je možno ověřit stav registrace.</strong></li>',
'submit' => 'Odeslat',
'reset' => 'Vymazat',

'confirm' => 'Ověření',
'confirm_description' => 'Před odesláním formuláře zkontrolujte správnost vyplněných údajů:',

'paypal' => 'Platba přes PayPal',
'paypal_description' =>
'<p>Použijte tlačítko "Kup nyní" pro platbu z PayPal účtu</p> ',
'paypal_failed' => 'Stornovat platbu z PayPal účtu',
'paypal_failed_description' => '<p>Můžete zkusit provést platbu znovu vyplněním níže uvedeného formuláře, nebo zvolit jiný způsob platby.</p>',
'paypal_successful' => 'Platba z PayPal účtu proběhla úspěšně',
'paypal_successful_description' => '<p>Děkujeme! Poté, co obdržíme Vaši platbu a zkontrolujeme registrační údaje, vyrozumíme Vás.</p>',
'atm' => 'Platba na bankovní účet',
'atm_description' => '
<p>Číslo účtu v Egyptě, na které je možno zasílat poplatky:</p>
<ul class="atm-account">
<li>Vlastník účtu: Bibliotheca Alexandrina</li>
<li>Banka: Commercial International Bank</li>
<li>Kód pobočky: Bibliotheca Alexandrina Branch</li>
<li>Kód SWIFT BIC: CIBEEGCX041</li>
<li>Číslo účtu Wikimanie (USD): 41-8930006-6</li>
</ul>
<p>Vzhledem k nemožnosti užití PayPal v <b>Egyptě</b>, použijte při vložení peněz přímo v bance výše uvedené údaje a číslo konta vedeného v egyptských librách:</p>
<ul class="atm-account">
<li>Číslo účtu Wikimanie (EGP): 41-8900019-5</li>
</ul>
<p>Potvrzení o provedené platbě nám zašlete spolu s Vaším jménem a číslem registrace (uvedeno nahoře) na regwikimania2008 AT wikimedia.org, odpovíme během tří pracovních dnů. Můžete také <a href="index.php?action=query" title="zkontrolovat stav registrace">zkontrolovat stav registrace</a>.</p>
'
);

$lang_messages = array(
'successful' => 'Registrace dokončena',
'successful_description' =>
'<p>Děkujeme Vám za účast na Wikimanii 2008! Vaše registrace byla odeslána. Po obdržení Vaší platby bude registrace potvrzena.

<strong>Číslo Vaší registrace</strong> bude uvedeno níže. Toto číslo si poznamenejte, bude používáno ke kontrole stavu registrace a později k potvrzení Vaší identity.
',
'cost' => 'Registrační poplatek',
'wikimania_cost' => 'Konference: ',
'accommodation_cost' => 'Ubytování: ',
'other_cost' => 'Další náklady: ',
'total_cost' => 'Celkem: ',
'usd' => ' USD',
'egp' => ' EGP',
);

$lang_errors = array(
'repeat' => 'Někdo již provedl registraci se stejným jménem a identifikačním číslem / číslem pasu. Je možné, že jste omylem odeslal(a) formulář dvakrát nebo znovunačetl(a) stránku registrace v prohlížeči.',
'not_input' => 'Pole $1 nebylo vyplněno.',
'not_input_completely' => 'Pole $1 není kompletní.',
'not_select' => 'Pole $1 nebylo označeno.',
'not_select_whether' => 'Pole $1 nebylo specifikováno.',
'too_long' => 'Pole $1 je příliš dlouhé, limit délky je $2 znaků.',
'incorect' => 'Pole $1 není správné.',
'wrong' => 'Pole $1 je chybjé.',
'visa_assistance_incomplete' => 'Informace o pomoci s vízem nebyla vyplněna.',
'wrong_query' => 'Chybné jméno nebo číslo registrace.',
'paypal_unavailable' => 'Vaše země / region není podporována v systému PayPal.'
);

$lang_query = array(
'unique_code' => 'Registrační číslo',
'submit' => 'Zkontrolovat',
'your_status' => 'Vítejte, $1, následuje stav Vaší registrace:',
'received_money' => 'Registrační poplatek (zaplacen / očekáván):',
'lack' => 'Nebyl uhrazen',
'enough' => 'Již zaplacen',
'too_much' => 'Zaplatil(a) jste příliš mnoho',
'accepted' => 'Vaše registrace byla <strong>potvrzena</strong>.',
'rejected' => 'Vaše registrace byla <strong>odmítnuta</strong>.',
'not_yet' => 'Vaše registrace dosud <strong>nebyla potvrzena</strong>.'

);

$lang_countries = array(
	'af' => 'Afghanistan',
	'ax' => 'Aland Islands',
	'al' => 'Albania',
	'dz' => 'Algeria',
	'as' => 'American Samoa',
	'ad' => 'Andorra',
	'ao' => 'Angola',
	'ai' => 'Anguilla',
	'aq' => 'Antarctica',
	'ag' => 'Antigua and Barbuda',
	'ar' => 'Argentina',
	'am' => 'Armenia',
	'aw' => 'Aruba',
	'au' => 'Australia',
	'at' => 'Austria',
	'az' => 'Azerbaijan',
	'bs' => 'Bahamas',
	'bh' => 'Bahrain',
	'bd' => 'Bangladesh',
	'bb' => 'Barbados',
	'by' => 'Belarus',
	'be' => 'Belgium',
	'bz' => 'Belize',
	'bj' => 'Benin',
	'bm' => 'Bermuda',
	'bt' => 'Bhutan',
	'bo' => 'Bolivia',
	'ba' => 'Bosnia and Herzegovina',
	'bw' => 'Botswana',
	'bv' => 'Bouvet Island',
	'br' => 'Brazil',
	'io' => 'British Indian Ocean Territory',
	'bn' => 'Brunei Darussalam',
	'bg' => 'Bulgaria',
	'bf' => 'Burkina Faso',
	'mm' => 'Burma (Myanmar)',
	'bi' => 'Burundi',
	'kh' => 'Cambodia',
	'cm' => 'Cameroon',
	'ca' => 'Canada',
	'cv' => 'Cape Verde',
	'ky' => 'Cayman Islands',
	'cf' => 'Central African Republic',
	'td' => 'Chad',
	'cl' => 'Chile',
	'hk' => 'Hong Kong SAR',
	'cn' => 'People\'s Republic of China',
	'tw' => 'Republic of China (Taiwan)',
	'cx' => 'Christmas Island',
	'cc' => 'Cocos (keeling) Islands',
	'co' => 'Colombia',
	'km' => 'Comoros',
	'cg' => 'Congo',
	'cd' => 'Congo\, The Democratic Republic of the',
	'ck' => 'Cook Islands',
	'cr' => 'Costa Rica',
	'ci' => 'Cote D\'ivoire',
	'hr' => 'Croatia',
	'cu' => 'Cuba',
	'cy' => 'Cyprus',
	'cz' => 'Czech Republic',
	'dk' => 'Denmark',
	'dj' => 'Djibouti',
	'dm' => 'Dominica',
	'do' => 'Dominican Republic',
	'ec' => 'Ecuador',
	'eg' => 'Egypt',
	'sv' => 'El Salvador',
	'gq' => 'Equatorial Guinea',
	'er' => 'Eritrea',
	'ee' => 'Estonia',
	'et' => 'Ethiopia',
	'fk' => 'Falkland Islands (malvinas)',
	'fo' => 'Faroe Islands',
	'fj' => 'Fiji',
	'fi' => 'Finland',
	'fr' => 'France',
	'gf' => 'French Guiana',
	'pf' => 'French Polynesia',
	'tf' => 'French Southern Territories',
	'ga' => 'Gabon',
	'gm' => 'Gambia',
	'ge' => 'Georgia',
	'de' => 'Germany',
	'gh' => 'Ghana',
	'gi' => 'Gibraltar',
	'gr' => 'Greece',
	'gl' => 'Greenland',
	'gd' => 'Grenada',
	'gp' => 'Guadeloupe',
	'gu' => 'Guam',
	'gt' => 'Guatemala',
	'gn' => 'Guinea',
	'gw' => 'Guinea-Bissau',
	'gy' => 'Guyana',
	'ht' => 'Haiti',
	'hm' => 'Heard Island and Mcdonald Islands',
	'va' => 'Holy See (Vatican City)',
	'hn' => 'Honduras',
	'hu' => 'Hungary',
	'is' => 'Iceland',
	'in' => 'India',
	'id' => 'Indonesia',
	'ir' => 'Iran, Islamic Republic of',
	'iq' => 'Iraq',
	'ie' => 'Ireland',
	'il' => 'Israel',
	'it' => 'Italy',
	'jm' => 'Jamaica',
	'jp' => 'Japan',
	'jo' => 'Jordan',
	'kz' => 'Kazakhstan',
	'ke' => 'Kenya',
	'ki' => 'Kiribati',
	'kp' => 'Democratic People\'s Republic of Korea',
	'kr' => 'Republic of Korea',
	'kw' => 'Kuwait',
	'kg' => 'Kyrgyzstan',
	'la' => 'Lao People\'s Democratic Republic',
	'lv' => 'Latvia',
	'lb' => 'Lebanon',
	'ls' => 'Lesotho',
	'lr' => 'Liberia',
	'ly' => 'Libyan Arab Jamahiriya',
	'li' => 'Liechtenstein',
	'lt' => 'Lithuania',
	'lu' => 'Luxembourg',
	'mo' => 'Macao',
	'mk' => 'Macedonia, The Former Yugoslav Republic of',
	'mg' => 'Madagascar',
	'mw' => 'Malawi',
	'my' => 'Malaysia',
	'mv' => 'Maldives',
	'ml' => 'Mali',
	'mt' => 'Malta',
	'mh' => 'Marshall Islands',
	'mq' => 'Martinique',
	'mr' => 'Mauritania',
	'mu' => 'Mauritius',
	'yt' => 'Mayotte',
	'mx' => 'Mexico',
	'fm' => 'Micronesia, Federated States of',
	'md' => 'Moldova, Republic of',
	'mc' => 'Monaco SAR',
	'mn' => 'Mongolia',
	'me' => 'Montenegro',
	'ms' => 'Montserrat',
	'ma' => 'Morocco',
	'mz' => 'Mozambique',
	'na' => 'Namibia',
	'nr' => 'Nauru',
	'np' => 'Nepal',
	'nl' => 'Netherlands',
	'an' => 'Netherlands Antilles',
	'nc' => 'New Caledonia',
	'nz' => 'New Zealand',
	'ni' => 'Nicaragua',
	'ne' => 'Niger',
	'ng' => 'Nigeria',
	'nu' => 'Niue',
	'nf' => 'Norfolk Island',
	'mp' => 'Northern Mariana Islands',
	'no' => 'Norway',
	'om' => 'Oman',
	'pk' => 'Pakistan',
	'pw' => 'Palau',
	'ps' => 'Palestinian Territory',
	'pa' => 'Panama',
	'pg' => 'Papua New Guinea',
	'py' => 'Paraguay',
	'pe' => 'Peru',
	'ph' => 'Philippines',
	'pn' => 'Pitcairn',
	'pl' => 'Poland',
	'pt' => 'Portugal',
	'pr' => 'Puerto Rico',
	'qa' => 'Qatar',
	're' => 'Reunion',
	'ro' => 'Romania',
	'ru' => 'Russian Federation',
	'rw' => 'Rwanda',
	'sh' => 'Saint Helena',
	'kn' => 'Saint Kitts and Nevis',
	'lc' => 'Saint Lucia',
	'pm' => 'Saint Pierre and Miquelon',
	'vc' => 'Saint Vincent and the Grenadines',
	'ws' => 'Samoa',
	'sm' => 'San Marino',
	'st' => 'Sao Tome and Principe',
	'sa' => 'Saudi Arabia',
	'sn' => 'Senegal',
	'rs' => 'Serbia',
	'sc' => 'Seychelles',
	'sl' => 'Sierra Leone',
	'sg' => 'Singapore',
	'sk' => 'Slovakia',
	'si' => 'Slovenia',
	'sb' => 'Solomon Islands',
	'so' => 'Somalia',
	'za' => 'South Africa',
	'gs' => 'South Georgia and the South Sandwich Islands',
	'es' => 'Spain',
	'lk' => 'Sri Lanka',
	'sd' => 'Sudan',
	'sr' => 'Suriname',
	'sj' => 'Svalbard and Jan Mayen',
	'sz' => 'Swaziland',
	'se' => 'Sweden',
	'ch' => 'Switzerland',
	'sy' => 'Syrian Arab Republic',
	'tj' => 'Tajikistan',
	'tz' => 'Tanzania, United Republic of',
	'th' => 'Thailand',
	'tl' => 'Timor-leste',
	'tg' => 'Togo',
	'tk' => 'Tokelau',
	'to' => 'Tonga',
	'tt' => 'Trinidad and Tobago',
	'tn' => 'Tunisia',
	'tr' => 'Turkey',
	'tm' => 'Turkmenistan',
	'tc' => 'Turks and Caicos Islands',
	'tv' => 'Tuvalu',
	'ug' => 'Uganda',
	'ua' => 'Ukraine',
	'ae' => 'United Arab Emirates',
	'gb' => 'United Kingdom',
	'us' => 'United States',
	'um' => 'United States Minor Outlying Islands',
	'uy' => 'Uruguay',
	'uz' => 'Uzbekistan',
	'vu' => 'Vanuatu',
	've' => 'Venezuela',
	'vn' => 'Viet Nam',
	'vg' => 'Virgin Islands, British',
	'vi' => 'Virgin Islands, U.S.',
	'wf' => 'Wallis and Futuna',
	'eh' => 'Western Sahara',
	'ye' => 'Yemen',
	'zm' => 'Zambia',
	'zw' => 'Zimbabwe'
);

