<?php

$lang_register_form = array(
'registration_title' => 'Registrering Wikimania 2008',
'select' => 'Velg',
'query' => 'Henter din registreringsstatus',
'query_title' => 'Du kan hente registreringsstatusen for Wikimania 2008 her.',
'correction' => 'Din informasjon er ikke sendt på grunn av en feil i skjemaet.',

'legend1' => 'Personinformasjon',
'title1' =>
'        <p><strong>Personlig data for identifisering</strong></p>
         <p>Vennligst fyll inn dine personlige data korrekt.</p>
',
'egy' => 'Er du en innbygger i Egypt?',
'egy1' => 'Ja, det er jeg. (Vennligst skriv inn ditt nasjonale identifikasjonsnummer og ditt navn i følgende felt)',
'egy0' => 'Nei, det er jeg ikke. (Vennligst skriv inn ditt passnummer og navnet i passet i følgende felt)',
'surname' => 'Etternavn',
'given_name' => 'Fornavn',
'sex' => 'Kjønn', 
'sex1' => 'Mann',
'sex2' => 'Kvinne',
'sex3' => 'Vil ikke oppgi',
'id' => 'ID / Passnummer', 
'country' => 'Land / Region', 
'city' => 'Stat / By', 
'birthday' => 'Fødselsdato (dd/mm/åååå)',
'organization' => 'Organisasjon',
'year1' => '', 
'year' => '', 
'month' => '', 
'months' => array(NULL, 'januar', 'februar', 'mars', 'april', 'mai', 'juni', 'juli', 'august', 'september', 'oktober', 'november', 'desember'),
'day' => '', 

'title2' =>
'        <p><strong>Lingvistisk ferdighet</strong></p>',
'langn' => 'Morsmål', 
'lang' => 'Ferdighetsnivå', 
'select_lang' => 'Velg språket',
'select_level' => 'Velg ferdighetsnivå',

'lang_level1' => '1 (Grunnleggende)',
'lang_level2' => '2 (Middelmådig)',
'lang_level3' => '3 (Avansert)',
'lang_level4' => '4 (Nær flytende)',

'lang1' => 'Språk 1',
'lang2' => 'Språk 2',
'lang3' => 'Språk 3',

'lang1_level' => 'Ferdighetsnivå for språk 1',
'lang2_level' => 'Ferdighetsnivå for språk 2',
'lang3_level' => 'Ferdighetsnivå for språk 3',

'title3' => 
'        <p><strong>Wikimedia-prosjekt og e-postkontoer</strong></p>
         <ul class="form_notice">
           <li>Din e-postadresse blir brukt til registrering og viktige meldinger rundt Wikimania 2008.</li>
         </ul>
', 
'wiki_id' => 'Ønsket Wikimedia-prosjekt-kontonavn', 
'email' => 'Din e-postadresse', 


'legend2' => 'Deltagelse',
'title4' =>
'        <p><strong>Deltagelse, skiltinformasjon og diverse</strong></p>
         <p>For bedre administrering av losji, track sessions og relaterte tjenester, vennligst fortell oss dine preferanser for følgende områder.</p>
',
'join_date' => 'Tid for deltagelse',
'join1' => '17. juli',
'join2' => '18. juli',
'join3' => '19. juli',
'topic' => 'Ønsket temalinje', 
'topic1' => 'Wikimedia-prosjekter',
'topic2' => 'Fritt innhold',
'topic3' => 'Teknisk infrastruktur',
'topic4' => 'Vitenskaplig linje',
'showname' => 'Skiltinformasjon',
'custom_showname' => 'Ønsket kallenavn på skilt',
'showname1' => 'Navn',
'showname2' => 'Wikimedia-konto',
'showname3' => 'Organisasjon',
'showname4' => 'Annet',
'size' => 'T-skjortestørrelse', 
'food' => 'Kostholdsrestriksjoner',
'food0' => '-',
'food1' => 'Ikke biff',
'food2' => 'Vegetarianer (Asiatisk)',
'food3' => 'Vegetarianer (Vestlig stil, egg og melk er ok)',
'food4' => 'Kosher',
'food5' => 'Annet',
'food_other' => 'Spesifiserte kostholdsrestriksjoner',
'allegric' => 'Eventuelle allergier', 
'transportation_assistance' => 'Flybillettassistanse',
'need_transportation_assistance' => 'Ja, jeg trenger deres assistanse for å bestille flybillett',
'visa_assistance' => 'Visumsassistanse', 
'need_visa_assistance' => 'Ja, jeg trenger visumsassistanse',
'visa_assistance_description' => ' Vennligst spesifiser hvordan organisasjonslaget kan hjelpe deg med visumproblemer. (på <strong>arabisk</strong> eller <strong>engelsk</strong>)',

'title5' =>
'         <p><strong>Losji</strong></p>
         <p>Vi har lagd to muligheter for deg angående losji. Du kan bo på hotell eller på Saint-Marc Colleges sovesaler.
    Vennligst se detaljer på <a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>Wikimanias offisielle nettside</a> for presis plassering og spesifikasjoner for hvert valg før du registrerer.</p>
',
'accommodation_hotel' => 'Ønsket hotell.',
'hotels_metropol'=> 'Metropol Hotel ($60 per natt)',
'hotels_delta'=> 'Delta Hotel ($30 per natt)',
'hotels_dorms' => 'Saint Marc Dorms ($10 per natt)',

'accommodation' => 'Dag(er) du skal være', 
'night1' => '16. juli',
'night2' => '17. juli',
'night3' => '18. juli',
'night4' => '19. juli',
'night5' => '20. juli',
'room' => 'Ønsket rom',  
'room2' => 'dobbelt-',
'room4' => 'firemanns-',
'room6' => 'Bryr meg ikke',

'title6' =>
'         <p><strong>Betaling</strong></p>
         <p>Du kan belaste din PayPal-konto eller betale med kredittkort via PayPal 1 <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">103 land / regioner</a> (Egypt er ikke inkludert) eller via remisse og direkte betaling til bankkontoen til organisasjonslaget i Alexandria. Merk: PayPal-muligheten frafaller hvis du er egyptisk</p>
',

'pay_method' => 'Betalingsmåte', 
'atm' => 'Bankkontobetaling',
'receipt' => 'Kvittering',
'need_receipt' => 'Ja, jeg trenger papirkvittering.',  
'receipt_title' => 'Tittel', 
'receipt_address' => 'Postadresse', 

'submit_notice' =>
'<li><strong>Du har fortsatt mulighet til å verifisere registreringen din etter at du har levert blanketten.</strong></li>',
'submit' => 'Send',
'reset' => 'Tilbakestill',

'confirm' => 'Bekreftelse',
'confirm_description' => 'Vennligst vær sikker på at du har fylt inn all informasjon korrekt før du sender:',

'paypal' => 'Betal med PayPal',
'paypal_description' =>
'<p>Vennligst benytt «Buy Now»-knappen nedenfor for å betale via PayPal</p> ',
'paypal_failed' => 'Avbryt PayPal-betalingen',
'paypal_failed_description' => '<p>Du kan prøve på nytt ved å fylle ut blanketten nedenfor, eller du kan betale på en annen måte som forklart ovenfor.</p>',
'paypal_successful' => 'Vellykket betaling via PayPal',
'paypal_successful_description' => '<p>Takk! Vi vil gi deg beskjed om resultatet når vi har mottatt betalingen og sett over din registreringsinformasjon.</p>',
'atm' => 'Betal via bankkonto',
'atm_description' => '
<p>Vennligst benytt følgende bankdetaljer i Egypt for å betale for registrering og/eller losji:</p>
<ul class="atm-account">
<li>Kontonavn: Bibliotheca Alexandrina</li>
<li>Bank: Commercial International Bank</li>
<li>Bransjekode: Bibliotheca Alexandrina Branch</li>
<li>SWIFT BIC-kode: CIBEEGCX041</li>
<li>Kontonummer til Wikimania (USD): 41-8930006-6</li>
</ul>
<p>På grunn av PayPal-restriksjoner i <b>Egypt</b>, kan du betale direkte til banken, vennligst benytt bankdetaljene ovenfor, med følgende EGP kontonummer :</p>
<ul class="atm-account">
<li>Kontonummer til Wikimania (EGP): 41-8900019-5</li>
</ul>
<p>Og vennligst send overføringskvitteringen din elektronisk med ditt navn og registreringsnummer (vist ovenfor) til regwikimania2008 AT wikimedia.org. Vi vil svare innen tre virkedager. Du kan også <a href="index.php?action=query" title="query the registration status">stille spørsmål om registreringsstatusen online</a>.</p>
'
);

$lang_messages = array(
'successful' => 'Registrering ferdig',
'successful_description' => 
'<p>Takk for at du deltar på Wikimania 2008! Registreringsblanketten din har blitt sendt. Vennligst merk deg at du må fullføre betalingsprossessen for at registreringen kan bekreftes.

<strong>Registreringsnummeret</strong> ditt vil vises nedenfor. Vennligst noter nummeret, for det vil bli brukt ved spørsmål angående registreringsstatus og for å bekrefte din indentitet fremover.
',
'cost' => 'Registreringsgebyr',
'wikimania_cost' => 'Konferanse: ',
'accommodation_cost' => 'Losji: ',
'other_cost' => 'Andre kostnader: ',
'total_cost' => 'Totalt: ',
'usd' => ' USD',
'egp' => ' EGP',
);

$lang_errors = array(
'repeat' => 'Noen har registrert seg med samme navn og indentifikasjons- /passnummer. Det er mulig du har sendt dobbelt eller fornyet registreringssiden.',
'not_input' => '$1 er tom.',
'not_input_completely' => '$1 er ikke ferdig.',
'not_select' => '$1 er ikke sjekket.',
'not_select_whether' => '$1 har ikke blitt spesifisert.',
'too_long' => '$1 er for lang, maksimumslengden er $2.',
'incorect' => '$1 er ikke korrekt.',
'wrong' => '$1 er feil.',
'visa_assistance_incomplete' => 'Visumsassistanseinformasjon er tom.',
'wrong_query' => 'Feil navn eller registreringsnummer.',
'paypal_unavailable' => 'Landet / regionen du har valgt støttes ikke av PayPal.'
);

$lang_query = array(
'unique_code' => 'Registreringsnummer',
'submit' => 'Spørsmål',
'your_status' => 'Hei, $1, her er din registreringsstatus:',
'received_money' => 'Registreringsgebyr (mottatt / forventet):',
'lack' => 'Ikke mottatt',
'enough' => 'Allerede betalt',
'too_much' => 'Du betalte for mye',
'accepted' => 'Din registrering er <strong>bekreftet</strong>.',
'rejected' => 'Din registrering ble <strong>avvist</strong>.',
'not_yet' => 'Din registrering er <strong>ikke bekreftet</strong>.'

);


$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

?>
