<?php

$lang_register_form = array(
'registration_title' => 'Inscripción para Wikimania 2008',
'select' => 'Elija una opción',
'query' => 'Consulta el estado de tu inscripción',
'query_title' => 'Puedes consultar el estado de tu inscripción para Wikimania 2008 aquí.',
'correction' => 'La información no ha sido enviada debido a un error en el formulario.',

'legend1' => 'Información personal',
'title1' =>
'        <p><strong>Datos de identificación personal</strong></p>
         <p>Por favor completa correctamente tu información personal.</p>
',
'egy' => '¿Eres ciudadano de la República Árabe de Egipto?',
'egy1' => 'Sí. (Por favor escribe tu número de identificación nacional y tu nombre en los siguientes campos)',
'egy0' => 'No. (Por favor escribe tu número de pasaporte y tu nombre tal como figura en el pasaporte en los siguientes campos)',
'surname' => 'Apellido',
'given_name' => 'Nombre',
'sex' => 'Sexo',
'sex1' => 'Masculino',
'sex2' => 'Femenino',
'sex3' => 'No declara',
'id' => 'Número de identificación / Número de Pasaporte',
'country' => 'País / Región',
'city' => 'Estado / Ciudad',
'birthday' => 'Fecha de Nacimiento (dd/mm/aaaa)',
'organization' => 'Organización',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre' ),
'day' => '',

'title2' =>
'        <p><strong>Habilidades lingüísticas</strong></p>',
'langn' => 'Idioma nativo',
'lang' => 'Nivel',
'select_lang' => 'Selecciona un idioma',
'select_level' => 'Selecciona el nivel',

'lang_level1' => '1 (Basico)',
'lang_level2' => '2 (Intermedio)',
'lang_level3' => '3 (Avanzado)',
'lang_level4' => '4 (Casi nativo)',

'lang1' => 'Idioma 1',
'lang2' => 'Idioma 2',
'lang3' => 'Idioma 3',

'lang1_level' => 'Nivel del idioma 1',
'lang2_level' => 'Nivel del idioma 2',
'lang3_level' => 'Nivel del idioma 3',

'title3' =>
'        <p><strong>Proyecto de Wikimedia y dirección/es de correo electrónico</strong></p>
         <ul class="form_notice">
           <li>Tu correo electrónico sólo será utilizado para la inscripción y para notificaciones urgentes sobre Wikimania 2008.</li>
         </ul>
',
'wiki_id' => 'Nombre de la cuenta de tu proyecto Wikimedia preferido',
'email' => 'Tu correo electrónico',


'legend2' => 'Participación',
'title4' =>
'        <p><strong>Participación, información para tu credencial y otros datos</strong></p>
         <p>Para facilitar arreglos en el alojamiento, las sesiones de las distintas áreas y servicios relacionados, por favor indícanos tus opciones en los siguientes campos.</p>
',
'join_date' => 'Fecha de participación',
'join1' => '17 de julio',
'join2' => '18 de julio',
'join3' => '19 de julio',
'topic' => 'Área preferida',
'topic1' => 'Comunidades Wikimedia',
'topic2' => 'Contenido libre',
'topic3' => 'Infraestructura técnica',
'topic4' => 'Área científica',
'showname' => 'Información para la credencial',
'custom_showname' => 'Apodo para la credencial',
'showname1' => 'Nombre',
'showname2' => 'Cuenta de Wikimedia',
'showname3' => 'Organización',
'showname4' => 'Otro',
'size' => 'Talla de remera',
'food' => 'Restricciones en la dieta',
'food0' => '-',
'food1' => 'No como carne',
'food2' => 'Vegetariano (estilo asiático)',
'food3' => 'Vegeteriano (estilo occidental, huevos y leche están permitidos)',
'food4' => 'Kosher',
'food5' => 'Otras',
'food_other' => 'Restricciones especificadas en la dieta',
'allegric' => 'Alguna alergia',
'transportation_assistance' => 'Asistencia para boletos de viaje',
'need_transportation_assistance' => 'Sí, necesito que me ayuden con mi reservación',
'visa_assistance' => 'Ayuda para obtener la visa',
'need_visa_assistance' => 'Sí, necesito ayuda para obtener la visa',
'visa_assistance_description' => ' Por favor indícanos cómo puede ayudarte el equipo organizador a obtener la visa. (en <strong>Árabe</strong> o <strong>Inglés</strong>)',

'title5' =>
'         <p><strong>Alojamiento</strong></p>
         <p>Tenemos 2 opciones disponibles para el alojamiento. Puedes elegir entre 1 de 2 hoteles en el centro de la ciudad, en habitación doble, o puedes quedarte en los dormitorios del Saint-Marc College.
    Por favor mira los detalles en el <a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>sitio oficial de Wikimania</a> para conocer la localización y especificaciones exactas de cada opción antes de registrarte.</p>
',
'accommodation_hotel' => 'Hotel preferido.',
'hotels_metropol' => 'Hotel Metropol ($60 por noche)',
'hotels_delta' => 'Hotel Delta ($30 por noche)',
'hotels_dorms' => 'Dormitorios en Saint Marc ($10 por noche)',

'accommodation' => 'Fechas de estadía',
'night1' => '16 de julio',
'night2' => '17 de julio',
'night3' => '18 de julio',
'night4' => '19 de julio',
'night5' => '20 de julio',
'room' => 'Preferencia de habitación',
'room2' => 'doble',
'room4' => 'cádruple',
'room6' => 'Cualquiera',

'title6' =>
'         <p><strong>Pago</strong></p>
         <p>Puedes utilizar tu cuenta Paypal o pagar utilizando tu tarjeta de crédito a través de PayPal en <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">103 países / regiones</a> (No incluye Egipto) o por transferencia y pago directo a la cuenta bancaria del equipo organizador en Alejandría. Nota: la opción de PayPal será descartada si eres egipcio</p>
',

'pay_method' => 'Tipo de Pago',
'atm' => 'Pago a través de cuenta bancaria',
'receipt' => 'Recibo',
'need_receipt' => 'Sí, necesito recibo impreso.',
'receipt_title' => 'Título',
'receipt_address' => 'Dirección postal',

'submit_notice' =>
'<li><strong>Luego de enviar el formulario, tendrás la posibilidad de verificar su inscripción.</strong></li>',
'submit' => 'Enviar',
'reset' => 'Limpiar',

'confirm' => 'Verificación',
'confirm_description' => 'Antes de aceptar el formulario, por favor, asegúrate de haber completado correctamente la información:',

'paypal' => 'Pago a través de PayPal',
'paypal_description' =>
'<p>Por favor, utiliza el botón "Buy now" que aparece debajo para pagar a través de PayPal</p> ',
'paypal_failed' => 'Cancelar el pago a través de PayPal',
'paypal_failed_description' => '<p>Puedes intentar nuevamente llenando el formalrio que se encuentra debajo o puedes pagar mediante las otras formas explicadas más abajo.</p>',
'paypal_successful' => 'Pago a través de PayPal exitoso',
'paypal_successful_description' => '<p>¡Gracias! Te notificaremos el resultado luego de recibir el pago y de revisar la información de tu inscripción.</p>',
'atm' => 'Pago a través de cuenta bancaria',
'atm_description' => '
<p>Por favor utilice la siguiente información bancaria en Egipto para transferir su pago de inscripción y/o estadía:</p>
<ul class="atm-account">
<li>Nombre de la cuenta bancaria: Bibliotheca Alexandrina</li>
<li>Banco: Commercial International Bank</li>
<li>Código de sucursal: Bibliotheca Alexandrina Branch</li>
<li>Código SWIFT BIC: CIBEEGCX041</li>
<li>Número de cuenta de Wikimania (USD): 41-8930006-6</li>
</ul>
<p>Debido a la restricción de Paypal en <b>Egipto</b>, puedes pagar directamente en el banco, por favor utiliza los datos arriba mencionados con el siguiente número de cuenta en EGP:</p>
<ul class="atm-account">
<li>Número de cuenta de Wikimania (EGP): 41-8900019-5</li>
</ul>
<p>Por favor envía el recibo de tu transferencia en formato electrónico con tu nombre y el número de inscripción (arriba mencionado) a regwikimania2008 AT wikimedia.org, te responderemos dentro de los tres días hábiles. También puedes <a href="index.php?action=query" title="Consultar el estado de tu inscripción">consultar el estado de tu inscripción en línea</a>.</p>
'
);

$lang_messages = array(
'successful' => 'Inscripción completa',
'successful_description' =>
'<p>¡Gracias por sumarte a Wikimania 2008! Tu formulario de inscripción fue aceptado. Por favor, ten en cuenta que necesitas completar el proceso de pago para que la inscripción pueda ser confirmada.

Tu <strong>número de inscripción</strong> será mostrado debajo. Por favor, anota este número ya que será utilizado para consultar el estado de tu inscripción y para confirmar tu identidad en el futuro.
',
'cost' => 'Cuota de inscripción',
'wikimania_cost' => 'Conferencia: ',
'accommodation_cost' => 'Alojamiento: ',
'other_cost' => 'Otros costos: ',
'total_cost' => 'Total: ',
'usd' => ' USD',
'egp' => ' EGP',
);

$lang_errors = array(
'repeat' => 'Ya existe alguien registrado con este nombre y número de identificación / pasaporte. Es posible que te hayas registrado dos veces o que hayas recargado la página de inscripción.',
'not_input' => '$1 está vacío.',
'not_input_completely' => '$1 está incompleto.',
'not_select' => '$1 no fue elegido.',
'not_select_whether' => '$1 no fue especificado.',
'too_long' => '$1 es muy largo, la longitud máxima es $2.',
'incorect' => '$1 es incorrecto.',
'wrong' => '$1 es erróneo.',
'visa_assistance_incomplete' => 'La información de asistencia para la visa está vacía.',
'wrong_query' => 'Nombre o número de inscripción incorrecto.',
'paypal_unavailable' => 'PaypPal no funciona en el país / región seleccionada.'
);

$lang_query = array(
'unique_code' => 'Número de inscripción',
'submit' => 'Consultar',
'your_status' => 'Hola, $1, aquí tienes el estado de tu inscripción:',
'received_money' => 'Cuota de inscripción (recibida / esperada):',
'lack' => 'No recibida',
'enough' => 'Pagada',
'too_much' => 'Has pagado por demás',
'accepted' => 'Tu inscripción está <strong>confirmada</strong>.',
'rejected' => 'Tu inscripción fue <strong>rechazada</strong>.',
'not_yet' => 'Tu inscripción <strong>no fue confirmada</strong>.'

);

$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);
