<?php

$lang_register_form = array(
'registration_title' => 'ウィキマニア2008登録',
'select' => 'お選び下さい',
'query' => '登録状況の確認',
'query_title' => 'こちらでウィキマニア2008への参加登録状況を確認できます。',
'correction' => '入力内容にエラーがあります。登録は完了していません。',

'legend1' => '個人情報',
'title1' =>
'	  <p><strong>個人識別情報</strong></p>
	   <p>フォームにあなたの個人情報を正しく入力してください。</p>
',
'egy' => 'あなたはエジプト・アラブ共和国市民ですか？',
'egy1' => 'はい、そうです（身分証番号と姓名を以下に記入してください）',
'egy0' => 'いいえ、ちがいます（あなたのパスポート番号とパスポートに記載された名前をローマ字で以下に記入してください）',
'surname' => '姓（日本人の方はローマ字でお願いします）',
'given_name' => '名（日本人の方はローマ字でお願いします）',
'sex' => '性別',
'sex1' => '男',
'sex2' => '女',
'sex3' => '記入を拒否します',
'id' => '身分証番号 / パスポート番号',
'country' => '国 / 地域',
'city' => '市町村',
'birthday' => '生年月日（日（2桁）、月、年（4桁））',
'organization' => '所属',
'year1' => '',
'year' => '年（西暦）',
'month' => '月',
'months' => array( NULL, '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12' ),
'day' => '日（2桁）',

'title2' =>
'	  <p><strong>言語</strong></p>',
'langn' => '母語',
'lang' => '習熟度',
'select_lang' => '言語を選んでください。',
'select_level' => '当該言語の習熟度',

'lang_level1' => '1 基本レベル (Basic)',
'lang_level2' => '2 一般レベル (Intermediate)',
'lang_level3' => '3 熟練レベル (Advanced)',
'lang_level4' => '4 専門レベル (Near native)',

'lang1' => '言語1',
'lang2' => '言語2',
'lang3' => '言語3',

'lang1_level' => '言語1の習熟度',
'lang2_level' => '言語2の習熟度',
'lang3_level' => '言語3の習熟度',

'title3' =>
'	  <p><strong>ウィキメディア・プロジェクトのアカウントと電子メールアドレス</strong></p>
	   <ul class="form_notice">
	     <li>メールアドレスはウィキマニア2008における参加受付および緊急連絡の際にのみ使われます。</li>
	   </ul>
',
'wiki_id' => 'ウィキメディア・プロジェクトのアカウント（ひとつ選択）',
'email' => '電子メールアドレス',


'legend2' => '参加登録',
'title4' =>
'	  <p><strong>参加登録、名札等について</strong></p>
	   <p>滞在先確保・セッション日程確定・関連サービスなどのため、以下からご希望の日程などをお知らせください。</p>
',
'join_date' => '参加日程',
'join1' => '7月17日',
'join2' => '7月18日',
'join3' => '7月19日',
'topic' => '興味のあるセッション',
'topic1' => 'ウィキメディア・コミュニティ',
'topic2' => '自由なコンテンツ',
'topic3' => '技術基盤',
'topic4' => '学術的セッション',
'showname' => '名札',
'custom_showname' => '名札に記載する際の呼称',
'showname1' => '氏名',
'showname2' => 'ウィキメディア・アカウント名',
'showname3' => '所属',
'showname4' => 'その他',
'size' => 'Tシャツのサイズ',
'food' => '飲食習慣',
'food0' => '-',
'food1' => '牛肉は食べません',
'food2' => 'ベジタリアン（アジアスタイル）',
'food3' => 'ベジタリアン（欧米スタイル。卵とミルクを含む）',
'food4' => 'ユダヤ式',
'food5' => 'その他',
'food_other' => '詳細',
'allegric' => 'アレルギー反応を起こす食べ物',
'transportation_assistance' => '航空券予約支援',
'need_transportation_assistance' => 'はい、航空券予約に支援が必要です。',
'visa_assistance' => 'ビザ取得の支援',
'need_visa_assistance' => 'はい、ビザ取得に支援が必要です',
'visa_assistance_description' => '運営チームがビザの件にどのように対応したらよいか、ご記入ください（<strong>アラビア語</strong>または<strong>英語</strong>でお願いします）',

'title5' =>
'	   <p><strong>宿泊情報</strong></p>
	   <p>今回、2種類の宿泊形態をご提供できることになりました。ホテル、もしくはサン・マルク・カレッジ宿舎にご滞在いただけます。
ご登録の前に、<a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>ウィキマニア公式ウェブサイト</a>で宿泊先の所在、宿泊環境をよくお確かめください。</p>
',
'accommodation_hotel' => '希望する宿泊先',
'hotels_metropol' => 'メトロポール・ホテル (Metropol Hotel)（1泊60ドル）',
'hotels_delta' => 'デルタ・ホテル (Delta Hotel)（1泊30ドル）',
'hotels_dorms' => 'サン・マルク宿舎 (Saint Marc Dorms)（1泊10ドル）',

'accommodation' => '宿泊日程',
'night1' => '7月16日',
'night2' => '7月17日',
'night3' => '7月18日',
'night4' => '7月19日',
'night5' => '7月20日',
'room' => '希望するタイプ',
'room2' => 'ツイン',
'room4' => '4人部屋',
'room6' => '指定なし',

'title6' =>
'	   <p><strong>支払い</strong></p>
	   <p>（エジプトは含まれない）<a href="http://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">103の国・地域から</a>PayPal経由でお支払い可能です。もしくはアレクサンドリア運営チーム所有の銀行口座への振込によってもお支払いいただけます。注意: エジプト人の方はPayPalでお支払いいただけません。</p>
',

'pay_method' => '支払い種別',
'atm' => '銀行口座への送金',
'receipt' => '領収書',
'need_receipt' => 'はい、領収書が必要です。',
'receipt_title' => '宛名',
'receipt_address' => '住所',

'submit_notice' =>
'<li><strong>フォーム送信後に送信内容を確認できます。</strong></li>',
'submit' => 'フォームを送信する',
'reset' => 'フォーム入力内容を取り消す',

'confirm' => '確認',
'confirm_description' => 'フォームを送信する前に、データを正しく記入したか確認してください：',

'paypal' => 'PayPal で支払う',
'paypal_description' =>
'<p>PayPal で支払うには、"Buy Now" （いま支払う）ボタンを使って下さい。</p> ',
'paypal_failed' => 'PayPal での支払いを取り消す',
'paypal_failed_description' => '<p>下のフォームをもう一度記入して支払いを行えます。下記で説明する他の方法で支払うことも出来ます。</p>',
'paypal_successful' => 'PayPal での支払いに成功しました',
'paypal_successful_description' => '<p>ありがとうございます。料金の支払いを確認し、登録情報を調べた上で、のちほど結果をお知らせをいたします。</p>',
'atm' => '銀行振り込みで支払う',
'atm_description' => '
<p>登録料を下記の銀行口座（エジプト）へ振り込んでください。</p>
<ul class="atm-account">
<li>口座名: Bibliotheca Alexandrina</li>
<li>銀行: Commercial International Bank</li>
<li>支店名: Bibliotheca Alexandrina Branch</li>
<li>SWIFT BIC番号: CIBEEGCX041</li>
<li>ウィキマニアの口座番号（アメリカドル）: 41-8930006-6</li>
</ul>
<p><b>エジプト</b>ではPayPalが利用できないため、上記銀行に、以下の口座番号で、エジプトポンドでお支払い下さい:</p>
<ul class="atm-account">
<li>ウィキマニアの口座番号（エジプトポンド）: 41-8900019-5</li>
</ul>
<p>支払い後、電子的に発行された領収書をお名前・登録番号とともに、regwikimania2008 AT wikimedia.org へお送りください。3営業日以内にお返事いたします。また<a href="index.php?action=query" title="query the registration status">登録状況をオンライン登録情報案内で確認する</a>ことができます。</p>
'
);

$lang_messages = array(
'successful' => '登録完了',
'successful_description' =>
'<p>ウィキマニア2008へのご参加ありがとうございます！　ご登録を受け付けました。登録を確定するためには送金処理を済ませる必要がありますので、ご注意ください。

あなたの<strong>受付番号 (registration number)<strong>は以下に記載されています。番号をお控えの上、受付状況の確認や会議の際のご自身の情報の確認などにお使いください。
',
'cost' => '登録料金',
'wikimania_cost' => '会議: ',
'accommodation_cost' => '宿泊: ',
'other_cost' => 'その他: ',
'total_cost' => '合計: ',
'usd' => ' ドル',
'egp' => ' ポンド',
);

$lang_errors = array(
'repeat' => 'あなたと同じ名前と身分証明書 / パスポート番号で誰かが登録をしています。あなたが同じデータを二度送信したか、または登録ページを再読み込みした可能性があります。',
'not_input' => '$1が空白です。',
'not_input_completely' => '$1の記述は不十分です。',
'not_select' => '$1にチェックが入っていません。',
'not_select_whether' => '$1が記入されていません。',
'too_long' => '$1が長すぎます。最長で$2文字までです。',
'incorect' => '$1が正確ではありません。',
'wrong' => '$1が間違っています。',
'visa_assistance_incomplete' => 'ビザ取得支援についての情報が空白です。',
'wrong_query' => '名前または登録番号が間違っています。',
'paypal_unavailable' => 'あなたが選択した国 / 地域は、PayPalでは扱っていません。'
);

$lang_query = array(
'unique_code' => '登録ナンバー',
'submit' => 'クエリ',
'your_status' => '$1さんの登録状況です：',
'received_money' => '登録料金（支払い済み / 支払い待ち）：',
'lack' => 'まだ受け取っていません',
'enough' => '支払い済みです',
'too_much' => '支払額が超過しています',
'accepted' => 'あなたの登録は<strong>確認されました</strong>。',
'rejected' => 'あなたの登録は<strong>却下されました</strong>。',
'not_yet' => 'あなたの登録は<strong>確認されていません</strong>。'

);


$lang_countries = array(
	'af' => 'Afghanistan',
	'ax' => 'Aland Islands',
	'al' => 'Albania',
	'dz' => 'Algeria',
	'as' => 'American Samoa',
	'ad' => 'Andorra',
	'ao' => 'Angola',
	'ai' => 'Anguilla',
	'aq' => 'Antarctica',
	'ag' => 'Antigua and Barbuda',
	'ar' => 'Argentina',
	'am' => 'Armenia',
	'aw' => 'Aruba',
	'au' => 'Australia',
	'at' => 'Austria',
	'az' => 'Azerbaijan',
	'bs' => 'Bahamas',
	'bh' => 'Bahrain',
	'bd' => 'Bangladesh',
	'bb' => 'Barbados',
	'by' => 'Belarus',
	'be' => 'Belgium',
	'bz' => 'Belize',
	'bj' => 'Benin',
	'bm' => 'Bermuda',
	'bt' => 'Bhutan',
	'bo' => 'Bolivia',
	'ba' => 'Bosnia and Herzegovina',
	'bw' => 'Botswana',
	'bv' => 'Bouvet Island',
	'br' => 'Brazil',
	'io' => 'British Indian Ocean Territory',
	'bn' => 'Brunei Darussalam',
	'bg' => 'Bulgaria',
	'bf' => 'Burkina Faso',
	'mm' => 'Burma (Myanmar)',
	'bi' => 'Burundi',
	'kh' => 'Cambodia',
	'cm' => 'Cameroon',
	'ca' => 'Canada',
	'cv' => 'Cape Verde',
	'ky' => 'Cayman Islands',
	'cf' => 'Central African Republic',
	'td' => 'Chad',
	'cl' => 'Chile',
	'hk' => 'Hong Kong SAR',
	'cn' => 'People\'s Republic of China',
	'tw' => 'Republic of China (Taiwan)',
	'cx' => 'Christmas Island',
	'cc' => 'Cocos (keeling) Islands',
	'co' => 'Colombia',
	'km' => 'Comoros',
	'cg' => 'Congo',
	'cd' => 'Congo\, The Democratic Republic of the',
	'ck' => 'Cook Islands',
	'cr' => 'Costa Rica',
	'ci' => 'Cote D\'ivoire',
	'hr' => 'Croatia',
	'cu' => 'Cuba',
	'cy' => 'Cyprus',
	'cz' => 'Czech Republic',
	'dk' => 'Denmark',
	'dj' => 'Djibouti',
	'dm' => 'Dominica',
	'do' => 'Dominican Republic',
	'ec' => 'Ecuador',
	'eg' => 'Egypt',
	'sv' => 'El Salvador',
	'gq' => 'Equatorial Guinea',
	'er' => 'Eritrea',
	'ee' => 'Estonia',
	'et' => 'Ethiopia',
	'fk' => 'Falkland Islands (malvinas)',
	'fo' => 'Faroe Islands',
	'fj' => 'Fiji',
	'fi' => 'Finland',
	'fr' => 'France',
	'gf' => 'French Guiana',
	'pf' => 'French Polynesia',
	'tf' => 'French Southern Territories',
	'ga' => 'Gabon',
	'gm' => 'Gambia',
	'ge' => 'Georgia',
	'de' => 'Germany',
	'gh' => 'Ghana',
	'gi' => 'Gibraltar',
	'gr' => 'Greece',
	'gl' => 'Greenland',
	'gd' => 'Grenada',
	'gp' => 'Guadeloupe',
	'gu' => 'Guam',
	'gt' => 'Guatemala',
	'gn' => 'Guinea',
	'gw' => 'Guinea-Bissau',
	'gy' => 'Guyana',
	'ht' => 'Haiti',
	'hm' => 'Heard Island and Mcdonald Islands',
	'va' => 'Holy See (Vatican City)',
	'hn' => 'Honduras',
	'hu' => 'Hungary',
	'is' => 'Iceland',
	'in' => 'India',
	'id' => 'Indonesia',
	'ir' => 'Iran, Islamic Republic of',
	'iq' => 'Iraq',
	'ie' => 'Ireland',
	'il' => 'Israel',
	'it' => 'Italy',
	'jm' => 'Jamaica',
	'jp' => 'Japan',
	'jo' => 'Jordan',
	'kz' => 'Kazakhstan',
	'ke' => 'Kenya',
	'ki' => 'Kiribati',
	'kp' => 'Democratic People\'s Republic of Korea',
	'kr' => 'Republic of Korea',
	'kw' => 'Kuwait',
	'kg' => 'Kyrgyzstan',
	'la' => 'Lao People\'s Democratic Republic',
	'lv' => 'Latvia',
	'lb' => 'Lebanon',
	'ls' => 'Lesotho',
	'lr' => 'Liberia',
	'ly' => 'Libyan Arab Jamahiriya',
	'li' => 'Liechtenstein',
	'lt' => 'Lithuania',
	'lu' => 'Luxembourg',
	'mo' => 'Macao',
	'mk' => 'Macedonia, The Former Yugoslav Republic of',
	'mg' => 'Madagascar',
	'mw' => 'Malawi',
	'my' => 'Malaysia',
	'mv' => 'Maldives',
	'ml' => 'Mali',
	'mt' => 'Malta',
	'mh' => 'Marshall Islands',
	'mq' => 'Martinique',
	'mr' => 'Mauritania',
	'mu' => 'Mauritius',
	'yt' => 'Mayotte',
	'mx' => 'Mexico',
	'fm' => 'Micronesia, Federated States of',
	'md' => 'Moldova, Republic of',
	'mc' => 'Monaco SAR',
	'mn' => 'Mongolia',
	  'me' => 'Montenegro',
	'ms' => 'Montserrat',
	'ma' => 'Morocco',
	'mz' => 'Mozambique',
	'na' => 'Namibia',
	'nr' => 'Nauru',
	'np' => 'Nepal',
	'nl' => 'Netherlands',
	'an' => 'Netherlands Antilles',
	'nc' => 'New Caledonia',
	'nz' => 'New Zealand',
	'ni' => 'Nicaragua',
	'ne' => 'Niger',
	'ng' => 'Nigeria',
	'nu' => 'Niue',
	'nf' => 'Norfolk Island',
	'mp' => 'Northern Mariana Islands',
	'no' => 'Norway',
	'om' => 'Oman',
	'pk' => 'Pakistan',
	'pw' => 'Palau',
	'ps' => 'Palestinian Territory',
	'pa' => 'Panama',
	'pg' => 'Papua New Guinea',
	'py' => 'Paraguay',
	'pe' => 'Peru',
	'ph' => 'Philippines',
	'pn' => 'Pitcairn',
	'pl' => 'Poland',
	'pt' => 'Portugal',
	'pr' => 'Puerto Rico',
	'qa' => 'Qatar',
	're' => 'Reunion',
	'ro' => 'Romania',
	'ru' => 'Russian Federation',
	'rw' => 'Rwanda',
	'sh' => 'Saint Helena',
	'kn' => 'Saint Kitts and Nevis',
	'lc' => 'Saint Lucia',
	'pm' => 'Saint Pierre and Miquelon',
	'vc' => 'Saint Vincent and the Grenadines',
	'ws' => 'Samoa',
	'sm' => 'San Marino',
	'st' => 'Sao Tome and Principe',
	'sa' => 'Saudi Arabia',
	'sn' => 'Senegal',
	'rs' => 'Serbia',
	'sc' => 'Seychelles',
	'sl' => 'Sierra Leone',
	'sg' => 'Singapore',
	'sk' => 'Slovakia',
	'si' => 'Slovenia',
	'sb' => 'Solomon Islands',
	'so' => 'Somalia',
	'za' => 'South Africa',
	'gs' => 'South Georgia and the South Sandwich Islands',
	'es' => 'Spain',
	'lk' => 'Sri Lanka',
	'sd' => 'Sudan',
	'sr' => 'Suriname',
	'sj' => 'Svalbard and Jan Mayen',
	'sz' => 'Swaziland',
	'se' => 'Sweden',
	'ch' => 'Switzerland',
	'sy' => 'Syrian Arab Republic',
	'tj' => 'Tajikistan',
	'tz' => 'Tanzania, United Republic of',
	'th' => 'Thailand',
	'tl' => 'Timor-leste',
	'tg' => 'Togo',
	'tk' => 'Tokelau',
	'to' => 'Tonga',
	'tt' => 'Trinidad and Tobago',
	'tn' => 'Tunisia',
	'tr' => 'Turkey',
	'tm' => 'Turkmenistan',
	'tc' => 'Turks and Caicos Islands',
	'tv' => 'Tuvalu',
	'ug' => 'Uganda',
	'ua' => 'Ukraine',
	'ae' => 'United Arab Emirates',
	'gb' => 'United Kingdom',
	'us' => 'United States',
	'um' => 'United States Minor Outlying Islands',
	'uy' => 'Uruguay',
	'uz' => 'Uzbekistan',
	'vu' => 'Vanuatu',
	've' => 'Venezuela',
	'vn' => 'Viet Nam',
	'vg' => 'Virgin Islands, British',
	'vi' => 'Virgin Islands, U.S.',
	'wf' => 'Wallis and Futuna',
	'eh' => 'Western Sahara',
	'ye' => 'Yemen',
	'zm' => 'Zambia',
	'zw' => 'Zimbabwe'
);


