<?php

$lang_register_form = array(
'registration_title' => 'ثبت نام در ویکی‌مانیا ۲۰۰۸',
'select' => 'لطفاً انتخاب کنید',
'query' => 'پیگیری وضعیت ثبت نام',
'query_title' => 'در این قسمت می‌توانید وضعیت ثبت نام در ویکی‌مانیا ۲۰۰۸ را پیگیری کنید.',
'correction' => 'اطلاعات شما ثبت نشده چرا که اشتباهی در آن وجود دارد.',

'legend1' => 'اطلاعات شخصی',
'title1' =>
'        <p><div align="right"><strong>اطلاعات شخصی</strong></div></div></p>
         <p><div align="right">لطفاً اطلاعات شخصی خود را به درستی در فرم وارد کنید.</div></div></p>
',
'egy' => 'آیا شما شهروند جمهوری عربی مصر هستید؟',
'egy1' => 'بله، هستم. (لطفاً شماره شناسایی ملی و نام خودتان را در قسمت‌های زیر وارد کنید)',
'egy0' => 'خیر، نیستم. (لطفاً شماره گذرنامه و نام خود را نظیر آن چه در گذرنامه آمده در قسمت‌های زیر وارد کنید)',
'surname' => 'نام خانوادگی',
'given_name' => 'نام',
'sex' => 'جنسیت',
'sex1' => 'مرد',
'sex2' => 'زن',
'sex3' => 'نمی‌خواهم بگویم',
'id' => 'شمارهٔ شناسنامه / گذرنامه',
'country' => 'کشور / منطقه',
'city' => 'استان / شهر',
'birthday' => 'تاریخ تولد (dd/mm/yyyy)',
'organization' => 'سازمان',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'ژانویه', 'فوریه', 'مارس', 'آوریل', 'مه', 'ژوئن', 'ژوئیه', 'اوت', 'سپتامبر', 'اکتبر', 'نوامبر', 'دسامبر' ),
'day' => '',

'title2' =>
'        <p><div align="right"><strong>توانایی‌های زبانی</strong></div></div></p>',
'langn' => 'زبان مادری',
'lang' => 'سطح مهارت',
'select_lang' => 'زبان را انتخاب کنید',
'select_level' => 'سطح مهارت را انتخاب کنید',

'lang_level1' => '۱ (مقدماتی)',
'lang_level2' => '۲ (متوسط)',
'lang_level3' => '۳ (پیشرفته)',
'lang_level4' => '۴ (در حد زبان مادری)',

'lang1' => 'زبان ۱',
'lang2' => 'زبان ۲',
'lang3' => 'زبان ۳',

'lang1_level' => 'سطح مهارت در زبان ۱',
'lang2_level' => 'سطح مهارت در زبان ۲',
'lang3_level' => 'سطح مهارت در زبان ۳',

'title3' =>
'        <p><div align="right"><strong>پروژه و نشانی پست الکترونیکی در ویکی‌مدیا</strong>
         <br>
           پست الکترونیکی شما تنها برای ثبت نام و تماس‌های ضروری دربارهٔ ویکی‌مانیا ۲۰۰۸ استفاده خواهد شد.
         </div></p>
',
'wiki_id' => 'حساب کاربری در پروژه دلخواه ویکی‌مدیا',
'email' => 'پست الکترونیکی شما',


'legend2' => 'شرکت کردن',
'title4' =>
'        <p><div align="right"><strong>شرکت کردن، اطلاعات نشان فردی و سایر موارد</strong></div></p>
         <p><div align="right">برای مرتب کردن بهتر کارها در زمان اسکان، نشست‌ها و خدمات مرتبط، لطفاً نظر خود را در مورد موارد زیر به ما بگویید.</div></p>
',
'join_date' => 'تاریخ شرکت کردن',
'join1' => '۱۷ ژوئیه',
'join2' => '۱۸ ژوئیه',
'join3' => '۱۹ ژوئیه',
'topic' => 'نشست‌های انتخابی',
'topic1' => 'جامعه‌های ویکی‌مدیا',
'topic2' => 'محتوای آزاد',
'topic3' => 'زیرساخت فنی',
'topic4' => 'پیگیری علمی',
'showname' => 'اطلاعات نشان فردی',
'custom_showname' => 'نام خودمانی انتخابی برای نشان فردی',
'showname1' => 'نام',
'showname2' => 'حساب کاربری ویکی‌مدیا',
'showname3' => 'سازمان',
'showname4' => 'سایر',
'size' => 'اندازه تی-شرت',
'food' => 'رژیم غذایی',
'food0' => '-',
'food1' => 'بدون گوشت',
'food2' => 'گیاه خوار (سبک آسیایی)',
'food3' => 'گیاه خوار (سبک غربی، تخم مرغ و شیر می‌خورم)',
'food4' => 'حلال خوار',
'food5' => 'سایر',
'food_other' => 'رژیم غذایی ذکر شده',
'allegric' => 'حساسیت (آلرژی)',
'transportation_assistance' => 'کمک بلیط‌های پروازها',
'need_transportation_assistance' => ' بله ،من به کمک شما در رزرو بلیط پروازم نیاز دارم.',
'visa_assistance' => 'کمک برای روادید',
'need_visa_assistance' => 'بله، نیاز به کمک برای دریافت روادید دارم',
'visa_assistance_description' => 'لطفاً مشخیص کنید که تیم سازمانی چگونه می‌تواند به شما در اخذ روادید کمک کند. (به زبان <strong>عربی</strong> یا <strong>انگلیسی</strong> بنویسید)',

'title5' =>
'         <p><div align="right"><strong>اسکان</strong></div></p>
         <p><div align="right">ما دو گزینه برای اسکان پیش روی شما گذاشته‌ایم. شما می‌توانید در یک هتل اقامت کنید، یا در خوابگاه‌های کالج سنت-مارک باشید.
    لطفاً جزئیات بیشتر را در <a href=http://wikimania2008.wikimedia.org/wiki/Accommodation>وبگاه رسمی ویکی‌مانیا</a> ببینید تا پیش از ثبت نام از مکان دقیق و خصوصیات هر یک از دو گزینه آگاه شوید.</div></p>
',
'accommodation_hotel' => 'هتل انتخابی',
'hotels_metropol' => 'هتل متروپول (۶۰ دلار برای هر شب)',
'hotels_delta' => 'هتل دلتا (۳۰ دلار برای هر شب)',
'hotels_dorms' => 'خوابگاه سنت-مارک (۱۰ دلار برای هر شب)',

'accommodation' => 'تاریخ اقامت',
'night1' => '۱۶ ژوئیه',
'night2' => '۱۷ ژوئیه',
'night3' => '۱۸ ژوئیه',
'night4' => '۱۹ ژوئیه',
'night5' => '۲۰ ژوئیه',
'room' => 'اتاق انتخابی',
'room2' => 'دو نفره',
'room4' => 'چهار نفره',
'room6' => 'فرقی نمی‌کند',

'title6' =>
'         <p><div align="right"><strong>پرداخت</strong></div></p>
         <p><div align="right">در <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_display-approved-signup-countries-outside" title="PayPal Worldwide">۱۰۳ منطقه / کشور</a> (شامل مصر نمی‌شود) شما می‌توانید از حساب PayPal خود پرداخت را انجام دهید یا کارت اعتباری خود را از طریق PayPal استفاده کنید، یا می‌توانید از Remittance و پرداخت مستقیم به حساب بانکی متعلق به تیم سازمانی ساکن در اسکندریه پرداخت را انجام دهید. توجه: اگر اهل مصر هستید نمی‌توانید از روش PayPal استفاده کنید</div></p>
',

'pay_method' => 'روش پرداخت',
'atm' => 'پرداخت از طریق حساب بانکی',
'receipt' => 'رسید',
'need_receipt' => 'بله، من یک رسید چاپی می‌خواهم.',
'receipt_title' => 'عنوان',
'receipt_address' => 'نشانی پستی',

'submit_notice' =>
'<li><strong>بعد از این که فرم را ارسال کنید، هنوز فرصت دارید که اطلاعات را بازبینی کنید.</strong></li>',
'submit' => 'ارسال',
'reset' => 'از نو',

'confirm' => 'بازبینی',
'confirm_description' => 'قبل از این که فرم را ارسال کنید، لطفاً از درستی اطلاعات زیر اطمینان حاصل کنید:',

'paypal' => 'پرداخت از طریق PayPal',
'paypal_description' =>
'<p><div align="right">لطفاً دکمهٔ «Buy Now» را بزنید تا از طریق PayPal پرداخت کنید</div></p> ',
'paypal_failed' => 'لغو پرداخت از طریق PayPal',
'paypal_failed_description' => '<p><div align="right">شما می‌توانید یک بار دیگر از طریق فرم زیر تلاش کنید، یا این که یکی دیگر از روش‌های پرداخت که در زیر توضیح داده شده را استفاده کنید.</div></p>',
'paypal_successful' => 'پرداخت از طریق PayPal موفقیت آمیز بود',
'paypal_successful_description' => '<p><div align="right">Thank you! We will notify you the result after we receive the payment and review your registration info.</div></p>',
'atm' => 'پرداخت از طریق حساب بانکی',
'atm_description' => '
<p><div align="right">لطفاً اطلاعات بانکی زیر را در مصر استفاده کنید تا هزینهٔ ثبت نام / اسکان را پرداخت نمایید:</div></p>
<ul class="atm-account">
<li>نام حساب: Bibliotheca Alexandrina</li>
<li>بانک: Commercial International Bank</li>
<li>کد شعبه: Bibliotheca Alexandrina Branch</li>
<li>کد SWIFT BIC: CIBEEGCX041</li>
<li>شماره حساب ویکی‌مانیا (پرداخت دلاری): 41-8930006-6</li>
</ul>
<p><div align="right">به خاطر محدودیت PayPal در <b>مصر</b>، شما تنها می‌توانید پرداخت را از طریق بانک انجام دهید؛ لطفاً اطلاعات بانکی فوق را با شماره حساب زیر برای این منظور استفاده کنید:</div></p>
<ul class="atm-account">
<li>شماره حساب ویکی‌مانیا (EGP): 41-8900019-5</li>
</ul>
<p><div align="right">همچنین لطفاً رسید پرداخت را به شکل الکترونیکی به همراه نام و شماره ثبت نام خود به نشانی regwikimania2008 AT wikimedia.org بفرستید؛ ما ظرف سه روز کاری به شما پاسخ خواهیم داد. شما همچنین می‌توانید <a href="index.php?action=query" title="query the registration status">وضعیت ثبت‌نام خود را به صورت برخط پیگیری کنید</a>.</div></p>
'
);

$lang_messages = array(
'successful' => 'ثبت نام کامل شد',
'successful_description' =>
'<p><div align="right">از این که به ویکی‌مانیا ۲۰۰۸ پیوستید متشکریم! فرم ثبت نام شما ارسال شده‌است. لطفاً توجه داشته باشید که برای تایید ثبت نام باید روال پرداخت هزینه‌ها را کامل کنید.

<strong>شماره ثبت</strong> شما در زیر نمایش داده می‌شود. لطفاً این شماره را به خاطر بسپارید تا بعداً برای پیگیری ثبت نام یا تایید هویت خودتان از آن استفاده نمایید.
',
'cost' => 'هزینهٔ ثبت نام',
'wikimania_cost' => 'کنفرانس: ',
'accommodation_cost' => 'اسکان: ',
'other_cost' => 'سایر هزینه‌ها: ',
'total_cost' => 'جمع کل: ',
'usd' => ' دلار آمریکا',
'egp' => ' پوند مصر',
);

$lang_errors = array(
'repeat' => 'فرد دیگری با همین نام و شماره شناسنامه / گذرنامه ثبت نام کرده‌است. امکان دارد که شما فرم را دو بار ارسال کرده باشید یا صفحه را ثبت نام را از نو کرده باشید..',
'not_input' => '$1 خالی است.',
'not_input_completely' => '$1 کامل نیست.',
'not_select' => '$1 علامت نخورده است.',
'not_select_whether' => '$1 مشخص نشده‌است.',
'too_long' => '$1 خیلی طولانی است؛ حداکثر طول مجاز $2 است.',
'incorect' => '$1 درست نیست.',
'wrong' => '$1 اشتباه است.',
'visa_assistance_incomplete' => 'اطلاعات مربوط به کمک برای روادید خالی است.',
'wrong_query' => 'نام یا شماره ثبت اشتباه.',
'paypal_unavailable' => 'کشور / منطقه‌ای که انتخاب کردید توسط PayPal پشتیبانی نمی‌شود.'
);

$lang_query = array(
'unique_code' => 'شماره ثبت',
'submit' => 'پیگیری',
'your_status' => 'سلام، $1، در این قسمت وضعیت ثبت نام خود را می‌بینید:',
'received_money' => 'هزینهٔ ثبت نام (دریافتی / مورد انتظار):',
'lack' => 'دریافت نشده',
'enough' => 'قبلاً پرداخت شده',
'too_much' => 'شما زیاد پرداخت کرده‌اید',
'accepted' => 'ثبت نام شما <strong>تایید شده‌است</strong>.',
'rejected' => 'ثبت نام شما <strong>رد شده‌است</strong>.',
'not_yet' => 'ثبت نام شما <strong>تایید نشده‌است</strong>.'

);

 $lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

?>
