Document: oggvideotools
Title: Debian oggvideotools Manual
Author: <insert document author here>
Abstract: This manual describes what oggvideotools is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/oggvideotools/oggvideotools.sgml.gz

Format: postscript
Files: /usr/share/doc/oggvideotools/oggvideotools.ps.gz

Format: text
Files: /usr/share/doc/oggvideotools/oggvideotools.text.gz

Format: HTML
Index: /usr/share/doc/oggvideotools/html/index.html
Files: /usr/share/doc/oggvideotools/html/*.html
