<?php

$lang_register_form = array(
'registration_title' => 'Wikimania 2011 Registration',
'select' => 'Please select',
'query' => 'Query your registration status',
'query_title' => 'You can query the registration status for Wikimania 2011 in here.',
'correction' => 'Your information is not submitted due to some errata in the form.',

'legend1' => 'Personal information',
'title1' =>
'<p><strong>Personal identification data</strong></p>',
'surname' => 'Last name',
'given_name' => 'First name',
'sex' => 'Gender', 
'sex1' => 'Male',
'sex2' => 'Female',
'sex3' => 'Decline to state',
'passport' => 'Passport number', 
'passport_valid' => 'Passport valid until (dd/mmm/yyyy)<br><small>Your passport has to be valid for 6 months</small>',
'passport_issued' => 'Place where passport was issued',
'country' => 'Country of residence', 
'birthday' => 'Date of Birth (dd/mmm/yyyy)',
'year1' => '', 
'year' => '', 
'month' => '', 
'months' => array(NULL, 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'),
'day' => '', 
'title2' =>
'        <p><strong>Linguistic abilities</strong></p>',
'langn' => 'Mother language', 
'lang' => 'Additional languages', 
'select_lang' => 'Select the language',
'select_level' => 'Select the skill level',

'lang_level1' => '1 (Basic)',
'lang_level2' => '2 (Intermediate)',
'lang_level3' => '3 (Advanced)',
'lang_level4' => '4 (Near native)',

'lang1' => 'Language 1',
'lang2' => 'Language 2',
'lang3' => 'Language 3',

'lang1_level' => 'Skill level for Language 1',
'lang2_level' => 'Skill level for Language 2',
'lang3_level' => 'Skill level for Language 3',

'title3' => 
'<p><strong>Wikimedia project and e-mail account</strong></p>
<p>Your e-mail information will be used for registration and urgent notification on Wikimania 2011 only.
</p>
', 
'wiki_id' => 'Wikimedia project username', 
'email' => 'Your e-mail', 

'legend2' => 'Participation',
'title4' =>
'<p><strong>Participation, badge information and miscellaneous</strong></p>',
'join_date' => 'Participation days',
'join1' => 'Tuesday, August 2nd, 2011',
'join2' => 'Wednesday, August 3rd, 2011',
'join3' => 'Thursday, August 4th, 2011',
'join4' => 'Friday, August 5th, 2011',
'join5' => 'Saturday, August 6th, 2011',
'join6' => 'Sunday, August 7th, 2011',
'join7' => 'Monday, August 8th, 2011',
'showname' => 'Badge information',
'custom_showname' => 'Preferred nickname on badge',
'showname1' => 'Name',
'showname2' => 'Wikimedia account',
'showname3' => 'Additional information:',
'size' => 'T-shirt size', 
'food' => 'Dietary restriction<br><small>All food served during the conference will be kosher.</small>',
'food0' => 'None',
'food1' => 'Vegetarian',
'food2' => 'Halal',
'food_other' => 'Other:',
 
'title_visa' => 
'<p><strong>Visa assistance</strong></p>
<p>If your passport is issued by <a href=http://wikimania2011.wikimedia.org/wiki/Visas#Visa_required>a country for which an entry visa to Israel is required</a>, please fill out this section so that the organizers can pass your details to the Israeli Ministry of Foreign Affairs.', 
'need_visa_assistance' => 'Yes, I require an entry visa for Israel',
'visa_assistance' => 'Visa assistance',
'visa_assistance_description' => 'Any special request related to visa assistance (in <strong>English</strong>)',

'title5' =>
'<p><strong>Accommodation</strong></p>
<p>You can stay in a hotel or in the dormitories. 
Please refer to the <a href=http://wikimania2011.wikimedia.org/wiki/Accommodation>accommodation page</a> for exact <b>prices</b>, locations and other details.</p>',
'accommodation_hotel' => 'Preferred accommodation<br><b><small>(<a href=http://wikimania2011.wikimedia.org/wiki/Accommodation onClick="return popup(this, \'prices\')">Prices</a>)</small></b>',
'hotel1' => 'Dorm room',
'hotel2' => 'Ganei Dan',
'hotel3' => 'Marom',
'hotel4' => 'Har HaCarmel',
'hotel5' => 'Nof',
'hotel6' => 'Dan Panorama',
'hotel7' => 'Crown Plaza',
'hotel8' => 'Colony',
'hotel9' => 'Galery',
'hotel3stars' => 'Three star hotels',
'hotel4stars' => 'Four star hotels',
'hotel5stars' => 'Five star hotels',
'hotelboutique' => 'Boutique hotels',

'accommodation' => 'Nights for which accommodation is needed', 
'night1' => 'Monday, August 1st, 2011',
'night2' => 'Tuesday, August 2nd, 2011',
'night3' => 'Wednesday, August 3rd, 2011',
'night4' => 'Thursday, August 4th, 2011',
'night5' => 'Friday, August 5th, 2011',
'night6' => 'Saturday, August 6th, 2011',
'night7' => 'Sunday, August 7th, 2011',
'night8' => 'Monday, August 8th, 2011',
'room' => 'Preferred room',  
'room1' => 'Single occupancy',
'room2' => 'Twin/double occupancy with same-gender partner randomly selected by organizers',
'room3' => 'Double occupancy with specified partner (enter full name):',
'room_requests' => 'Special requests related to accommodation (e.g. room for the disabled)',
'room_partner' => 'Room partner',
'title6' =>
'<p><strong>Payment</strong></p>
<p>Payment for conference fees and accommodation is done through PayPal at the time of registration. <br></p>',
'title7' =>
'<p><strong>CAPTCHA</strong></p><p>To make sure you are a human being and not a bot, please complete this CAPTCHA query.</p>',
'discount_code' => 'Discount code<br><small>If you got a discount code, please enter it here.</small>',
'submit_notice' =>
'<li><strong>After you submit the form, you still have a chance to verify your registration.</strong></li>',
'asterix_meaning' =>
'<li><strong>An asterix next to a field name means you must fill it.</strong></li>',
'submit' => 'Submit',
'reset' => 'Reset',

'confirm' => 'Verification',
'confirm_description' => 'Before you submit the form, please make sure you have filled the data correctly:',

'paypal' => 'Pay via PayPal',
'paypal_description' =>
'<p>Please use the "Pay Now" button below to proceed to pay <b>now</b> via PayPal!</p> ',
'paypal_failed' => 'Cancel the PayPal payment',
'paypal_failed_description' => '<p>You can try again by filling the form below, or you can pay at another time by transferring the funds via Paypal to <b>finance@wikimedia.org.il</b>, but be sure to add your registration number in the item description field.</p>',
'paypal_successful' => 'Payment via PayPal successful',
'paypal_successful_description' => '<p>Thank you! We will notify you the result after we receive the payment and review your registration info.</p>',

'hackingdays' => 'Developer meetings and other meetups',
'maindays' => 'Main days',
'tourdays' => 'Tour day',
'color' => 'T-shirt Color',
'white' => 'White',
'black' => 'Black',
'nationality' => 'Passport issued by', 
'countryofbirth' => 'Country of birth', 
'homeaddress' => 'Home address',
'picktour' => 'Preferred tour destination',
'tour0' => 'No tour preference',
'tour1' => 'Nazareth and the Galilee',
'tour2' => 'Jerusalem',
'tour3' => 'Acre (Acco)',
'tour4' => 'The Baha\'i Gardens',
'tour5' => 'Druze Villages',
'main_date' => 'Main conference day',
'captcha' => 'CAPTCHA information'
);


$lang_messages = array(
'successful' => 'Registration complete',
'successful_description' => 
'<p>Thank you for joining Wikimania 2011! Your registration form has been submitted. Please note that you need to complete the payment process so the registration can be confirmed.

Your <strong>registration number</strong> will be shown below. Please take a note of the number for it will be used for querying the registration status and to confirm your identity in the future.
',
'cost' => 'Registration fee: ',
'attendance_cost' => 'Conference: ',
'accommodation_cost' => 'Accommodation: ',
'vat_cost' => 'VAT: ',
'other_cost' => 'Other expense(s): ',
'total_cost' => 'Total: ',
'usd' => ' USD',
);

$lang_errors = array(
'repeat' => 'Someone has registered with the same name and e-mail address. It\'s possible you have submitted twice or you have refreshed the registration page.',
'not_input' => '$1 is empty.',
'not_input_completely' => '$1 is not complete.',
'not_select' => '$1 is not checked.',
'not_select_whether' => '$1 is not been specified.',
'too_long' => '$1 is too long, the allowed length is $2.',
'incorrect' => '$1 is not correct.',
'wrong' => '$1 is wrong.',
'visa_assistance_incomplete' => 'Visa assistance information is empty.',
'wrong_query' => 'Wrong name or registration number.',
'paypal_unavailable' => 'The country / region you selected is not supported by PayPal.'
);

$lang_query = array(
'query_title' => 'Registration status summary and proof of payment received',
'unique_code' => 'Registration number:',
'submit' => 'Query',
'your_status' => 'Welcome, $1, here is the status of your registration:',
'received_money' => 'Wikimedia Israel confirms that we received the following fee out of this expected fee for attending Wikimania 2011 in Haifa, Israel:',
'lack' => 'Still not paid in full',
'enough' => 'Paid in full',
'too_much' => 'Paid too much',
'accepted' => 'Your registration has been <strong>confirmed</strong>.',
'rejected' => 'Your registration has been <strong>rejected</strong>.',
'not_yet' => 'Your registration has been <strong>received</strong>. Final letter with more details will follow closer to the conference.'
);

$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
      'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

?>
