<?php
$lang_register_form = array(
'registration_title' => 'רישום לוויקימניה 2011',
'select' => 'נא לבחור',
'query' => 'בדיקת מצב הרישום',
'query_title' => 'כאן ניתן לבדוק את מצב הרישום לוויקימניה 2011',
'correction' => 'המידע לא נקלט עקב טעויות בטופס הרישום',

'legend1' => 'פרטים אישיים',
'title1' =>
'<p><strong>פרטי זיהוי אישיים</strong></p>',
'surname' => 'שם משפחה',
'given_name' => 'שם פרטי',
'sex' => 'מין',
'sex1' => 'זכר',
'sex2' => 'נקבה',
'sex3' => 'מעדיף לא לציין',
'passport' => 'מספר דרכון',
'passport_valid' => 'דרכון בתוקף עד (יום/חודש/שנה)',
'passport_issued' => 'מקום הוצאת הדרכון',
'country' => 'ארץ מגורים',
'birthday' => 'תאריך לידה (יום/חודש/שנה/)',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'ינואר', 'פברואר', 'מרץ', 'אפריל', 'מאי', 'יוני', 'יולי', 'אוגוסט', 'ספטמבר', 'אוקטובר', 'נובמבר', 'דצמבר' ),
'day' => '',

'title2' => '<p><strong>כישורי שפה</strong></p>',
'langn' => 'שפת אם',
'lang' => 'רמת השליטה',
'select_lang' => 'בחירת השפה',
'select_level' => 'בחירת רמת השליטה',

'lang_level1' => '1 (בסיסית)',
'lang_level2' => '2 (בינונית)',
'lang_level3' => '3 (מתקדמת)',
'lang_level4' => '4 (קרובה לשפת אם)',

'lang1' => 'שפה 1',
'lang2' => 'שפה 2',
'lang3' => 'שפה 3',

'lang1_level' => 'רמת שליטה לשפה 1',
'lang2_level' => 'רמת שליטה לשפה 2',
'lang3_level' => 'רמת שליטה לשפה 3',

'title3' =>
'<p><strong>שם משתמש במיזמי ויקימדיה וכתובת דוא"ל</strong></p>
<p>המידע לגבי הדוא"ל ישמש אך ורק לצורכי הרישום ולהודעות דחופות בנוגע לוויקימניה 2011.</p>',
'wiki_id' => 'שם משתמש במיזם ויקימדיה ',
'email' => 'כתובת דוא"ל',

'legend2' => 'השתתפות',
'title4' =>
'<p><strong>השתתפות, פרטי התג ושונות</strong></p>',
'join_date' => 'ימי השתתפות בכנס',
'join1' => 'יום שלישי, 2 באוגוסט 2011',
'join2' => 'יום רביעי, 3 באוגוסט 2011',
'join3' => 'יום חמישי, 4 באוגוסט 2011',
'join4' => 'יום שישי, 5 באוגוסט 2011',
'join5' => 'יום שבת, 6 באוגוסט 2011',
'join6' => 'יום ראשון, 7 באוגוסט 2011',
'join7' => 'יום שני, 8 באוגוסט 2011',

'showname' => 'מידע על-גבי התג',
'custom_showname' => 'הכינוי המועדף על-גבי התג',
'showname1' => 'שם',
'showname2' => 'שם משתמש בוויקימדיה',
'showname3' => 'מידע נוסף:',
'size' => 'מידת החולצה',
'food' => 'מגבלות תזונה<br><small>כל המזון שיוגש במהלך הכנס יהיה כשר</small>',
'food0' => 'אין',
'food1' => 'צמחוני',
'food2' => 'בשר חלאל למוסלמים',
'food_other' => 'מגבלת תזונה אחרת:',

'title_visa' =>
'<p><strong>סיוע בהנפקת אשרת כניסה</strong></p>
<p>אם הינכם זקוקים לעזרה מהמארגנים בהנפקת אשרת כניסה לישראל, אנא מלאו את החלק הזה.',
'visa_assistance' => 'עזרה בהנפקת אשרת כניסה',
'need_visa_assistance' => 'כן, אני זקוק לעזרה מהמארגנים בהנפקת אשרת כניסה לישראל',
'visa_assistance_description' => 'בקשות מיוחדות הנוגעות להנפקת אשרת כניסה',
'title5' =>
'<p><strong>סידורי לינה</strong></p>
 לפרטים מלאים על מחירים, מיקום ומפרט בכל אחת מהאפשרויות, אנא עיינו <a href=http://wikimania2011.wikimedia.org/w/index.php?title=Accommodation/he&uselang=he&rtl=1>בדף על אפשרויות הלינה</a>.</p>
',
'accommodation_hotel' => 'אפשרות הלינה המועדפת<br><b><small>(<a href=http://wikimania2011.wikimedia.org/w/index.php?title=Accommodation/he&uselang=he&rtl=1 onClick="return popup(this, \'prices\')">מחירים</a>)</small></b>',
'hotel1' => 'חדר מעונות',
'hotel2' => 'גני דן',
'hotel3' => 'מרום',
'hotel4' => 'הר הכרמל',
'hotel5' => 'נוף',
'hotel6' => 'דן פנורמה',
'hotel7' => 'קראון פלזה',
'hotel8' => 'קולוני',
'hotel9' => 'גלרי',
'hotel3stars' => 'מלונות שלושה כוכבים',
'hotel4stars' => 'מלונות ארבעה כוכבים',
'hotel5stars' => 'מלונות חמישה כוכבים',
'hotelboutique' => 'מלונות בוטיק',
'accommodation' => 'הלילות שבהם אזדקק לסידור לינה',
'night1' => 'יום שני, 1 באוגוסט 2011',
'night2' => 'יום שלישי, 2 באוגוסט 2011',
'night3' => 'יום רביעי, 3 באוגוסט 2011',
'night4' => 'יום חמישי, 4 באוגוסט 2011',
'night5' => 'יום שישי, 5 באוגוסט 2011',
'night6' => 'יום שבת, 6 באוגוסט 2011',
'night7' => 'יום ראשון, 7 באוגוסט 2011',
'night8' => 'יום שני, 8 באוגוסט 2011',
'room' => 'חדר מועדף',
'room1' => 'חדר ליחיד',
'room2' => 'חדר לשניים עם שותף מאותו המין שייבחר באקראי על ידי המארגנים',
'room3' => 'חדר זוגי עם משתתף ספציפי (הכניסו את שמו המלא):',
'room_requests' => 'בקשות מיוחדות בנוגע לסידור הלינה (למשל חדר מתאים לנכים)',
'room_partner' => 'שותף לחדר',
'title6' =>
'<p><strong>אופן התשלום</strong></p>
<p>תשלום דמי ההשתתפות ועלות סידורי הלינה נעשה באמצעות פייפאל (כולל בכרטיס אשראי) בזמן הרישום.</p>
<p>אם יש ברשותכם קוד הנחה, אנא הכניסו אותו כעת.</p>',
'title7' =>
'<p><strong>CAPTCHA</strong></p><p>על מנת לוודא שהינכם בני אדם ולא תוכנית מחשב, אנא הקלידו את המלים הבאות.</p>',
'discount_code' => 'קוד הנחה',
'submit_notice' =>
'<li><strong>אפשר לוודא את פרטי הרישום גם לאחר שליחת הטופס.</strong></li>',
'asterix_meaning' =>
'<li><strong>כוכבית ליד שם שדה מציינת שחובה למלאו.</strong></li>',
'submit' => 'שליחה',
'reset' => 'איפוס',

'confirm' => 'אישור',
'confirm_description' => 'אנא ודאו כי מילאתם את הפרטים כנדרש לפני שליחת הטופס.',

'paypal' => 'תשלום דרך PayPal',
'paypal_description' =>
'<p>נא ללחוץ על הכפתור "Pay Now" כדי לשלם דרך PayPal</p> ',
'paypal_failed' => 'ביטול התשלום ב PayPal',
'paypal_failed_description' => '<p>אפשר לנסות שוב על-ידי לחיצה חוזרת על הכפתור, או להעביר את הכספים לחשבון finance@wikimedia.org.il תוך ציון קוד הרישום בשדה תיאור הפריט.</p>',
'paypal_successful' => 'התשלום דרך PayPal עבר בהצלחה.',
'paypal_successful_description' => '<p>תודה! נודיע לך את התוצאות לאחר שנקבל את התשלום ונבדוק את פרטי הרישום.</p>',

'hackingdays' => 'כנס מתכנתים ומפגשים אחרים',
'maindays' => 'ימי הכנס העיקריים',
'tourdays' => 'יום טיולים',
'color' => 'צבע חולצה',
'white' => 'לבן',
'black' => 'שחור',
'nationality' => 'הדרכון הונפק על ידי',
'countryofbirth' => 'ארץ לידה',
'homeaddress' => 'כתובת מגורים',
'picktour' => 'יעד טיולים מועדף',
'tour0' => 'אין העדפה',
'tour1' => 'נצרת והגליל',
'tour2' => 'ירושלים',
'tour3' => 'עכו',
'tour4' => 'הגנים הבהאיים',
'tour5' => 'כפרים דרוזיים',
'main_date' => 'יום כנס עיקרי',
'captcha' => 'מידע CAPTCHA'
);

$lang_messages = array(
'successful' => 'הרישום הושלם',
'successful_description' =>
'<p>תודה על ההצטרפות לוויקימניה 2011! טופס הרישום נשלח. יש להשלים את תהליך התשלום כדי שהרישום יאושר.

<strong>מספר הרישום</strong> שלך מופיע להלן. נא לרשום את המספר לשם שימוש בו כדי לבדוק את מצב הרישום, וכדי להזדהות במערכת בעתיד.
',
'cost' => 'דמי הרישום',
'attendance_cost' => 'השתתפות בכנס: ',
'accommodation_cost' => 'לינה: ',
'vat_cost' => 'מע"מ: ',
'other_cost' => 'הוצאות אחרות: ',
'total_cost' => 'סך-הכול: ',
'usd' => ' דולר ארה"ב',
);

$lang_errors = array(
'repeat' => 'מישהו נרשם באותו שם ובאותו מספר זהות/מספר דרכון. ייתכן ששלחת את הטופס פעמיים או ש"ריעננת" את דף הרישום.',
'not_input' => '$1 נשאר ריק.',
'not_input_completely' => '$1 אינו שלם.',
'not_select' => '$1 אינו מסומן.',
'not_select_whether' => '$1 לא צוין.',
'too_long' => '$1 ארוך מדי, האורך המרבי הוא $2.',
'incorrect' => '$1 אינו תקין.',
'wrong' => '$1 שגוי.',
'visa_assistance_incomplete' => 'המידע לגבי עזרה בקבלת ויזה נשאר ריק.',
'wrong_query' => 'שם או מספר רישום שגויים.',
'paypal_unavailable' => 'הארץ או האזור שבחרת אינם נתמכים ב-PayPal.'
);

$lang_query = array(
'unique_code' => 'מספר הרישום',
'submit' => 'בדיקה',
'your_status' => 'שלום, $1, זהו מצב הרישום שלך:',
'received_money' => 'דמי הרישום (שולמו / סך הכול):',
'lack' => 'לא שולם כל הסכום',
'enough' => 'שולם הסכום במלואו',
'too_much' => 'שילמת יותר מדי',
'accepted' => 'הרישום שלך <strong>אושר</strong>.',
'rejected' => 'הרישום שלך <strong>נדחה</strong>.',
'not_yet' => 'הרישום שלך <strong>התקבל, אך טרם אושר</strong>.'

);

$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albania',
      'dz' => 'Algeria',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua and Barbuda',
      'ar' => 'Argentina',
      'am' => 'Armenia',
      'aw' => 'Aruba',
      'au' => 'Australia',
      'at' => 'Austria',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Belarus',
      'be' => 'Belgium',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivia',
      'ba' => 'Bosnia and Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brazil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgaria',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodia',
      'cm' => 'Cameroon',
      'ca' => 'Canada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Central African Republic',
      'td' => 'Chad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'People\'s Republic of China',
      'tw' => 'Republic of China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Denmark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Ecuador',
      'eg' => 'Egypt',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estonia',
      'et' => 'Ethiopia',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finland',
      'fr' => 'France',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Germany',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
	  'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

