<?php

$lang_register_form = array(
'registration_title' => 'Registrazione Wikimania 2011',
'select' => 'Seleziona',
'query' => 'Controlla lo stato della tua registrazione',
'query_title' => 'Puoi controllare lo stato della tua registrazione a Wikimania 2011 qui.',
'correction' => 'Le tue informazioni non sono state inviate a causa di un errore nel modulo.',

'legend1' => 'Informazioni personali',
'title1' => '<p><strong>Dati anagrafici</strong></p>',
'surname' => 'Cognome',
'given_name' => 'Nome',
'sex' => 'Sesso',
'sex1' => 'Maschio',
'sex2' => 'Femmina',
'sex3' => 'Non dichiarato',
'passport' => 'Passaporto numero',
'passport_valid' => 'Passaporto valido fino a (gg/mmm/aaaa)<br><small>Il tuo passaporto deve essere valido per 6 mesi.</small>',
'passport_issued' => 'Luogo di rilascio del passaporto',
'country' => 'Stato di residenza',
'birthday' => 'Data di nascita (gg/mmm/aaaa)',
'organization' => 'Organizzazione',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre' ),
'day' => '',

'title2' =>
'	  <p><strong>Lingue conosciute</strong></p>',
'langn' => 'Lingua madre',
'lang' => 'Livello di conoscenza',
'select_lang' => 'Seleziona la lingua',
'select_level' => 'Seleziona il livello di conoscenza',

'lang_level1' => '1 (Elementare)',
'lang_level2' => '2 (Intermedio)',
'lang_level3' => '3 (Avanzato)',
'lang_level4' => '4 (Quasi madrelingua)',

'lang1' => 'Lingua 1',
'lang2' => 'Lingua 2',
'lang3' => 'Lingua 3',

'lang1_level' => 'Livello di conoscenza della lingua 1',
'lang2_level' => 'Livello di conoscenza della lingua 2',
'lang3_level' => 'Livello di conoscenza della lingua 3',

'title3' =>
'<p><strong>Progetto Wikimedia e indirizzo e-mail</strong></p>
<p>Le informazioni relative alla tua e-mail saranno usate unicamente per la registrazione e per comunicazioni urgenti relative a Wikimania 2011.</p>
',
'wiki_id' => 'Nome utente del progetto Wikimedia principale',
'email' => 'La tua e-mail',


'legend2' => 'Partecipazione',
'title4' =>
'<p><strong>Partecipazione, tesserino e varie</strong></p>',
	'join_date' => 'Date di partecipazione',
	'join1' => 'Martedì 2 agosto 2011',
	'join2' => 'Mercoledì 3 agosto 2011',
	'join3' => 'Giovedì 4 agosto 2011',
	'join4' => 'Venerdì 5 agosto 2011',
	'join5' => 'Sabato 6 agosto 2011',
	'join6' => 'Domenica 7 agosto 2011',
	'join7' => 'Lunedì 8 agosto 2011',
'showname' => 'Informazioni sul tesserino',
'custom_showname' => 'Nome o pseudonimo scelto per il tesserino',
'showname1' => 'Nome',
'showname2' => 'Nome utente',
'showname3' => 'Altre informazioni:',
'size' => 'Taglia della maglietta',
'food' => 'Preferenze o problemi alimentari',
'food0' => 'Nessuna',
'food1' => 'Vegetariano',
'food2' => 'Halal',
'food_other' => 'Altro:',

'title_visa' =>
'<p><strong>Assistenza per il visto</strong></p>
<p>Se il tuo passaporto è rilasciato da <a href=http://wikimania2011.wikimedia.org/wiki/Visas#Visa_required>uno Stato per cui è richiesto un visto d\'ingresso in Israele</a>, compila questa sezione perché l\'organizzazione possa trasmettere i tuoi dati al Ministero degli esteri israeliano.',
'need_visa_assistance' => 'Sì, mi serve un visto d\'ingresso per Israele',
'visa_assistance' => 'Assistenza per il visto',
'visa_assistance_description' => 'Qualsiasi richiesta particolare di assistenza per il visto (in <strong>inglese</strong>)',

'title5' =>
'	   <p><strong>Alloggio</strong></p>
	   <p>Puoi alloggiare in un albergo o nelle residenze. Vedi <a href=http://wikimania2011.wikimedia.org/w/index.php?title=Accommodation/it&uselang=it>la pagina sugli alloggi</a> per informazioni precise su prezzi, posizione e altri dettagli.</p>
',
'accommodation_hotel' => 'Alloggio preferito<br><b><small>(<a href=http://wikimania2011.wikimedia.org/wiki/Accommodation onClick="return popup(this, \'prices\')">Prezzi</a>)</small></b>',
'hotel1' => 'Stanza nelle residenze',
'hotel2' => 'Ganei Dan',
'hotel3' => 'Marom',
'hotel4' => 'Har HaCarmel',
'hotel5' => 'Nof',
'hotel6' => 'Dan Panorama',
'hotel7' => 'Crown Plaza',
'hotel8' => 'Colony',
'hotel9' => 'Galery',
'hotel3stars' => 'Alberghi a tre stelle',
'hotel4stars' => 'Alberghi a quattro stelle',
'hotel5stars' => 'Alberghi a cinque stelle',
'hotelboutique' => 'Alberghi eleganti',

'accommodation' => 'Notti per cui è necessario l\'alloggio',
'night1' => 'Lunedì 1º agosto 2011',
'night2' => 'Martedì 2 agosto 2011',
'night3' => 'Mercoledì 3 agosto 2011',
'night4' => 'Giovedì 4 agosto 2011',
'night5' => 'Venerdì 5 agosto 2011',
'night6' => 'Sabato 6 agosto 2011',
'night7' => 'Domenica 7 agosto 2011',
'night8' => 'Lunedì 8 agosto 2011',
'room' => 'Stanza preferita',
'room1' => 'Singola',
'room2' => 'Matrimoniale/doppia con compagno/a di stanza dello stesso sesso scelto/a a caso dall\'organizzazione',
'room3' => 'Matrimoniale/doppia con compagno/a di stanza specificato/a (inserire nome completo):',
'room_requests' => 'Richieste speciali relative all\'alloggio (ad esempio stanza per disabili)',
'room_partner' => 'Compagno/a di stanza',

'title6' =>
'	   <p><strong>Pagamento</strong></p>
	   <p>Il pagamento delle spese di registrazione e alloggio va eseguito tramite PayPal al momento della registrazione.</p>
',
'title7' =>
'<p><strong>CAPTCHA</strong></p><p>Per confermare che sei un essere umano e non un robot, inserisci il codice.</p>',
'discount_code' => 'Codice sconto<br><small>Se hai un codice sconto, isneriscilo qui.</small>',
'submit_notice' =>
'<li><strong>Dopo aver inviato il modulo, potrai rivederlo prima di confermare la registrazione.</strong></li>',
'asterix_meaning' =>
'<li><strong>Un asterisco a fianco al nome di un campo significa che è obbligatorio compilarlo.</strong></li>',
'submit' => 'Invia',
'reset' => 'Annulla',

'confirm' => 'Verifica',
'confirm_description' => 'Prima di inviare il modulo, assicurati di aver inserito correttamente tutti i dati:',

'paypal' => 'Paga con PayPal',
'paypal_description' =>
'<p>Per favore, usa il pulsante "Pay Now" sottostante per pagare con PayPal!</p> ',
'paypal_failed' => 'Annulla il pagamento con PayPal',
'paypal_failed_description' => '<p>Puoi riprovare a compilare il modulo sotto, o puoi pagare in un altro momento inviando il pagamento a <b>finance@wikimedia.org.il</b>, ma assicurati di inserire il numero della tua registrazione nella causale.</p>',
'paypal_successful' => 'Pagamento con PayPal eseguito con successo.',
'paypal_successful_description' => '<p>Grazie! Ti faremo avere altre informazioni dopo che avremo ricevuto il pagamento e rivisto i tuoi dati di registrazione.</p>',

'hackingdays' => 'Riunioni degli sviluppatori e altri raduni',
'maindays' => 'Giorni principali',
'tourdays' => 'Giornata turistica',
'color' => 'Colore della maglietta',
'white' => 'Bianca',
'black' => 'Nera',
'nationality' => 'Passaporto rilasciato da',
'countryofbirth' => 'Stato di nascita',
'homeaddress' => 'Indirizzo di residenza',
'picktour' => 'Destinazione turistica preferita',
'tour0' => 'Nessuna',
'tour1' => 'Nazareth e la Galilea',
'tour2' => 'Gerusalemme',
'tour3' => 'San Giovanni d\'Acri (Acre)',
'tour4' => 'The Baha\'i Gardens',
'tour5' => 'Druze Villages',
'main_date' => 'Giorno di conferenza',
'captcha' => 'CAPTCHA'
);

$lang_messages = array(
'successful' => 'Registrazione completata',
'successful_description' =>
'<p>Grazie per la tua partecipazione a Wikimania 2011! La tua registrazione è stata inviata. Per favore, nota che hai bisogno di completare il processo di pagamento affinché la registrazione possa essere confermata.

Il tuo <strong>numero di registrazione</strong> sarà mostrato in basso. Prendi nota del numero dato, che sarà usato per controllare lo stato della tua registrazione e per confermare la tua identità in futuro.
',
'cost' => 'Contributo di registrazione',
'wikimania_cost' => 'Conferenza: ',
'accommodation_cost' => 'Alloggio: ',
'vat_cost' => 'IVA: ',
'other_cost' => 'Altre spese: ',
'total_cost' => 'Totale: ',
'usd' => 'USD',
);

$lang_errors = array(
'repeat' => 'Qualcuno si è registrato con lo stesso nome e indirizzo e-mail. È possibile che tu abbia inviato due volte il modulo o aggiornato la pagina di registrazione.',
'not_input' => '$1 è vuoto.',
'not_input_completely' => '$1 è incompleto.',
'not_select' => '$1 non è selezionato.',
'not_select_whether' => '$1 non è specificato.',
'too_long' => '$1 è troppo lungo, lunghezza limitata a $2.',
'incorrect' => '$1 non è corretto.',
'wrong' => '$1 è errato.',
'visa_assistance_incomplete' => 'Non ci sono informazioni per l\'assistenza relativa al visto',
'wrong_query' => 'Nome o numero di registrazione non validi',
'paypal_unavailable' => 'Il paese o la regione selezionati non permettono il pagamento con PayPal'
);

$lang_query = array(
'query_title' => 'Riassunto dello stato della registrazione',
'unique_code' => 'Numero di registrazione',
'submit' => 'Controlla',
'your_status' => 'Ciao, $1, questo è lo stato della tua registrazione:',
'received_money' => 'Contributo di registrazione (ricevuto / atteso):',
'lack' => 'Non completamente ricevuto',
'enough' => 'Già pagato',
'too_much' => 'Hai pagato un importo superiore al necessario',
'accepted' => 'La tua registrazione è stata <strong>confermata</strong>.',
'rejected' => 'La tua registrazione è stata <strong>rifiutata</strong>.',
'not_yet' => 'La tua registrazione è stata ricevuta, ma <strong>non ancora confermata</strong>.'

);


$lang_countries = array(
	'af' => 'Afghanistan',
	'ax' => 'Aland Islands',
	'al' => 'Albania',
	'dz' => 'Algeria',
	'as' => 'American Samoa',
	'ad' => 'Andorra',
	'ao' => 'Angola',
	'ai' => 'Anguilla',
	'aq' => 'Antarctica',
	'ag' => 'Antigua and Barbuda',
	'ar' => 'Argentina',
	'am' => 'Armenia',
	'aw' => 'Aruba',
	'au' => 'Australia',
	'at' => 'Austria',
	'az' => 'Azerbaijan',
	'bs' => 'Bahamas',
	'bh' => 'Bahrain',
	'bd' => 'Bangladesh',
	'bb' => 'Barbados',
	'by' => 'Belarus',
	'be' => 'Belgium',
	'bz' => 'Belize',
	'bj' => 'Benin',
	'bm' => 'Bermuda',
	'bt' => 'Bhutan',
	'bo' => 'Bolivia',
	'ba' => 'Bosnia and Herzegovina',
	'bw' => 'Botswana',
	'bv' => 'Bouvet Island',
	'br' => 'Brazil',
	'io' => 'British Indian Ocean Territory',
	'bn' => 'Brunei Darussalam',
	'bg' => 'Bulgaria',
	'bf' => 'Burkina Faso',
	'mm' => 'Burma (Myanmar)',
	'bi' => 'Burundi',
	'kh' => 'Cambodia',
	'cm' => 'Cameroon',
	'ca' => 'Canada',
	'cv' => 'Cape Verde',
	'ky' => 'Cayman Islands',
	'cf' => 'Central African Republic',
	'td' => 'Chad',
	'cl' => 'Chile',
	'hk' => 'Hong Kong SAR',
	'cn' => 'People\'s Republic of China',
	'tw' => 'Republic of China (Taiwan)',
	'cx' => 'Christmas Island',
	'cc' => 'Cocos (keeling) Islands',
	'co' => 'Colombia',
	'km' => 'Comoros',
	'cg' => 'Congo',
	'cd' => 'Congo\, The Democratic Republic of the',
	'ck' => 'Cook Islands',
	'cr' => 'Costa Rica',
	'ci' => 'Cote D\'ivoire',
	'hr' => 'Croatia',
	'cu' => 'Cuba',
	'cy' => 'Cyprus',
	'cz' => 'Czech Republic',
	'dk' => 'Denmark',
	'dj' => 'Djibouti',
	'dm' => 'Dominica',
	'do' => 'Dominican Republic',
	'ec' => 'Ecuador',
	'eg' => 'Egypt',
	'sv' => 'El Salvador',
	'gq' => 'Equatorial Guinea',
	'er' => 'Eritrea',
	'ee' => 'Estonia',
	'et' => 'Ethiopia',
	'fk' => 'Falkland Islands (malvinas)',
	'fo' => 'Faroe Islands',
	'fj' => 'Fiji',
	'fi' => 'Finland',
	'fr' => 'France',
	'gf' => 'French Guiana',
	'pf' => 'French Polynesia',
	'tf' => 'French Southern Territories',
	'ga' => 'Gabon',
	'gm' => 'Gambia',
	'ge' => 'Georgia',
	'de' => 'Germany',
	'gh' => 'Ghana',
	'gi' => 'Gibraltar',
	'gr' => 'Greece',
	'gl' => 'Greenland',
	'gd' => 'Grenada',
	'gp' => 'Guadeloupe',
	'gu' => 'Guam',
	'gt' => 'Guatemala',
	'gn' => 'Guinea',
	'gw' => 'Guinea-Bissau',
	'gy' => 'Guyana',
	'ht' => 'Haiti',
	'hm' => 'Heard Island and Mcdonald Islands',
	'va' => 'Holy See (Vatican City)',
	'hn' => 'Honduras',
	'hu' => 'Hungary',
	'is' => 'Iceland',
	'in' => 'India',
	'id' => 'Indonesia',
	'ir' => 'Iran, Islamic Republic of',
	'iq' => 'Iraq',
	'ie' => 'Ireland',
	'il' => 'Israel',
	'it' => 'Italy',
	'jm' => 'Jamaica',
	'jp' => 'Japan',
	'jo' => 'Jordan',
	'kz' => 'Kazakhstan',
	'ke' => 'Kenya',
	'ki' => 'Kiribati',
	'kp' => 'Democratic People\'s Republic of Korea',
	'kr' => 'Republic of Korea',
	'kw' => 'Kuwait',
	'kg' => 'Kyrgyzstan',
	'la' => 'Lao People\'s Democratic Republic',
	'lv' => 'Latvia',
	'lb' => 'Lebanon',
	'ls' => 'Lesotho',
	'lr' => 'Liberia',
	'ly' => 'Libyan Arab Jamahiriya',
	'li' => 'Liechtenstein',
	'lt' => 'Lithuania',
	'lu' => 'Luxembourg',
	'mo' => 'Macao',
	'mk' => 'Macedonia, The Former Yugoslav Republic of',
	'mg' => 'Madagascar',
	'mw' => 'Malawi',
	'my' => 'Malaysia',
	'mv' => 'Maldives',
	'ml' => 'Mali',
	'mt' => 'Malta',
	'mh' => 'Marshall Islands',
	'mq' => 'Martinique',
	'mr' => 'Mauritania',
	'mu' => 'Mauritius',
	'yt' => 'Mayotte',
	'mx' => 'Mexico',
	'fm' => 'Micronesia, Federated States of',
	'md' => 'Moldova, Republic of',
	'mc' => 'Monaco SAR',
	'mn' => 'Mongolia',
	  'me' => 'Montenegro',
	'ms' => 'Montserrat',
	'ma' => 'Morocco',
	'mz' => 'Mozambique',
	'na' => 'Namibia',
	'nr' => 'Nauru',
	'np' => 'Nepal',
	'nl' => 'Netherlands',
	'an' => 'Netherlands Antilles',
	'nc' => 'New Caledonia',
	'nz' => 'New Zealand',
	'ni' => 'Nicaragua',
	'ne' => 'Niger',
	'ng' => 'Nigeria',
	'nu' => 'Niue',
	'nf' => 'Norfolk Island',
	'mp' => 'Northern Mariana Islands',
	'no' => 'Norway',
	'om' => 'Oman',
	'pk' => 'Pakistan',
	'pw' => 'Palau',
	'ps' => 'Palestinian Territory',
	'pa' => 'Panama',
	'pg' => 'Papua New Guinea',
	'py' => 'Paraguay',
	'pe' => 'Peru',
	'ph' => 'Philippines',
	'pn' => 'Pitcairn',
	'pl' => 'Poland',
	'pt' => 'Portugal',
	'pr' => 'Puerto Rico',
	'qa' => 'Qatar',
	're' => 'Reunion',
	'ro' => 'Romania',
	'ru' => 'Russian Federation',
	'rw' => 'Rwanda',
	'sh' => 'Saint Helena',
	'kn' => 'Saint Kitts and Nevis',
	'lc' => 'Saint Lucia',
	'pm' => 'Saint Pierre and Miquelon',
	'vc' => 'Saint Vincent and the Grenadines',
	'ws' => 'Samoa',
	'sm' => 'San Marino',
	'st' => 'Sao Tome and Principe',
	'sa' => 'Saudi Arabia',
	'sn' => 'Senegal',
	'rs' => 'Serbia',
	'sc' => 'Seychelles',
	'sl' => 'Sierra Leone',
	'sg' => 'Singapore',
	'sk' => 'Slovakia',
	'si' => 'Slovenia',
	'sb' => 'Solomon Islands',
	'so' => 'Somalia',
	'za' => 'South Africa',
	'gs' => 'South Georgia and the South Sandwich Islands',
	'es' => 'Spain',
	'lk' => 'Sri Lanka',
	'sd' => 'Sudan',
	'sr' => 'Suriname',
	'sj' => 'Svalbard and Jan Mayen',
	'sz' => 'Swaziland',
	'se' => 'Sweden',
	'ch' => 'Switzerland',
	'sy' => 'Syrian Arab Republic',
	'tj' => 'Tajikistan',
	'tz' => 'Tanzania, United Republic of',
	'th' => 'Thailand',
	'tl' => 'Timor-leste',
	'tg' => 'Togo',
	'tk' => 'Tokelau',
	'to' => 'Tonga',
	'tt' => 'Trinidad and Tobago',
	'tn' => 'Tunisia',
	'tr' => 'Turkey',
	'tm' => 'Turkmenistan',
	'tc' => 'Turks and Caicos Islands',
	'tv' => 'Tuvalu',
	'ug' => 'Uganda',
	'ua' => 'Ukraine',
	'ae' => 'United Arab Emirates',
	'gb' => 'United Kingdom',
	'us' => 'United States',
	'um' => 'United States Minor Outlying Islands',
	'uy' => 'Uruguay',
	'uz' => 'Uzbekistan',
	'vu' => 'Vanuatu',
	've' => 'Venezuela',
	'vn' => 'Viet Nam',
	'vg' => 'Virgin Islands, British',
	'vi' => 'Virgin Islands, U.S.',
	'wf' => 'Wallis and Futuna',
	'eh' => 'Western Sahara',
	'ye' => 'Yemen',
	'zm' => 'Zambia',
	'zw' => 'Zimbabwe'
);

