<?php

$lang_register_form = array(
'registration_title' => 'Inscription pour Wikimania 2011',
'select' => 'Choisissez',
'query' => 'Interroger le statut de vôtre inscription',
'query_title' => 'Vous pouvez interroger le statut de vôtre inscription ici.',
'correction' => 'Vos données comportent des erreurs et ne peuvent être enregistrées.',

'legend1' => 'Informations personnelles',
'title1' =>
'<p><strong>Données sur l\'identité du participant</strong></p>',
'surname' => 'Nom',
'given_name' => 'Prénom',
'sex' => 'Sexe',
'sex1' => 'masculin',
'sex2' => 'féminin',
'sex3' => 'non communiqué',
'passport' => 'Numéro de passeport',
'passport_valid' => 'Passeport valide jusqu\'au (JJ/MM/AAAA)<br><small>Vôtre passeport doit impérativement être encore valide six mois après la date d\'entrée sur le territoire.</small>',
'passport_issued' => 'Passeport délivré à',
'country' => 'Pays de résidence',
'birthday' => 'Date de naissance (JJ/MM/AAAA)',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre' ),
'day' => '',
'title2' =>
'        <p><strong>Compétences linguistiques</strong></p>',
'langn' => 'Langue maternelle',
'lang' => 'Autres langues',
'select_lang' => 'Choisir une langue',
'select_level' => 'Choisir un niveau',

'lang_level1' => '1 (basique)',
'lang_level2' => '2 (intermédiaire)',
'lang_level3' => '3 (bon)',
'lang_level4' => '4 (bilingue)',

'lang1' => 'Langue 1',
'lang2' => 'Langue 2',
'lang3' => 'Langue 3',

'lang1_level' => 'Compétences linguistiques pour la langue 1',
'lang2_level' => 'Compétences linguistiques pour la langue 2',
'lang3_level' => 'Compétences linguistiques pour la langue 3',

'title3' =>
'<p><strong>Projet Wikimédia et adresse de courriel</strong></p>
<p>Vôtre adresse de courriel sera utilisée uniquement dans le cadre de Wikimania 2011.
</p>
',
'wiki_id' => 'Nom d\'utilisateur sur les projets Wikimédia',
'email' => 'Adresse de courriel',

'legend2' => 'Participation',
'title4' =>
'<p><strong>Participation, badge et autres informations</strong></p>',
'join_date' => 'Présent le :',
'join1' => 'Mardi, 2 août 2011',
'join2' => 'Mercredi, 3 août 2011',
'join3' => 'Jeudi, 4 août 2011',
'join4' => 'Vendredi, 5 août 2011',
'join5' => 'Samedi, 6 août 2011',
'join6' => 'Dimanche, 7 août 2011',
'join7' => 'Lundi, 8 août 2011',
'showname' => 'Nom affiché sur le badge',
'custom_showname' => 'Nom personnalisé sur le badge',
'showname1' => 'Nom',
'showname2' => 'Nom d\'utilisateur sur les projets Wikimédia',
'showname3' => 'Informations supplémentaires :',
'size' => 'Taille du T-Shirt',
'food' => 'Pratique alimentaire particulière<br><small>Tous les repas durant la conférence seront casher.</small>',
'food0' => 'aucune',
'food1' => 'végétarien',
'food2' => 'halal',
'food_other' => 'autre :',

'title_visa' =>
'<p><strong>Visa</strong></p>
<p>Si vôtre passeport a été émis d\'un <a href=http://wikimania2011.wikimedia.org/wiki/Visas#Visa_required>pays pour lequel il est exigé un visa de la part d\'Israël</a>, renseignez le formulaire suivant afin que l\'organisation soit en mesure de communiquer ces informations au ministère israélien des Affaires étrangères.',
'need_visa_assistance' => 'Oui, ma venue en Israël nécessite un visa.',
'visa_assistance' => 'Nécessité d\'un visa',
'visa_assistance_description' => 'Requête particulière relative à la demande de visa (en <strong>anglais</strong>)',

'title5' =>
'<p><strong>Hébergement</strong></p>
<p>Vous pouvez être hébergé(e) dans un hotel ou dans un dortoir.
Informez-vous sur <a href=http://wikimania2011.wikimedia.org/wiki/Accommodation>la page dédiée</a> pour avoir de plus amples informations, en particulier sur <b>les prix</b> ou encore sur les localisations.</p>',
'accommodation_hotel' => 'Hébergement souhaité<br><b><small>(<a href=http://wikimania2011.wikimedia.org/wiki/Accommodation onClick="return popup(this, \'prices\')">Prix</a>)</small></b>',
'hotel1' => 'Dortoir',
'hotel2' => 'Ganei Dan',
'hotel3' => 'Marom',
'hotel4' => 'Har HaCarmel',
'hotel5' => 'Nof',
'hotel6' => 'Dan Panorama',
'hotel7' => 'Crown Plaza',
'hotel8' => 'Colony',
'hotel9' => 'Galery',
'hotel3stars' => 'Hotels ***',
'hotel4stars' => 'Hotels ****',
'hotel5stars' => 'Hotels *****',
'hotelboutique' => 'Boutique-Hotels',

'accommodation' => 'Nuitées où un hébergement est nécessaire',
'night1' => 'Lundi, 1. août 2011',
'night2' => 'Mardi, 2 août 2011',
'night3' => 'Mercredi, 3 août 2011',
'night4' => 'Jeudi, 4 août 2011',
'night5' => 'Vendredi, 5 août 2011',
'night6' => 'Samedi, 6 août 2011',
'night7' => 'Dimanche, 7 août 2011',
'night8' => 'Lundi, 8 août 2011',
'room' => 'Type de chambre souhaitée',
'room1' => 'Individuelle',
'room2' => 'Double avec un autre participant du même sexe choisi au hasard.',
'room3' => 'Double avec un autre participant en particulier (prière de donner le nom et prénom complet) :',
'room_requests' => 'Requête particulière concernant l\'hébergement (par exemple pour garantir un accès à une chaise roulante)',
'room_partner' => 'Partenaire de chambrée',
'title6' =>
'<p><strong>Paiement</strong></p>
<p>Le paiement des frais d\'inscription et d\'hébergement s\'effectue via PayPal pendant l\'inscription.<br></p>',
'title7' =>
'<p><strong>CAPTCHA</strong></p><p>Pour s\'assurer que vous êtes un humain et non un bot nous vous prions de bien remplir le formulaire suivant.</p>',
'discount_code' => 'Code pour une réduction<br><small>Si vous avez un code pour une réduction, renseignez le formulaire suivant.</small>',
'submit_notice' =>
'<li><strong>Après avoir rempli et envoyé ce formulaire, vous avez la possibilité de vérifier vos données une dernière fois.</strong></li>',
'asterix_meaning' =>
'<li><strong>Les champs marqués d\'un astérisque (*) doivent être obligatoirement renseignés.</strong></li>',
'submit' => 'Envoyer',
'reset' => 'Abandonner',

'confirm' => 'Vérification',
'confirm_description' => 'Avant d\'envoyer définitivement les données du formulaire veuillez vérifier que toutes les informations sont correctes',

'paypal' => 'Paiement via PayPal',
'paypal_description' =>
'<p>Veuillez utiliser le button intitulé "Pay Now" pour payer <b>maintenant</b> avec PayPal!</p> ',
'paypal_failed' => 'Abandonner le paiement via PayPal',
'paypal_failed_description' => '<p>Vous pouvez de nouveau essayer de remplir les champs suivants ou bien vous pouvez payer plus tard en versant le montant via Paypal à <b>finance@wikimedia.org.il</b>, dans ce cas pensez à indiquer vôtre code d\'inscription dans la description du virement.</p>',
'paypal_successful' => 'Le paiement via PayPal s\'est effecuté avec succès.',
'paypal_successful_description' => '<p>Merci beaucoup! Nous allons vous confirmer vôtre inscription dès réception du virement via PayPal et vérifications de vos données d\'inscription.</p>',

'hackingdays' => 'Rencontre des développeurs et autres rencontres',
'maindays' => 'Conférence principale',
'tourdays' => 'Journée de visite',
'color' => 'Couleur du T-Shirt',
'white' => 'blanc',
'black' => 'noir',
'nationality' => 'Pays d\'émission du passeport',
'countryofbirth' => 'Pays de naissance',
'homeaddress' => 'Adresse de résidence',
'picktour' => 'Souhait de visite',
'tour0' => 'pas de souhait particulier',
'tour1' => 'Nazareth et lac de Tibériade',
'tour2' => 'Jérusalem',
'tour3' => 'Acre',
'tour4' => 'Terrasses Baha\'i sur le Mont Carmel',
'tour5' => 'Villages druses',
'main_date' => 'Journée principale de la conférence',
'captcha' => 'Information du CAPTCHA'
);


$lang_messages = array(
'successful' => 'Inscription terminée',
'successful_description' =>
'<p>Merci beaucoup pour vôtre participation à Wikimania 2011! Vôtre inscription a été transmise. Prenez en considération qu\'il vous faudra effecuté le paiement afin de que vôtre inscription puisse être confirmée.

Vôtre <strong>numéro d\'inscription</strong> va être indiqué ci-dessous. Prenez en considération qu\'il vous faudra obligatoirement ce numéro pour interroger le système sur le statut de vôtre inscription.
',
'cost' => 'Frais d\'inscription : ',
'attendance_cost' => 'Conférence: ',
'accommodation_cost' => 'Hébergement: ',
'vat_cost' => 'TVA: ',
'other_cost' => 'Autres frais: ',
'total_cost' => 'Total: ',
'usd' => ' USD',
);

$lang_errors = array(
'repeat' => 'Quelqu\'un avec ce nom et cet adresse de courriel s\'est déjà enregistré. Peut-être avez-vous rempli le formulaire d\'inscription deux fois ou rechargé la page Web une deuxième fois',
'not_input' => '$1 est vide.',
'not_input_completely' => '$1 n\'est pas complet.',
'not_select' => '$1 ist nicht ausgewählt.',
'not_select_whether' => '$1 n\'a pas été renseigné.',
'too_long' => '$1 est trop long, la longueur maximale est $2.',
'incorrect' => '$1 n\'est pas correct.',
'wrong' => '$1 est faux.',
'visa_assistance_incomplete' => 'Les données relative au Visa sont manquantes.',
'wrong_query' => 'Mauvais nom ou numéro d\'inscription.',
'paypal_unavailable' => 'Le pays ou la région choisi(e) n\'est pas supporté(e) par PayPal.'
);

$lang_query = array(
'query_title' => 'Synthèse de vôtre inscription',
'unique_code' => 'Numéro d\'inscription:',
'submit' => 'Envoyer',
'your_status' => 'Bienvenue $1, ceci est le statut de vôtre inscription :',
'received_money' => 'Frais d\'inscription (payés / attendus):',
'lack' => 'pas encore complètement payés',
'enough' => 'entièrement payés',
'too_much' => 'trop payé',
'accepted' => 'Vôtre inscription a été <strong>confirmée</strong>.',
'rejected' => 'Vôtre inscription a été <strong>refusée</strong>.',
'not_yet' => 'Vôtre inscription a été <strong>reçue, mais pas encore confirmée</strong>.'
);

$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Åland',
      'al' => 'Albanie',
      'dz' => 'Algérie',
      'ad' => 'Andorre',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctique',
      'ag' => 'Antigua und Barbuda',
      'ar' => 'Argentine',
      'am' => 'Arménie',
      'aw' => 'Aruba',
      'au' => 'Australie',
      'at' => 'Autriche',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Biélorussie',
      'be' => 'Belgique',
      'bz' => 'Belize',
      'bj' => 'Bénin',
      'bm' => 'Bermudes',
      'bt' => 'Bhutan',
      'bo' => 'Bolivie',
      'ba' => 'Bosnie-Herzégovine',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brésil',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgarie',
      'bf' => 'Burkina Faso',
      'mm' => 'Birmanie (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Cambodge',
      'cm' => 'Cameroun',
      'ca' => 'Canada',
      'cv' => 'Cap-Vert',
      'ky' => 'Îles Cayman',
      'cf' => 'République centrafricaine',
      'td' => 'Tchad',
      'cl' => 'Chili',
      'hk' => 'Hong Kong SAR',
      'cn' => 'République populaire de Chine',
      'tw' => 'République de Chine (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombie',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'République démocratique du Congo',
      'ck' => 'Îles Cook',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatie',
      'cu' => 'Cuba',
      'cy' => 'Chypre',
      'cz' => 'Czech Republic',
      'dk' => 'Danemark',
      'dj' => 'Djibouti',
      'dm' => 'Dominique',
      'do' => 'République dominicaine',
      'ec' => 'Équateur',
      'eg' => 'Égypte',
      'sv' => 'El Salvador',
      'gq' => 'Guinée équatoriale',
      'er' => 'Érythrée',
      'ee' => 'Estonie',
      'et' => 'Éthiopie',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fidji',
      'fi' => 'Finlande',
      'fr' => 'France',
      'gf' => 'Guyane française',
      'pf' => 'Polynésie française',
      'tf' => 'Territoires français du Sud',
      'ga' => 'Gabon',
      'gm' => 'Gambie',
      'ge' => 'Géorgie',
      'de' => 'Allemagne',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Grèce',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinée',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyane',
      'ht' => 'Haïti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hongrie',
      'is' => 'Islande',
      'in' => 'Inde',
      'id' => 'Indonésie',
      'ir' => 'Iran',
      'iq' => 'Irak',
      'ie' => 'Irelande',
      'il' => 'Israël',
      'it' => 'Italie',
      'jm' => 'Jamaique',
      'jp' => 'Japon',
      'jo' => 'Jordanie',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Liban',
      'ls' => 'Lesotho',
      'lr' => 'Libéria',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lituanie',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malte',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexique',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolie',
      'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Maroc',
      'mz' => 'Mozambique',
      'na' => 'Namibie',
      'nr' => 'Nauru',
      'np' => 'Népal',
      'nl' => 'Pays-Bas',
      'an' => 'Netherlands Antilles',
      'nc' => 'Nouvelle Calédonie',
      'nz' => 'Nouvelle-Zélande',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norvège',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Pérou',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Pologne',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Réunion',
      'ro' => 'Roumanie',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'eh' => 'Sahara occidental',
      'as' => 'Samoa américaines',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucie',
      'pm' => 'Saint Pierre et Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Sénégal',
      'rs' => 'Serbie',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapour',
      'sk' => 'Slovaquie',
      'si' => 'Slovénie',
      'sb' => 'Solomon Islands',
      'so' => 'Somalie',
      'za' => 'Afrique du Sud',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Suède',
      'ch' => 'Suisse',
      'sy' => 'Syrie',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisie',
      'tr' => 'Turquie',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'ye' => 'Yemen',
      'zm' => 'Zambie',
      'zw' => 'Zimbabwe'
);

?>
