<?php

$lang_register_form = array(
'registration_title' => 'Inscripción para Wikimanía 2011',
'select' => 'Elija una opción',
'query' => 'Consulta el estado de tu inscripción',
'query_title' => 'Puedes consultar el estado de tu inscripción para Wikimanía 2011 aquí.',
'correction' => 'La información no ha sido enviada debido a un error en el formulario.',

'legend1' => 'Información personal',
'title1' =>
'<p><strong>Datos de información personal</strong></p>',
'surname' => 'Apellido',
'given_name' => 'Nombre',
'sex' => 'Género',
'sex1' => 'Masculino',
'sex2' => 'Femenino',
'sex3' => 'No declara',
'passport' => 'Número de pasaporte / Número de identificación',
'passport_valid' => 'Pasaporte válido hasta (dd/mmm/yyyy)<br><small>Tu pasaporte debe ser válido por 6 meses.</small>',
'passport_issued' => 'Lugar en donde el pasaporte fue emitido',
'country' => 'País de residencia',
'birthday' => 'Fecha de nacimiento (dd/mmm/yyyy)',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre' ),
'day' => '',
'title2' =>
'	  <p><strong>Habilidades lingüísticas</strong></p>',
'langn' => 'Idioma nativo',
'lang' => 'Idiomas adicionales',
'select_lang' => 'Selecciona el idioma',
'select_level' => 'Selecciona el nivel de dominio',

'lang_level1' => '1 (Basico)',
'lang_level2' => '2 (Intermedio)',
'lang_level3' => '3 (Avanzado)',
'lang_level4' => '4 (Casi nativo)',

'lang1' => 'Idioma 1',
'lang2' => 'Idioma 2',
'lang3' => 'Idioma 3',

'lang1_level' => 'Nivel del Idioma 1',
'lang2_level' => 'Nivel del Idioma 2',
'lang3_level' => 'Nivel del Idioma 3',

'title3' =>
'<p><strong>Proyecto de Wikimedia y dirección/es de correo electrónico</strong></p>
<p>Tu correo electrónico sólo será utilizado para la inscripción y para notificaciones urgentes sobre Wikimanía 2011.
</p>
',
'wiki_id' => 'Nombre de la cuenta de tu proyecto Wikimedia preferido',
'email' => 'Tu correo electrónico',

'legend2' => 'Participación',
'title4' =>
'<p><strong>Participación, información para tu credencial y otros datos</strong></p>',
'join_date' => 'Fechas de participación',
'join1' => 'Martes 2 de agosto de 2011',
'join2' => 'Miércoles 3 de agosto de 2011',
'join3' => 'Jueves 4 de agosto de 2011',
'join4' => 'Viernes 5 de agosto de 2011',
'join5' => 'Sábado 6 de agosto de 2011',
'join6' => 'Domingo 7 de agosto de 2011',
'join7' => 'Lunes 8 de agosto de 2011',
'showname' => 'Información para la credencial',
'custom_showname' => 'Apodo preferido para la credencial',
'showname1' => 'Nombre',
'showname2' => 'Cuenta Wikimedia',
'showname3' => 'Información adicional:',
'size' => 'Talla de camiseta',
'food' => 'Restricciones de dieta<br><small>Todos los alimentos que se servirán durante la conferencia serán kosher.</small>',
'food0' => 'No',
'food1' => 'Vegetariano',
'food2' => 'Halal',
'food_other' => 'Otro:',

'title_visa' =>
'<p><strong>Asistencia para visa</strong></p>
<p>Si tu pasaporte es emitido por <a href=http://wikimania2011.wikimedia.org/wiki/Visas#Visa_required>un país para el que se requiere un visado de entrada a Israel</a>, por favor llena esta sección para que los organizadores pueden pasar sus datos al Ministerio israelí de Asuntos Exteriores.',
'need_visa_assistance' => 'Sí, necesito un visado de entrada a Israel',
'visa_assistance' => 'Ayuda para obtener la visa',
'visa_assistance_description' => 'Por favor indícanos cómo puede ayudarte el equipo organizador a obtener la visa. (en <strong>Inglés</strong>)',

'title5' =>
'<p><strong>Alojamiento</strong></p>
<p>Puedes alojarte en un hotel o en los dormitorios.
Por favor visita el <a href=http://wikimania2011.wikimedia.org/wiki/Accommodation>sitio oficial de Wikimanía</a> para <b>precios</b> exactos, ubicaciones y otros detalles.</p>',
'accommodation_hotel' => 'Alojo preferido<br><b><small>(<a href=http://wikimania2011.wikimedia.org/wiki/Accommodation onClick="return popup(this, \'prices\')">Precios</a>)</small></b>',
'hotel1' => 'Dormitorio',
'hotel2' => 'Ganei Dan',
'hotel3' => 'Marom',
'hotel4' => 'Har HaCarmel',
'hotel5' => 'Nof',
'hotel6' => 'Dan Panorama',
'hotel7' => 'Crown Plaza',
'hotel8' => 'Colony',
'hotel9' => 'Galery',
'hotel3stars' => 'Hotel de tres estrellas',
'hotel4stars' => 'Hotel de cuatro estrellas',
'hotel5stars' => 'Hotel de cinco estrellas',
'hotelboutique' => 'Hotel boutique',

'accommodation' => 'Noches de alojamiento que necesitas',
'night1' => 'Lunes 1 de agosto, 2011',
'night2' => 'Martes 2 de agosto, 2011',
'night3' => 'Miércoles 3 de agosto, 2011',
'night4' => 'Jueves 4 de agosto, 2011',
'night5' => 'Viernes 5 de agosto, 2011',
'night6' => 'Sábado 5 de agosto, 2011',
'night7' => 'Domingo 7 de agosto, 2011',
'night8' => 'Lunes 8 de agosto, 2011',
'room' => 'Habitación preferida',
'room1' => 'Ocupación individual',
'room2' => 'Ocupación doble con pareja del mismo género seleccionada al azar por los organizadores',
'room3' => 'Ocupación doble con un compañero (a) en específico (por favor escriba nombre completo)',
'room_requests' => 'Peticiones especiales relacionadas al alojamiento (por ejemplo, personas con discapacidad)',
'room_partner' => 'Compañero de cuarto',
'title6' =>
'<p><strong>Pago</strong></p>
<p>El pago por acceso a la conferencia y el alojamiento se realiza a través de PayPal en el momento del registro. <br></p>',
'title7' =>
'<p><strong>CAPTCHA</strong></p><p>Para asegurarnos de que eres una persona y no un bot, por favor completa el siguiente CAPTCHA.</p>',
'discount_code' => 'Código de descuento<br><small>Si tienes un código de descuento, por favor introdúcelo aquí.</small>',
'submit_notice' =>
'<li><strong>Antes de que envíes tu formulario, tienes aún la oportunidad de verificar los datos que introduciste.</strong></li>',
'asterix_meaning' =>
'<li><strong>Un asterisco junto al nombre de un campo significa que debes completarla.</strong></li>',
'submit' => 'Enviar',
'reset' => 'Limpiar',

'confirm' => 'Verificación',
'confirm_description' => 'Antes de aceptar el formulario, por favor, asegúrate de haber completado correctamente la información:',

'paypal' => 'Pago vía PayPal',
'paypal_description' =>
'<p>Por favor, utiliza el botón "Buy now" que aparece debajo para pagar a través de PayPal</p> ',
'paypal_failed' => 'Cancelar pago vía PayPal',
'paypal_failed_description' => '<p>Puedes intentar nuevamente llenando el formulario que se encuentra debajo, o puedes pagar en otro momento transfiriendo los fondos vía PayPal a <b>finance@wikimedia.org.il</b>, asegurándote de añadir tu número de registro en el campo de descripción.</p>',
'paypal_successful' => 'Pago vía PayPal completado con éxito',
'paypal_successful_description' => '<p>Gracias! Le notificaremos el resultado después de que recibamos el pago y revisemos su información de registro.</p>',

'hackingdays' => 'Encuentro de desarrolladores y otros encuentros',
'maindays' => 'Días principales',
'tourdays' => 'Día de tour',
'color' => 'Color de camiseta',
'white' => 'Blanca',
'black' => 'negra',
'nationality' => 'Pasaporte emitido por',
'countryofbirth' => 'País de nacimiento',
'homeaddress' => 'Dirección',
'picktour' => 'Destino de tour preferido',
'tour0' => 'No tengo una preferencia',
'tour1' => 'Nazareth y Galilea',
'tour2' => 'Jerusalén',
'tour3' => 'Acre (Acco)',
'tour4' => 'Jardines Bahá’í',
'tour5' => 'Villas drusas',
'main_date' => 'Día principal de la conferencia',
'captcha' => 'Información de CAPTCHA'
);


$lang_messages = array(
'successful' => 'Registro completo',
'successful_description' =>
'<p>¡Gracias por sumarte a Wikimanía 2011! Tu formulario de inscripción fue aceptado. Por favor, ten en cuenta que necesitas completar el proceso de pago para que la inscripción pueda ser confirmada.

Tu <strong>número de registro</strong> será mostrado debajo. Por favor, anota este número ya que será utilizado para consultar el estado de tu inscripción y para confirmar tu identidad en el futuro.
',
'cost' => 'Cuota de inscripción: ',
'attendance_cost' => 'Conferencia: ',
'accommodation_cost' => 'Alojamiento: ',
'vat_cost' => 'VAT: ',
'other_cost' => 'Otros costos ',
'total_cost' => 'Total: ',
'usd' => ' USD',
);

$lang_errors = array(
'repeat' => 'Ya existe alguien registrado con este nombre y número de identificación / pasaporte. Es posible que te hayas registrado dos veces o que hayas recargado la página de inscripción.',
'not_input' => '$1 está vacío.',
'not_input_completely' => '$1 está incompleto.',
'not_select' => '$1 no fue elegido.',
'not_select_whether' => '$1 no fue especificado.',
'too_long' => '$1 es muy largo, la longitud máxima es $2.',
'incorect' => '$1 es incorrecto.',
'wrong' => '$1 es erróneo.',
'visa_assistance_incomplete' => 'La información de asistencia para la visa está vacía.',
'wrong_query' => 'Nombre o número de inscripción incorrecto.',
'paypal_unavailable' => 'PaypPal no funciona en el país / región seleccionada.'
);

$lang_query = array(
'query_title' => 'Resumen del estado de la inscripción',
'unique_code' => 'Número de registro:',
'submit' => 'Consultar',
'your_status' => 'Hola, $1, aquí tienes el estado de tu inscripción:',
'received_money' => 'Cuota de inscripción (recibida / esperada):',
'lack' => 'No recibida',
'enough' => 'Pagada',
'too_much' => 'Has pagado por demás',
'accepted' => 'Tu inscripción está <strong>confirmada</strong>.',
'rejected' => 'Tu inscripción fue <strong>rechazada</strong>.',
'not_yet' => 'Tu inscripción <strong>no fue confirmada</strong>.'

);

$lang_countries = array(
	'af' => 'Afganistán',
	'ax' => 'Islas Aland',
	'al' => 'Albania',
	'dz' => 'Algeria',
	'as' => 'Samoa Estadounidense',
	'ad' => 'Andorra',
	'ao' => 'Angola',
	'ai' => 'Anguilla',
	'aq' => 'Antártida',
	'ag' => 'Antigua y Barbuda',
	'ar' => 'Argentina',
	'am' => 'Armenia',
	'aw' => 'Aruba',
	'au' => 'Australia',
	'at' => 'Austria',
	'az' => 'Azerbayán',
	'bs' => 'Bahamas',
	'bh' => 'Bahrein',
	'bd' => 'Bangladesh',
	'bb' => 'Barbados',
	'by' => 'Belarus',
	'be' => 'Bélgica',
	'bz' => 'Belice',
	'bj' => 'Benin',
	'bm' => 'Bermuda',
	'bt' => 'Bhutan',
	'bo' => 'Bolivia',
	'ba' => 'Bosnia y Herzegovina',
	'bw' => 'Botswana',
	'bv' => 'Bouvet Island',
	'br' => 'Brasil',
	'io' => 'British Indian Ocean Territory',
	'bn' => 'Brunei Darussalam',
	'bg' => 'Bulgaria',
	'bf' => 'Burkina Faso',
	'mm' => 'Burma (Myanmar)',
	'bi' => 'Burundi',
	'kh' => 'Cambodia',
	'cm' => 'Camerún',
	'ca' => 'Canadá',
	'cv' => 'Cabo Verde',
	'ky' => 'Islans Caimán',
	'cf' => 'República Central Africana',
	'td' => 'Chad',
	'cl' => 'Chile',
	'hk' => 'Hong Kong SAR',
	'cn' => 'República Popular de China',
	'tw' => 'República Popular de China (Taiwan)',
	'cx' => 'Isla de Navidad',
	'cc' => 'Islas Coco',
	'co' => 'Colombia',
	'km' => 'Comoros',
	'cg' => 'Congo',
	'cd' => 'Congo\, The Democratic Republic of the',
	'ck' => 'Cook Islands',
	'cr' => 'Costa Rica',
	'ci' => 'Cote D\'ivoire',
	'hr' => 'Croacia',
	'cu' => 'Cuba',
	'cy' => 'Cyprus',
	'cz' => 'República Checa',
	'dk' => 'Dinamarca',
	'dj' => 'Djibouti',
	'dm' => 'Dominica',
	'do' => 'República Dominicana',
	'ec' => 'Ecuador',
	'eg' => 'Egipto',
	'sv' => 'El Salvador',
	'gq' => 'Equatorial Guinea',
	'er' => 'Eritrea',
	'ee' => 'Estonia',
	'et' => 'Ethiopia',
	'fk' => 'Falkland Islands (malvinas)',
	'fo' => 'Faroe Islands',
	'fj' => 'Fiji',
	'fi' => 'Finlandia',
	'fr' => 'Francia',
	'gf' => 'French Guiana',
	'pf' => 'French Polynesia',
	'tf' => 'French Southern Territories',
	'ga' => 'Gabon',
	'gm' => 'Gambia',
	'ge' => 'Georgia',
	'de' => 'Alemania',
	'gh' => 'Ghana',
	'gi' => 'Gibraltar',
	'gr' => 'Grecia',
	'gl' => 'Groenlandia',
	'gd' => 'Grenada',
	'gp' => 'Guadeloupe',
	'gu' => 'Guam',
	'gt' => 'Guatemala',
	'gn' => 'Guinea',
	'gw' => 'Guinea-Bissau',
	'gy' => 'Guyana',
	'ht' => 'Haití',
	'hm' => 'Heard Island and Mcdonald Islands',
	'va' => 'Holy See (Vatican City)',
	'hn' => 'Honduras',
	'hu' => 'Hungary',
	'is' => 'Iceland',
	'in' => 'India',
	'id' => 'Indonesia',
	'ir' => 'Iran, Islamic Republic of',
	'iq' => 'Iraq',
	'ie' => 'Ireland',
	'il' => 'Israel',
	'it' => 'Italia',
	'jm' => 'Jamaica',
	'jp' => 'Japón',
	'jo' => 'Jordán',
	'kz' => 'Kazakhstan',
	'ke' => 'Kenya',
	'ki' => 'Kiribati',
	'kp' => 'Democratic People\'s Republic of Korea',
	'kr' => 'Republic of Korea',
	'kw' => 'Kuwait',
	'kg' => 'Kyrgyzstan',
	'la' => 'Lao People\'s Democratic Republic',
	'lv' => 'Latvia',
	'lb' => 'Lebanon',
	'ls' => 'Lesotho',
	'lr' => 'Liberia',
	'ly' => 'Libyan Arab Jamahiriya',
	'li' => 'Liechtenstein',
	'lt' => 'Lithuania',
	'lu' => 'Luxembourg',
	'mo' => 'Macao',
	'mk' => 'Macedonia, The Former Yugoslav Republic of',
	'mg' => 'Madagascar',
	'mw' => 'Malawi',
	'my' => 'Malaysia',
	'mv' => 'Maldives',
	'ml' => 'Mali',
	'mt' => 'Malta',
	'mh' => 'Marshall Islands',
	'mq' => 'Martinique',
	'mr' => 'Mauritania',
	'mu' => 'Mauritius',
	'yt' => 'Mayotte',
	'mx' => 'México',
	'fm' => 'Micronesia, Federated States of',
	'md' => 'Moldova, Republic of',
	'mc' => 'Monaco SAR',
	'mn' => 'Mongolia',
	'me' => 'Montenegro',
	'ms' => 'Montserrat',
	'ma' => 'Morocco',
	'mz' => 'Mozambique',
	'na' => 'Namibia',
	'nr' => 'Nauru',
	'np' => 'Nepal',
	'nl' => 'Netherlands',
	'an' => 'Netherlands Antilles',
	'nc' => 'New Caledonia',
	'nz' => 'New Zealand',
	'ni' => 'Nicaragua',
	'ne' => 'Niger',
	'ng' => 'Nigeria',
	'nu' => 'Niue',
	'nf' => 'Norfolk Island',
	'mp' => 'Northern Mariana Islands',
	'no' => 'Norway',
	'om' => 'Oman',
	'pk' => 'Pakistan',
	'pw' => 'Palau',
	'ps' => 'Palestinian Territory',
	'pa' => 'Panamá',
	'pg' => 'Papua New Guinea',
	'py' => 'Paraguay',
	'pe' => 'Perú',
	'ph' => 'Philippines',
	'pn' => 'Pitcairn',
	'pl' => 'Polonia',
	'pt' => 'Portugal',
	'pr' => 'Puerto Rico',
	'qa' => 'Qatar',
	're' => 'Reunion',
	'ro' => 'Romania',
	'ru' => 'Russian Federation',
	'rw' => 'Rwanda',
	'sh' => 'Saint Helena',
	'kn' => 'Saint Kitts and Nevis',
	'lc' => 'Saint Lucia',
	'pm' => 'Saint Pierre and Miquelon',
	'vc' => 'Saint Vincent and the Grenadines',
	'ws' => 'Samoa',
	'sm' => 'San Marino',
	'st' => 'Sao Tome and Principe',
	'sa' => 'Saudi Arabia',
	'sn' => 'Senegal',
	'rs' => 'Serbia',
	'sc' => 'Seychelles',
	'sl' => 'Sierra Leone',
	'sg' => 'Singapore',
	'sk' => 'Slovakia',
	'si' => 'Slovenia',
	'sb' => 'Solomon Islands',
	'so' => 'Somalia',
	'za' => 'South Africa',
	'gs' => 'South Georgia and the South Sandwich Islands',
	'es' => 'Spain',
	'lk' => 'Sri Lanka',
	'sd' => 'Sudan',
	'sr' => 'Suriname',
	'sj' => 'Svalbard and Jan Mayen',
	'sz' => 'Swaziland',
	'se' => 'Sweden',
	'ch' => 'Switzerland',
	'sy' => 'Syrian Arab Republic',
	'tj' => 'Tajikistan',
	'tz' => 'Tanzania, United Republic of',
	'th' => 'Thailand',
	'tl' => 'Timor-leste',
	'tg' => 'Togo',
	'tk' => 'Tokelau',
	'to' => 'Tonga',
	'tt' => 'Trinidad and Tobago',
	'tn' => 'Tunisia',
	'tr' => 'Turkey',
	'tm' => 'Turkmenistan',
	'tc' => 'Turks and Caicos Islands',
	'tv' => 'Tuvalú',
	'ug' => 'Uganda',
	'ua' => 'Ucrania',
	'ae' => 'Emiratos Árabes Unidos',
	'gb' => 'Reino Unido',
	'us' => 'Estados Unidos',
	'um' => 'United States Minor Outlying Islands',
	'uy' => 'Uruguay',
	'uz' => 'Uzbekistán',
	'vu' => 'Vanuatú',
	've' => 'Venezuela',
	'vn' => 'VietNam',
	'vg' => 'Virgin Islands, British',
	'vi' => 'Virgin Islands, U.S.',
	'wf' => 'Wallis and Futuna',
	'eh' => 'Western Sahara',
	'ye' => 'Yemen',
	'zm' => 'Zambia',
	'zw' => 'Zimbabwe'
);
