<?php

$lang_register_form = array(
'registration_title' => 'Wikimania 2011 Registrierung',
'select' => 'Bitte wählen',
'query' => 'Registrierungsstatus abrufen',
'query_title' => 'Sie können den Status Ihrer Wikimania-Registrierung hier abrufen.',
'correction' => 'Ihre Daten enthalten Fehler und konnten daher nicht übermittelt werden.',

'legend1' => 'Persönliche Informationen',
'title1' =>
'<p><strong>Persönliche Identitätsdaten</strong></p>',
'surname' => 'Nachname',
'given_name' => 'Vorname',
'sex' => 'Geschlecht',
'sex1' => 'männlich',
'sex2' => 'weiblich',
'sex3' => 'keine Angabe',
'passport' => 'Reisepass-Nummer',
'passport_valid' => 'Gültigkeit des Reisepasses (TT/MM/JJJJ)<br><small>Ihr Reisepass muss noch mindestens sechs Monate gültig sein.</small>',
'passport_issued' => 'Ausstellungsort',
'country' => 'Land des aktuellen Wohnorts',
'birthday' => 'Geburtsdatum (TT/MM/JJJJ)',
'year1' => '',
'year' => '',
'month' => '',
'months' => array( NULL, 'Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember' ),
'day' => '',
'title2' =>
'        <p><strong>Sprachkenntnisse</strong></p>',
'langn' => 'Muttersprache',
'lang' => 'Weitere Sprachen',
'select_lang' => 'bitte Sprache auswählen',
'select_level' => 'bitte Fähgkeit angeben',

'lang_level1' => '1 (Grundlagen)',
'lang_level2' => '2 (fortgeschritten)',
'lang_level3' => '3 (sehr gut)',
'lang_level4' => '4 (muttersprachliches Niveau)',

'lang1' => 'Sprache 1',
'lang2' => 'Sprache 2',
'lang3' => 'Sprache 3',

'lang1_level' => 'Sprachkenntnis für Sprache 1',
'lang2_level' => 'Sprachkenntnis für Sprache 2',
'lang3_level' => 'Sprachkenntnis für Sprache 3',

'title3' =>
'<p><strong>Wikimedia-Projekt und E-Mail-Adresse</strong></p>
<p>Ihre E-Mail-Adresse wird ausschliesslich für die Registrierung sowie dringende Benachrichtigungen zur Wikimania 2011 verwendet.
</p>
',
'wiki_id' => 'Wikimedia-Benutzername',
'email' => 'E-Mail-Adresse',

'legend2' => 'Teilnahme',
'title4' =>
'<p><strong>Teilnahme, Namensschild und Allgemeines</strong></p>',
'join_date' => 'Teilnahme an folgenden Tagen:',
'join1' => 'Dienstag, 2. August 2011',
'join2' => 'Mittwoch, 3. August 2011',
'join3' => 'Donnerstag, 4. August 2011',
'join4' => 'Freitag, 5. August 2011',
'join5' => 'Samstag, 6. August 2011',
'join6' => 'Sonntag, 7. August 2011',
'join7' => 'Montag, 8. August 2011',
'showname' => 'Namensschild',
'custom_showname' => 'Gewünschter Name auf dem Namensschild',
'showname1' => 'Name',
'showname2' => 'Wikimedia-Benutzername',
'showname3' => 'Weitere Informationen:',
'size' => 'T-Shirt-Grösse',
'food' => 'Ernährungseinschränkungen<br><small>Alle Mahlzeiten während der Konferenz werden kosher zubereitet.</small>',
'food0' => 'keine',
'food1' => 'Vegetarier',
'food2' => 'Halal',
'food_other' => 'Andere:',

'title_visa' =>
'<p><strong>Visum</strong></p>
<p>Wenn Ihr Reisepass von <a href=http://wikimania2011.wikimedia.org/wiki/Visas#Visa_required>einem Land ausgestellt wurde, für das ein Visum zur Einreise nach Israel benötigt wird</a>, füllen Sie bitte die folgenden Angaben aus, damit das Organisationsteam Ihre Daten an das israelische Aussenministerium weitergeben kann.',
'need_visa_assistance' => 'Ja, ich benötige ein Visum zur Einreise nach Israel',
'visa_assistance' => 'Visum-Antrag',
'visa_assistance_description' => 'Spezielle Anforderungen im Bezug auf den Visums-Antrag (auf <strong>Englisch</strong>)',

'title5' =>
'<p><strong>Übernachtung</strong></p>
<p>Sie können in einem Hotel oder in einem Wohnheim übernachten.
Bitte informieren Sie sich auf der <a href=http://wikimania2011.wikimedia.org/wiki/Accommodation>Übernachtungsseite</a> wegen den genauen <b>Preisen</b>, Lage und weiteren Details.</p>',
'accommodation_hotel' => 'Gewünschte Übernachtungsmöglichkeit<br><b><small>(<a href=http://wikimania2011.wikimedia.org/wiki/Accommodation onClick="return popup(this, \'prices\')">Preise</a>)</small></b>',
'hotel1' => 'Studentenwohnheim',
'hotel2' => 'Ganei Dan',
'hotel3' => 'Marom',
'hotel4' => 'Har HaCarmel',
'hotel5' => 'Nof',
'hotel6' => 'Dan Panorama',
'hotel7' => 'Crown Plaza',
'hotel8' => 'Colony',
'hotel9' => 'Galery',
'hotel3stars' => 'Drei-Sterne Hotels',
'hotel4stars' => 'Vier-Sterne Hotels',
'hotel5stars' => 'Fünf-Sterne Hotels',
'hotelboutique' => 'Boutique-Hotels',

'accommodation' => 'Nächte in denen Übernachtung benötigt wird',
'night1' => 'Montag, 1. August 2011',
'night2' => 'Diensta, 2. August 2011',
'night3' => 'Mittwoch, 3. August 2011',
'night4' => 'Donnerstag, 4. August, 2011',
'night5' => 'Freitag, 5. August 2011',
'night6' => 'Samstag, 6. August 2011',
'night7' => 'Sonntag, 7. August 2011',
'night8' => 'Montag, 8. August 2011',
'room' => 'Gewünschtes Zimmer',
'room1' => 'Einzelbelegung',
'room2' => 'Doppelbelegung mit einem zufällig gewählten Teilnehmer gleichen Geschlechts',
'room3' => 'Doppelbelegung mit einem bestimmten Partner (bitte vollen Namen angeben):',
'room_requests' => 'Besondere Anforderungen an die Übernachtung (zB. rollstuhlgerecht)',
'room_partner' => 'Zimmerpartner',
'title6' =>
'<p><strong>Zahlweise</strong></p>
<p>Die Bezahlung der Konferenzgebühren und Übernachtung erfolgt via PayPal während der Registrierung.<br></p>',
'title7' =>
'<p><strong>CAPTCHA</strong></p><p>Um sicherzustellen dass Sie ein echter Mensch und kein Bot sind bitten wir Sie dieses CAPTCHA auszufüllen.</p>',
'discount_code' => 'Rabatt-Code<br><small>Wenn Sie einen Rabatt-Code erhalten haben geben Sie diesen bitte hier ein.</small>',
'submit_notice' =>
'<li><strong>Nachdem Sie das Formular abgeschickt haben, haben Sie die Möglichkeit Ihre Daten noch einmal zu überprüfen.</strong></li>',
'asterix_meaning' =>
'<li><strong>Felder, die mit einem Stern (*) markiert sind, müssen zwingend ausgefüllt werden.</strong></li>',
'submit' => 'Absenden',
'reset' => 'löschen',

'confirm' => 'Überprüfen',
'confirm_description' => 'Bevor Sie das Formular absenden, überprüfen Sie bitte, dass alle Daten korrekt sind:',

'paypal' => 'Bezahlung via PayPal',
'paypal_description' =>
'<p>Bitte benutzen sie den "Pay Now"-Button unten um <b>jetzt</b> via PayPal zu bezahlen!</p> ',
'paypal_failed' => 'Bezahlung via PayPal abbrechen',
'paypal_failed_description' => '<p>Sie können erneut versuchen die untenstehenden Felder auszufüllen oder Sie können später bezahlen indem Sie den Betrag via Paypal an <b>finance@wikimedia.org.il</b> überweisen, denken Sie dann aber bitte daran Ihren Registrierungscode in der Beschreibung anzugeben.</p>',
'paypal_successful' => 'die Bezahlung via PayPal war erfolgreich',
'paypal_successful_description' => '<p>Vielen Dank! Wir werden Sie über Ihre Buchung benachrichtigen sobald wir die Überweisung durch PayPal erhalten und Ihre Registrierungsdaten geprüft haben.</p>',

'hackingdays' => 'Entwicklertreffen und weitere Treffen',
'maindays' => 'Haupt-Konferenz',
'tourdays' => 'Tour-Tag',
'color' => 'T-Shirt-Farbe',
'white' => 'weiss',
'black' => 'schwarz',
'nationality' => 'Reisepass ausgestellt durch',
'countryofbirth' => 'Geburtsland',
'homeaddress' => 'Heimatadresse',
'picktour' => 'Gewünschte Tour',
'tour0' => 'kein bestimmter Wunsch',
'tour1' => 'Nazareth und See Galiläa',
'tour2' => 'Jerusalem',
'tour3' => 'Akkon (Acco)',
'tour4' => 'die Hängenden Gärten der Bahai',
'tour5' => 'Drusen-Dörfer',
'main_date' => 'Haupt-Konferenztag',
'captcha' => 'CAPTCHA-Information'
);


$lang_messages = array(
'successful' => 'Registrierung abgeschlossen',
'successful_description' =>
'<p>Vielen Dank für Ihre Teilnahme an Wikimania 2011! Ihre Registrierun wurde übermittelt. Bitte beachten Sie, dass Sie die Zahlung vornehmen müssen, bevor die Registrierung bestätigt werden kann.

Ihre <strong>Registrierungsnummer</strong> wird unten angezeigt. Bitte notieren Sie sich diese Nummer, da Sie sie benötigen um Ihren Registrierungsstatus abzufragen und zukünftig Ihre Identität zu prüfen.
',
'cost' => 'Registrierungsgebühr: ',
'attendance_cost' => 'Konferenz: ',
'accommodation_cost' => 'Übernachtung: ',
'vat_cost' => 'MWSt: ',
'other_cost' => 'zusätzliche Kosten: ',
'total_cost' => 'Summe: ',
'usd' => ' USD',
);

$lang_errors = array(
'repeat' => 'Es hat sich bereits jemand mit diesem Namen und dieser E-Mail-Adresse registriert. Es kann sein, dass Sie das Formular zweimal abgeschickt oder die Registrierungsseite neu geladen haben.',
'not_input' => '$1 ist leer.',
'not_input_completely' => '$1 ist nicht vollständig.',
'not_select' => '$1 ist nicht ausgewählt.',
'not_select_whether' => '$1 ist nicht angegeben.',
'too_long' => '$1 ist zu lang, die maximale Länge ist $2.',
'incorrect' => '$1 ist nicht korrekt.',
'wrong' => '$1 ist falsch.',
'visa_assistance_incomplete' => 'Visa-Angaben fehlen.',
'wrong_query' => 'Falscher Name oder Registrierungsnummer.',
'paypal_unavailable' => 'Das gewählte Land / die gewählte Region wird von PayPal nicht unterstützt.'
);

$lang_query = array(
'query_title' => 'Übersicht Registrierungsstatus',
'unique_code' => 'Registrierungsnummer:',
'submit' => 'abfragen',
'your_status' => 'Willkommen $1, dies ist der Status Ihrer Registrierung:',
'received_money' => 'Registrierungsgebühr (erhalten / erwartet):',
'lack' => 'noch nicht vollständig bezahlt',
'enough' => 'vollständig bezahlt',
'too_much' => 'zuviel bezahlt',
'accepted' => 'Ihre Registrierung wurde <strong>bestätigt</strong>.',
'rejected' => 'Ihre Registrierung wurde <strong>abgelehnt</strong>.',
'not_yet' => 'Ihre Registrierung wurde <strong>erhalten, aber noch nicht bestätigt</strong>.'
);

$lang_countries = array(
      'af' => 'Afghanistan',
      'ax' => 'Aland Islands',
      'al' => 'Albanien',
      'dz' => 'Algerien',
      'as' => 'American Samoa',
      'ad' => 'Andorra',
      'ao' => 'Angola',
      'ai' => 'Anguilla',
      'aq' => 'Antarctica',
      'ag' => 'Antigua und Barbuda',
      'ar' => 'Argentinien',
      'am' => 'Armenien',
      'aw' => 'Aruba',
      'au' => 'Australien',
      'at' => 'Österreich',
      'az' => 'Azerbaijan',
      'bs' => 'Bahamas',
      'bh' => 'Bahrain',
      'bd' => 'Bangladesh',
      'bb' => 'Barbados',
      'by' => 'Weissrussland',
      'be' => 'Belgien',
      'bz' => 'Belize',
      'bj' => 'Benin',
      'bm' => 'Bermuda',
      'bt' => 'Bhutan',
      'bo' => 'Bolivien',
      'ba' => 'Bosnien und Herzegovina',
      'bw' => 'Botswana',
      'bv' => 'Bouvet Island',
      'br' => 'Brasilien',
      'io' => 'British Indian Ocean Territory',
      'bn' => 'Brunei Darussalam',
      'bg' => 'Bulgarien',
      'bf' => 'Burkina Faso',
      'mm' => 'Burma (Myanmar)',
      'bi' => 'Burundi',
      'kh' => 'Kambodscha',
      'cm' => 'Kamerun',
      'ca' => 'Kanada',
      'cv' => 'Cape Verde',
      'ky' => 'Cayman Islands',
      'cf' => 'Zentralafrikanische Republik',
      'td' => 'Tschad',
      'cl' => 'Chile',
      'hk' => 'Hong Kong SAR',
      'cn' => 'Volksrepublik China',
      'tw' => 'Republik China (Taiwan)',
      'cx' => 'Christmas Island',
      'cc' => 'Cocos (keeling) Islands',
      'co' => 'Colombia',
      'km' => 'Comoros',
      'cg' => 'Congo',
      'cd' => 'Congo\, The Democratic Republic of the',
      'ck' => 'Cook Islands',
      'cr' => 'Costa Rica',
      'ci' => 'Cote D\'ivoire',
      'hr' => 'Croatia',
      'cu' => 'Cuba',
      'cy' => 'Cyprus',
      'cz' => 'Czech Republic',
      'dk' => 'Dänemark',
      'dj' => 'Djibouti',
      'dm' => 'Dominica',
      'do' => 'Dominican Republic',
      'ec' => 'Equador',
      'eg' => 'Ägypten',
      'sv' => 'El Salvador',
      'gq' => 'Equatorial Guinea',
      'er' => 'Eritrea',
      'ee' => 'Estland',
      'et' => 'Äthiopien',
      'fk' => 'Falkland Islands (malvinas)',
      'fo' => 'Faroe Islands',
      'fj' => 'Fiji',
      'fi' => 'Finnland',
      'fr' => 'Frankreich',
      'gf' => 'French Guiana',
      'pf' => 'French Polynesia',
      'tf' => 'French Southern Territories',
      'ga' => 'Gabon',
      'gm' => 'Gambia',
      'ge' => 'Georgia',
      'de' => 'Deutschland',
      'gh' => 'Ghana',
      'gi' => 'Gibraltar',
      'gr' => 'Greece',
      'gl' => 'Greenland',
      'gd' => 'Grenada',
      'gp' => 'Guadeloupe',
      'gu' => 'Guam',
      'gt' => 'Guatemala',
      'gn' => 'Guinea',
      'gw' => 'Guinea-Bissau',
      'gy' => 'Guyana',
      'ht' => 'Haiti',
      'hm' => 'Heard Island and Mcdonald Islands',
      'va' => 'Holy See (Vatican City)',
      'hn' => 'Honduras',
      'hu' => 'Hungary',
      'is' => 'Iceland',
      'in' => 'India',
      'id' => 'Indonesia',
      'ir' => 'Iran, Islamic Republic of',
      'iq' => 'Iraq',
      'ie' => 'Ireland',
      'il' => 'Israel',
      'it' => 'Italy',
      'jm' => 'Jamaica',
      'jp' => 'Japan',
      'jo' => 'Jordan',
      'kz' => 'Kazakhstan',
      'ke' => 'Kenya',
      'ki' => 'Kiribati',
      'kp' => 'Democratic People\'s Republic of Korea',
      'kr' => 'Republic of Korea',
      'kw' => 'Kuwait',
      'kg' => 'Kyrgyzstan',
      'la' => 'Lao People\'s Democratic Republic',
      'lv' => 'Latvia',
      'lb' => 'Lebanon',
      'ls' => 'Lesotho',
      'lr' => 'Liberia',
      'ly' => 'Libyan Arab Jamahiriya',
      'li' => 'Liechtenstein',
      'lt' => 'Lithuania',
      'lu' => 'Luxembourg',
      'mo' => 'Macao',
      'mk' => 'Macedonia, The Former Yugoslav Republic of',
      'mg' => 'Madagascar',
      'mw' => 'Malawi',
      'my' => 'Malaysia',
      'mv' => 'Maldives',
      'ml' => 'Mali',
      'mt' => 'Malta',
      'mh' => 'Marshall Islands',
      'mq' => 'Martinique',
      'mr' => 'Mauritania',
      'mu' => 'Mauritius',
      'yt' => 'Mayotte',
      'mx' => 'Mexico',
      'fm' => 'Micronesia, Federated States of',
      'md' => 'Moldova, Republic of',
      'mc' => 'Monaco SAR',
      'mn' => 'Mongolia',
      'me' => 'Montenegro',
      'ms' => 'Montserrat',
      'ma' => 'Morocco',
      'mz' => 'Mozambique',
      'na' => 'Namibia',
      'nr' => 'Nauru',
      'np' => 'Nepal',
      'nl' => 'Netherlands',
      'an' => 'Netherlands Antilles',
      'nc' => 'New Caledonia',
      'nz' => 'New Zealand',
      'ni' => 'Nicaragua',
      'ne' => 'Niger',
      'ng' => 'Nigeria',
      'nu' => 'Niue',
      'nf' => 'Norfolk Island',
      'mp' => 'Northern Mariana Islands',
      'no' => 'Norway',
      'om' => 'Oman',
      'pk' => 'Pakistan',
      'pw' => 'Palau',
      'ps' => 'Palestinian Territory',
      'pa' => 'Panama',
      'pg' => 'Papua New Guinea',
      'py' => 'Paraguay',
      'pe' => 'Peru',
      'ph' => 'Philippines',
      'pn' => 'Pitcairn',
      'pl' => 'Poland',
      'pt' => 'Portugal',
      'pr' => 'Puerto Rico',
      'qa' => 'Qatar',
      're' => 'Reunion',
      'ro' => 'Romania',
      'ru' => 'Russian Federation',
      'rw' => 'Rwanda',
      'sh' => 'Saint Helena',
      'kn' => 'Saint Kitts and Nevis',
      'lc' => 'Saint Lucia',
      'pm' => 'Saint Pierre and Miquelon',
      'vc' => 'Saint Vincent and the Grenadines',
      'ws' => 'Samoa',
      'sm' => 'San Marino',
      'st' => 'Sao Tome and Principe',
      'sa' => 'Saudi Arabia',
      'sn' => 'Senegal',
      'rs' => 'Serbia',
      'sc' => 'Seychelles',
      'sl' => 'Sierra Leone',
      'sg' => 'Singapore',
      'sk' => 'Slovakia',
      'si' => 'Slovenia',
      'sb' => 'Solomon Islands',
      'so' => 'Somalia',
      'za' => 'South Africa',
      'gs' => 'South Georgia and the South Sandwich Islands',
      'es' => 'Spain',
      'lk' => 'Sri Lanka',
      'sd' => 'Sudan',
      'sr' => 'Suriname',
      'sj' => 'Svalbard and Jan Mayen',
      'sz' => 'Swaziland',
      'se' => 'Sweden',
      'ch' => 'Switzerland',
      'sy' => 'Syrian Arab Republic',
      'tj' => 'Tajikistan',
      'tz' => 'Tanzania, United Republic of',
      'th' => 'Thailand',
      'tl' => 'Timor-leste',
      'tg' => 'Togo',
      'tk' => 'Tokelau',
      'to' => 'Tonga',
      'tt' => 'Trinidad and Tobago',
      'tn' => 'Tunisia',
      'tr' => 'Turkey',
      'tm' => 'Turkmenistan',
      'tc' => 'Turks and Caicos Islands',
      'tv' => 'Tuvalu',
      'ug' => 'Uganda',
      'ua' => 'Ukraine',
      'ae' => 'United Arab Emirates',
      'gb' => 'United Kingdom',
      'us' => 'United States',
      'um' => 'United States Minor Outlying Islands',
      'uy' => 'Uruguay',
      'uz' => 'Uzbekistan',
      'vu' => 'Vanuatu',
      've' => 'Venezuela',
      'vn' => 'Viet Nam',
      'vg' => 'Virgin Islands, British',
      'vi' => 'Virgin Islands, U.S.',
      'wf' => 'Wallis and Futuna',
      'eh' => 'Western Sahara',
      'ye' => 'Yemen',
      'zm' => 'Zambia',
      'zw' => 'Zimbabwe'
);

?>
