#!/usr/bin/python
import sys, subprocess, ldapsupportlib
from optparse import OptionParser

def main():
	parser = OptionParser(conflict_handler="resolve")
	parser.set_usage('add-labs-user --wikiname="Wiki Name" --mail="wikiname@domain.org" <username>')

	parser.add_option("--wikiname", action="store", dest="wikiname", help="Set the user's wiki name (required)")
	parser.add_option("--mail", action="store", dest="mail", help="Set the user's email address (required)")
	(options, args) = parser.parse_args()

	if len(args) != 1:
		parser.error("Username is required.\n")

	if not (options.wikiname and options.mail):
		parser.error("--wikiname and --mail options are required.\n")

	username = args[0]

	# Set a random password for the user
	passwdargs = ['/usr/local/bin/change-ldap-passwd', '--random', username]
	passwd = subprocess.Popen(passwdargs, stdout=subprocess.PIPE).communicate()[0]

	# Set the user's CN and email address
	passwdargs = ['/usr/local/bin/modify-ldap-user', '--cn=' + options.wikiname, '--mail=' + options.mail, username]
	ignore = subprocess.Popen(passwdargs, stdout=subprocess.PIPE).communicate()[0]

	# Do an initial log in as the user, which will cause the wiki to create an account
	# for the user.
	data = {'action': 'login',
		'lgname': username,
		'lgpassword': passwd,
		'lgdomain': scriptconfig.domain
		}
	postdata = urllib.urlencode(data)
	resp = urllib.urlopen(scriptconfig.controllerapiurl, data=postdata)
	if resp.code != 200:
		print resp.read()
	resp.close()

if __name__ == "__main__":
	main()
