# This is a configuration file for our cgi-bin/export script


limits:
  # Maximum load before we start to refuse service
  max_load: 40.0

  # Resource limits passed to setrlimit(3)
  rlimit:
    as:
      min: 4000000000
      max: 4000000000

    cpu:
      min: 300
      max: 300

maptypes:
  - osm-like

caching:
  max-age: 604800

# Where to read our list of languages from
locales: /sql/misc-data/wikipedia-languages.yml  

# Interface with renderd
renderd:
  socket: /var/run/renderd/renderd.sock
